### ISSUE TITLE
problem with date widget

### ISSUE THREAD

**Issue by EmilianoMorello** [sehmaschine/django-grappelli#1005]
hello, I recently installed grappelli. I encountered a problem on the data widget. the text "today" is not displayed correctly. Look at the photo.
![date](https://user-images.githubusercontent.com/53911234/203417812-84e1adac-5b71-4a14-ad6d-b59621370917.jpg)
I also saw that the text is not translated correctly (into Italian for example)
![calendar](https://user-images.githubusercontent.com/53911234/203418000-8d8cd873-fc72-41fc-a9f3-369cedfb4a43.jpg)
Can you do anything to help me?
Thanks!

**Comment by sehmaschine** [comment]
this looks like some js is not being loaded correctly. I assume it's either cached (wrong) or the setup is incorrect. not much we can do about that ... but you should be able to debug the issue yourself. and come back here if you think it's a bug.
