### ISSUE TITLE
FileNotFoundError after upgrade to 3.0.5 which removes jQuery UI's package.json with existing collected staticfiles

### ISSUE THREAD

**Issue by florianm** [sehmaschine/django-grappelli#1014]
### Issue
After upgrading django-grappelli to 3.0.5, tests were failing with 
```
FileNotFoundError: [Errno 2] No such file or directory: '[...]/staticfiles/grappelli/jquery/ui/package.json'
```

### Solution
I had to delete and recreate staticfiles
```
rm -rf staticfiles/
mkdir staticfiles/
./manage.py collectstatic -l
```

This is only an issue with existing collected staticfiles.
When deploying Django via Docker images which run a fresh collectstatic into a new image layer this issue does not occur.

**Comment by sehmaschine** [comment]
Thanks for the info. But if I understand correctly, this is not a bug. There is actually nothing we can do about it... right?

**Comment by florianm** [comment]
Apart from a warning in the release notes or in the code (which I feel would be overkill), this issue should be discoverable enough for any fellow grappelli users running into the same error.
