### ISSUE TITLE
Collectstatic Post-processing failing to find CSS files

### ISSUE THREAD

**Issue by victorvaldez5** [sehmaschine/django-grappelli#1023]
VERSIONS: Grappelli 3.0.7, Django 4.2
STATICFILES: ERROR, 
CUSTOMIZATIONS: custom ManifestStaticFilesStorage that we wrote for minifying static files and cache breaking. That we  adapted from https://github.com/askholme/django_minifiedstorage/blob/master/minifiedstorage/storages.py

## Problem
We are migrating to from Django 3.2 to Django 4.2 right now, and when I try to run `collectstatic` I get this error:
 
<img width="960" alt="Screenshot 2023-08-30 at 4 21 53 PM" src="https://github.com/sehmaschine/django-grappelli/assets/12886746/f0e400af-002a-482b-8165-0e6d8880451d">

When I dug into the grappelli files and my collect static folder, it appears that those image files do exist though. 
<img width="708" alt="Screenshot 2023-08-30 at 4 24 05 PM" src="https://github.com/sehmaschine/django-grappelli/assets/12886746/aaf7ea52-2d75-4aef-ad49-ee5b838a93e1">

I dug a little more and tracked down the problem to `jquery-ui.css` and `jquery-ui.theme.css`. My current work around is to copy those files and put them in my static folder and removing any references to the png file it is complaining about. What is odd is that it is only happening for that specific png file, it is able to handle other png files fine.

**Comment by arconamagi** [comment]
I have the same issue

**Comment by sehmaschine** [comment]
merged with master. please give it a test and let me know if it works as expected (it works fine with my setup/tests).
