### ISSUE TITLE
Autocomplete_fields for inlines that are added after the initial are empty

### ISSUE THREAD

**Issue by jTiKey** [sehmaschine/django-grappelli#1027]
django==4.2.4 
django-grappelli==3.0.7

When using inlines and autocomplete, it doesn't load the autocomplete for new forms:

<img width="280" alt="image" src="https://github.com/sehmaschine/django-grappelli/assets/1391925/224fc061-d9e7-4239-ad22-71e1a8f9817c">

while the initial ones are fine:

<img width="263" alt="image" src="https://github.com/sehmaschine/django-grappelli/assets/1391925/b8cb62e5-7eb1-4cbe-9a72-d3740538a6ac">

admin.py:

```
class InstitutionServiceInline(admin.TabularInline):
    model = InstitutionService
    extra = 5
    autocomplete_fields = ('service',)


@admin.register(Institution)
class InstitutionAdmin(TimyMCEAdmin, admin.ModelAdmin):
    list_display = ('name', 'city', 'created', 'modified')
    search_fields = ('name', 'city__name')
    list_filter = ('city',)
    autocomplete_fields = ('city', 'services')
    inlines = [InstitutionServiceInline]
```

It works properly if grappelli is disabled.

**Comment by sehmaschine** [comment]
I guess you are referring to the Django Autocompletes (the ones that come with Grappelli should work). We'll check that ... if it's urgent, please submit a PR.

**Comment by jTiKey** [comment]
Yeah, it's the Django Autocomplete. I suspect the JS code isn't being loaded when generating new fields. It's not urgent.

**Comment by sehmaschine** [comment]
Not exactly sure if that fixes all usecases, but I guess it doese. Maybe you can give it a try and let me know if it works with your setup (it does with my tests).

**Comment by sehmaschine** [comment]
In that case, there might be something wrong with your setup. I’ve tested
it and I’m pretty sure it works.

**Comment by jTiKey** [comment]
I see. Thanks for the help. I've dropped the need for this relation so it's not that important anymore.

**Comment by jTiKey** [comment]
Yeah, I've pulled the specific commit and confirmed the change it in jquery.grp_inline.js. But I cannot find this file being loaded into on the page.
