### ISSUE TITLE
drag&drop fails due to validation rule on empty element

### ISSUE THREAD

**Issue by lsmith77** [sehmaschine/django-grappelli#1033]
Django Admin always adds an empty element to my list of relationships (ie. the one with the `-` at the end in the below screenshot). 

<img width="157" alt="image" src="https://github.com/sehmaschine/django-grappelli/assets/300279/1ce31f10-721e-4c29-93f3-a619e2171ef7">

The problem is that when I save now, the validation rule triggers because of the ordering property being filled.

How can I prevent this?

I would also be fine if I could figure out how to prevent this default empty element from being added to the list of relationships.

**Comment by sehmaschine** [comment]
are you sure it's because of the ordering field (because that should not be the case). other fields can be excluded with `sortable_excludes`.

**Comment by lsmith77** [comment]
I cannot definitively say so but I tried to quickly reproduce the issue on an inline model without ordering and I was unable to.

**Comment by sehmaschine** [comment]
closing this for now. please reopen, if the issue still exists.
