### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by alfreedom** [sehmaschine/django-grappelli#1039]
The logout button in the admin page doesn't work, it makes a GET request to the path `/admin/logout/` but a POST request is expected.

https://github.com/sehmaschine/django-grappelli/blob/187fc6b3ab0d8860a2e86e0e6f53a40632901a7d/grappelli/templates/admin/base.html#L106

<img width="527" alt="image" src="https://github.com/sehmaschine/django-grappelli/assets/6258387/6c84129b-bf9a-401c-a52d-685948ee507f">

A quick fix would be:

```html
<li>
  <form id="logout-form" method="post" action="{% url 'admin:logout' %}">
    {% csrf_token %}
    <a href="#" class="grp-logout" onclick="document.getElementById('logout-form').submit()"> 
      {% translate 'Log out' %}
    </a>
  </form>
</li>
```

According to release notes from django 4.1, the Log out via GET request is deprecated:

https://docs.djangoproject.com/en/4.1/releases/4.1/#log-out-via-get

**Comment by duanyu1988** [comment]
Nice work!
