### ISSUE TITLE
Autocomplete search button throws 403 on User proxy model

### ISSUE THREAD

**Issue by kenricci** [sehmaschine/django-grappelli#1045]
I have a proxy model to the auth.User model using grappelli 3.0.8.  I set up an autocomplete to the proxy model which works fine when typing a portion of the user name in the text box.  However, when a user clicks on the magnifying glass lookup button, the system throws a 403 error.  

If the user has superuser rights, it works.  I tried added auth.user view permissions, but it won't work for a standard user.

![autocomplete_typing](https://github.com/sehmaschine/django-grappelli/assets/2746850/3a29c86c-6857-426f-b9c1-3eae84aea315)
![autocomplete_button_403](https://github.com/sehmaschine/django-grappelli/assets/2746850/90f0b6c3-0b4a-4d86-b498-9f064866354a)

**Comment by sehmaschine** [comment]
does it work without the autocomplete (e.g. with a raw id field)?

**Comment by kenricci** [comment]
No.  Still throws a 403.  I have turned off the lookup button with css for
now as the autocomplete works

**Comment by sehmaschine** [comment]
I'm not sure this is related to grappelli. The magnifying glass opens a new window based on django permissions – did you register that (proxy) model with the admin?

**Comment by kenricci** [comment]
Doh!  I had view permission for the auth.User model, not the proxy.  It now
works exactly as it shows.

Sorry for the trouble!

Thank you for your prompt response.

Regards,
Ken
