### ISSUE TITLE
Multiple fields on the same line seems broken

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#1047]
@parsch Not sure if that's alredy solved (and just not released), but multiple fields on the same line does not seem to work with the latest official release.

**Comment by parsch** [comment]
@sehmaschine Not sure what you mean exactly, can you screenshot an example?

**Comment by parsch** [comment]
@sehmaschine using branch stable/3.0.x this looks as expected in my env:
 
<img width="1224" alt="Bildschirmfoto 2024-01-25 um 21 05 32" src="https://github.com/sehmaschine/django-grappelli/assets/206830/3a12eb85-32ee-4a00-9e96-bd252bede38e">

**Comment by sehmaschine** [comment]
@parsch thanks for checking this! I guess I've lost track about what has changed after the last release.
