### ISSUE TITLE
CollectStatic when using Django Storages and a private bucket

### ISSUE THREAD

**Issue by seashootz** [sehmaschine/django-grappelli#1052]
Hello,

We have a private S3 bucket that we use with `django-storages`. Uploading Grappelli assets is fine with the `collectstatic` command, but reading requires query params containing a short-lived access key to get all assets. For instance, `https://YOUR_S3_BUCKET.s3.amazonaws.com/grappelli/images/backgrounds/changelist-results.png`, which is referenced by Grappelli, should be `https://YOUR_S3_BUCKET.s3.amazonaws.com/grappelli/images/backgrounds/changelist-results.png?X-AMZ-Secret...` which contains query params with the token. Django Storages does this for you automatically if you use something like a `FileField`, and AFAICT the only things that don't are the assets in Grappelli.

Thanks for reading this, I enjoy using the library!

**Comment by sehmaschine** [comment]
@shicholas Sorry, but I don't fully understand why this is an issue with Grappelli. What exactly should we do to solve this? To me, this looks more like an issue with `django-storages` ...
