### ISSUE TITLE
Compatibility with Django 4.2 LTS

### ISSUE THREAD

**Issue by myii** [sehmaschine/django-grappelli#1053]
With Django 3.2 LTS reaching the end of extended support within the next month, we need to upgrade to Django 4.2 LTS soon but are unsure if Grappelli is compatible at the current time.  The `README` suggests that the only versions supported currently are 3.2 LTS and 4.0:

https://github.com/sehmaschine/django-grappelli/blob/d7ce15aaed882ed7cf8814a938db2f710dea5d61/README.rst#L39-L40

Is there a version of Grappelli that is compatible with 4.2 LTS?  If not, are there any steps that the community can help with in order to get this up and running?

**Comment by sehmaschine** [comment]
That's a minor glitch with the README file ... it should be 4.x instead of 4.0. We're using grappelli 3.0.8 with Django 4.2 LTS for a while now and it should work fine. I'll update the docs.

**Comment by myii** [comment]
> We're using grappelli 3.0.8 with Django 4.2 LTS for a while now and it should work fine.

That's good to hear, thanks for the prompt response.

I won't close this issue, since I see you've self-assigned it.
