### ISSUE TITLE
Filter drop-down doesn't function due to Javascript error in Chrome, FF

### ISSUE THREAD

**Issue by ndrsn** [sehmaschine/django-grappelli#12]
I just installed django-grappelli 2.3.4 in combination with Django 1.4.0 alpha. All's fine, except for the filter drop-down box on the change list page. Chrome and Firefox report a Javascript error:

```
Uncaught TypeError: Object #<Object> has no method 'actions'
(anonymous function):8000/admin/msdb/incident/:59
c.extend.readyjquery-1.4.2.min.js:26
L
```

The relevant bit of code is in templates/admin/change_list.html. A fix seems to be moving the block

```
{% if action_form %}
  ...
{% endif %}
```

from line 19 down to line 65, right after `{{ media.js }}`. I believe this is because the `actions.js` script is loaded in the block contained by `media.js`, which comes _after_ relevant Javascript code.

Not sure if this is a result of Django code still being in alpha, but figured I'd report it.

Another error occurrs at the same time by `grp_collapsible` in `templates/admin/includes_grappelli/header.html`:

```
Uncaught TypeError: Object #<Object> has no method 'grp_collapsible'
```

Don't know how to fix this one, though.

**Comment by samupl** [comment]
Django==1.8.2
django-grappelli==2.7.1

Problem still persists, collectstatic doesn't find grappellis admin/ static folder for some reason.

**Comment by gbcgit** [comment]
Django==1.8.3
django-grappelli==2.7.3

problem still here for me

~django.contrib.admin.options.ModelAdmin#media:635
        if self.actions is not None:
            js.append('actions%s.js' % extra)

If you do something in a ModelAdmin subclass that prevents this method (property) from getting called, like redefine the media property without calling this super one, then you don't get actions loaded.  And you also don't get the extend feature of Form.media.   So, even if you try to put actions in your class Media in the subclass it doesn't get found.

So, put a check point in that method and make sure it's getting called.

**Comment by gameot** [comment]
I had the same problem and I solved it by editing nginx config. 
Before:
`location /static/admin/ { alias /web/merv/env/lib/python3.4/site-packages/django/contrib/admin/static/admin/; }`
`location /static/ {
        alias   /web/merv/files/static/;
    }`
After:
`location /static/ {
        alias   /web/merv/files/static/;
    }`

**Comment by gasinvein** [comment]
For me problem is still present.
python 2.7, django 1.9.6, grappelli 2.8.1

**Comment by MohsenHassani** [comment]
The solution by @gameot worked for me!
I just needed to comment the /static/admin/ block in the nginx config file of the website; like this:
#       location /static/admin/ {
#          gzip on;
#          alias /home/mohsen/virtualenvs/django-1.9/lib/python3.4/site-packages/django/contrib/admin/static/admin/;
#       }

I could delete it of course! It just seems to be useless while using grappelli.

Thanks @gameot for sharing your solution. ;-)
