### ISSUE TITLE
autocomplete feature cannot get app label and model name

### ISSUE THREAD

**Issue by benjiec** [sehmaschine/django-grappelli#185]
I've got autocomplete setup according to documentation.

When I try to check it on on admin page, the autocomplete JS did not get the right app label and model name. It got "false", which from the JS code means it didn't find a "a" tag with the URL.  I inspected the DOM and didn't find such a "a" tag.

Where is this "a" tag?

**Comment by leszarna** [comment]
There should be some check and error or waring so that developers do not loose time investigating.
