### ISSUE TITLE
Django 1.4 like help_text display in tabular inline

### ISSUE THREAD

**Issue by deschler** [sehmaschine/django-grappelli#216]
Django 1.4 introduced a new help_text icon in the table head (actually it's a div) of a tabular inline. The help_text is only displayed when the icon is hovered. I think it would be great if grappelli used the same pattern.

In grappelli the help_text is displayed below each inline instance. This is still better than no help_text at all like in pre 1.4 Django versions, but it can result in very long columns if the help_text itself is long, especially with small columns. It's also somewhat redundant to the see the text again for each line.

**Comment by rcooke** [comment]
## description

A string of optional extra text to be displayed at the top of each fieldset, 
under the heading of the fieldset. _This string is not rendered for TabularInline_ 
_due to its layout._

[ModelAdmin.fieldsets](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets)


According to the Django docs, this will not work with Tabular inlines.  I don't understand your aversion to Django's solution.

But you could make an option flag to enable it for tabular inlines, so its not a magical new behavior.  Or define a new option - like hover-over for the column title cell and/or any cell in that column. Or define a number of options so the user can pick which one they want to best suit their circumstances.

**Comment by rcooke** [comment]
Heh.  One quick fix is to hide the help text with some JS in JQuery:

```
django.jQuery(document).ready(function($){
  $(".inline-group .grp-help").hide()
});

```
I'm trying to learn enough JS/JQuery to copy or move the HELP TEXT someplace else.  Either as the "title" text for the input field, or the column title.

**Comment by rcooke** [comment]
Heh.  Ok.  So I figured out the Jquery to copy the help text message onto the cell container's "title" attribute.  So hovering the mouse over the cell pops it up.  I might try and figure out how to target the input cell itself, if users complain the pop ups are too distracting this way.

```
django.jQuery(document).ready(function($){
  $(".inline-group .grp-help").hide()
  $('.inline-group .grp-help').each(function() {
    this.parentNode.title = this.innerHTML;
  });
});

```
