### ISSUE TITLE
Autocomplete is creating bogus URLs

### ISSUE THREAD

**Issue by funkybob** [sehmaschine/django-grappelli#303]
[Django 1.4.5]
I have an autocomplete in a TabularInline [which is working in many other places in my project] which for some reason is producing urls as:

```
[13/Mar/2013 11:08:09] "GET /grappelli/lookup/related/?object_id=121&app_label=false&model_name=false HTTP/1.1" 500 22038
```

An autocomplete on the main form is working fine.

It was having a rendering issue, but I upgraded from 2.4.3 to 2.4.4 and that went away.  However, lookup issue remains.

The model is a 'through' on a m2m.

```
class DiscountRuleInline(admin.TabularInline):
    model = models.DiscountRule
    raw_id_fields = ('condition',)
    autocomplete_lookup_fields = {
        'fk': ('condition',),
    }
```

**Comment by DeathBorn** [comment]
Yep. you need to register that model on which you autocomplete. Only then autocompelte will work. It is a shame.
