### ISSUE TITLE
DashboardModule.content?

### ISSUE THREAD

**Issue by BertrandBordage** [sehmaschine/django-grappelli#306]
The DashboardModule docstring refers to a ``content`` attribute.  I guess we have to remove this.  Or, since it is not consistent with ``pre_content`` and ``post_content``, maybe we should reimplement this.

**Comment by int-ua** [comment]
It wasn't removed in docs:
https://github.com/sehmaschine/django-grappelli/blob/master/docs/dashboard_api.rst#the-dashboardmodule-class

**Comment by int-ua** [comment]
AFAIU, it should be replaced with `children` in the documentation.
