### ISSUE TITLE
Rearrange inlines

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#355]
sometimes it might make sense to not show inlines at the bottom of the page/form, but somewhere in–between.

this could be solved with adding some js to change_form.html:

```
$('div.grp-group').each(function() {
    var placeholder = $("fieldset.placeholder."+$(this).attr("id"));
    $(placeholder).replaceWith($(this));
});
```

with admin.py, one needs to define the placeholder with the group–class:

```
("Some Fieldset", {
    "classes": ("grp-collapse grp-open",),
    "fields": ("whatever",)
}),
("New Inline position", {"classes": ("placeholder images-group",), "fields" : ()}),
("Another Fieldset", {
    "classes": ("grp-collapse grp-open",),
    "fields": ("whatever",)
}),

inlines = [ImageInlines]
```

any objections?

**Comment by ppawlak** [comment]
Hi, I am trying to get this working. [From the docs](http://django-grappelli.readthedocs.io/en/latest/customization.html#rearrange-inlines) it seems to be implemented ?

Maybe I am not doing it right. Where the doc says 

> The two classes for the placeholder are important. First, you need a class placeholder. The second class has to match the id of the inline–group.

is not very clear. Can you provide a full working example ?

Thanks a lot!

**Comment by sehmaschine** [comment]
There is an example with the docs. You need a class `placeholder` and a 2nd class which matches the class of the inline-group (which depends on your fieldsets). If you have an inline `images` the class would probably be `images-group`.

Besides, please use the google-group for asking questions (it´s more likely to get an answer there).

**Comment by sehmaschine** [comment]
Closing this for now since the ticket is very old. If there's still something which needs to be fixed with regards to this issue, please open a new ticket.
