### ISSUE TITLE
support ModelAdmin.get_queryset

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#403]
```
def get_queryset(self):
    qs = self.model._default_manager.get_queryset()
    # try to find model admin queryset
    model_admin = self.GET.get("model_admin", None)
    if model_admin:
        module, classname = model_admin.split(",")
        ma = import_from(module, classname)
        # FIXME: we are not using the admin_site here, do we need it?
        qs = ma(self.model, None).get_queryset(self.request)
    qs = self.get_filtered_queryset(qs)
    return qs
```

then, we just need to add model_admin=module,classname to the ajax–call.

**Comment by apoku** [comment]
Any chance this is still being worked? Our team switched over to django-grappelli for the effortless autocomplete feature on foreign key and many to many fields; however, we do have use cases where we've got to prevent some values from being displayed in the UI based on factors such as if the entry "is approved" or the logged in user "is authorized" etc. We were hoping to just override the get_queryset() method that is part of Django 1.11, but it doesn't seem to be supported with django-grappelli. Any pointers or other workarounds?

**Comment by sehmaschine** [comment]
see https://gist.github.com/sehmaschine/41747752e56e2723368a409feb3cbd5c

the changes are in lines 21, 76-81 and 96-98.

It´s actually a pretty easy workaround, but (in my opinion) it does not work with multiple/custom admin sites since we only check the contrib.admin registry. I'm not sure how we could solve this and I'm currently unable to add a testcase. As said before, if someone comes up with a working and tested solution, I'm more than happy to merge it.

**Comment by sehmaschine** [comment]
Closing this since the issue is extremely outdated. If there is still something unresolved related to this topic, please open a new ticket.
