### ISSUE TITLE
'Import' 'Export' 'Add <Model>' buttons not being styled

### ISSUE THREAD

**Issue by ghost** [sehmaschine/django-grappelli#435]
Hi,

I am using django-import-export feature with django admin:

```
   class ProductAdmin(admin.ImportExportModelAdmin):
         .....
```

This puts 'Import' and 'Export' buttons alongside 'Add Model' button at the top of the change list view. 

But when I use grappelli these buttons dont get styled in the jazzy grappelli way, rather they are just text links. 

https://www.dropbox.com/s/fs52h072wfzjuaw/Screenshot%202014-01-12%2021.58.16.png

Any help/advice much appreciated. 

Thanks

HT

**Comment by AlexLoar** [comment]
@slawekl  I managed to gather both apps but I still have a problem in how are showed the buttons Import, Export and Add because are hidden (are located between the word admin and Filter): dl.dropboxusercontent.com/u/23171086/image.png

**Comment by techietek** [comment]
I just hacked something up as I had the same issue, i haven't had time to do the import template so if someone gets a chance let me know :), you can just add those files to your template dir:

templates/admin/import_export/
https://gist.github.com/techietek/ffc53269c57549ebcb05

which should give you something like below:
![screen shot 2015-08-18 at 12 32 21 pm](https://cloud.githubusercontent.com/assets/8494130/9328966/499a903c-45a5-11e5-89f3-22387b13322f.JPG)

![screen shot 2015-08-18 at 12 32 39 pm](https://cloud.githubusercontent.com/assets/8494130/9328965/4996d8e8-45a5-11e5-8d2a-c4a627b916eb.JPG)

**Comment by vincentleeuwen** [comment]
@techietek Works like a charm! Thanks for sharing!

**Comment by benxy** [comment]
Also, note that in Django 1.9 url tag is loaded by default so it has to be removed from base.html and export.html.

http://stackoverflow.com/questions/5653497/django-load-url-from-future-yields-error-url-is-not-a-valid-tag-libra
