### ISSUE TITLE
Compatibility: provide Django's CSS class/id names, e.g. `.form-row` and `#container` (additionally)

### ISSUE THREAD

**Issue by blueyed** [sehmaschine/django-grappelli#494]
Grappelli uses e.g. `.grp-row` instead of `.form-row` with change forms.

This causes problems with re-usable Django apps like [Django-parsley](https://github.com/agiliq/Django-parsley), whose Javascript expects and uses `.form-row`.

Wouldn't it be possible to use `.form-row` additionally to `.grp-row`?

Another example is [django-admin-enhancer](https://github.com/charettes/django-admin-enhancer), which expects `#container`, where Grappelli uses `#grp-container`.

I can imagine that there are problems when applying the class/id names as-is, but with additional CSS to reset them this should work.

**Comment by blueyed** [comment]
I think providing this for some essential wrappers like `#container` and `.form-row` would be a good start.  Other classes could be added if needed and it makes sense.
It might also make diffing to and merging from Django a bit easier after all.

**Comment by parsch** [comment]
@blueyed Okay, let's add ```#container``` and ```.form-row```. Can you provide a patch for that?

**Comment by parsch** [comment]
added following id/classes: `#container` `.inline-group` `.inline-related` `.tabular` `.module` `.form-row` `.field-box`

**Comment by blueyed** [comment]
@parsch 
Thanks! :)
