### ISSUE TITLE
FieldError at /grappelli/lookup/autocomplete

### ISSUE THREAD

**Issue by zacniewski** [sehmaschine/django-grappelli#510]
My first model is:

class City(models.Model):
    name = models.CharField(u'Nazwa miasta', max_length=255)
    slugified_name = models.SlugField()

```
@staticmethod
def autocomplete_search_fields():
    return ("name__icontains",)
```

...

And I have second model, where city is a FK to first model:
class Stadium(models.Model):

```
city = models.ForeignKey(City,
                         related_name="city_to_stadium",
                         verbose_name=u"Miasto")
```
# admin.py

class StadiumModelAdmin(admin.ModelAdmin):
    list_display = ['name', 'city', 'street_name', 'number_of_seats', 'is_main']
    raw_id_fields = ('city',)
    autocomplete_lookup_fields = {'fk': ['city'], }

When I'm typing any letter in the input (in admin panel) nothing changes and I get an error in console:
http://127.0.0.1:8000/grappelli/lookup/autocomplete/?term=G&app_label=stadiums&model_name=city&query_string=_to_field=id
FieldError at /grappelli/lookup/autocomplete/Cannot resolve keyword u'_to_field' into field. Choices are: city_to_stadium, id, name, slugified_name
What can be wrong?

**Comment by phretor** [comment]
@sehmaschine I'm still seeing this issue on 2.5.7 + Django 1.7. Here is more details:

    # models.py
    class Conference(models.Model):
            class Meta:
                app_label = 'foolab'
                ordering = [
                    'acronym',
                    'name', ]

            name = models.CharField(
                _('Name'),
                help_text=_('E.g., Recent Advances in Intrusion Detection'),
                max_length=256,
                unique=True,
                db_index=True)
            acronym = models.CharField(
                max_length=16,
                unique=True,
                help_text=_('E.g., RAID, IMC, EC2ND, CCS, SSP'),
                validators=[RegexValidator(regex=r'^([0-9A-Za-z]+[ ]?)+$')])

            def __unicode__(self):
                return self.acronymized

            def _get_acronymized(self):
                return u'%s (%s)' % (
                    self.name,
                    self.acronym)
            acronymized = property(_get_acronymized)

            @staticmethod
            def autocomplete_search_fields():
                return ("id__iexact", "name__icontains", "acronym__icontains")


    # admin.py
    @admin.register(ConferenceEdition)
        class ConferenceEditionAdmin(admin.ModelAdmin):
            list_display_links = (
                'conference',)
            list_display = (
                'conference',
                'year',
                'address',
                'web_page')
            raw_id_fields = (
                'conference',)
            autocomplete_lookup_fields = {
                'fk': ['conference',]
            }

        @admin.register(Conference)
        class ConferenceAdmin(admin.ModelAdmin):
            list_display = (
                'acronym',
                'name')
            list_display_links = (
                'acronym',
                'name',)

    # traceback
    Environment:


        Request Method: GET
        Request URL: http://localhost:9000/grappelli/lookup/autocomplete/?term=raid&app_label=foolab&model_name=conference&query_string=_to_field=id

        Django Version: 1.7
        Python Version: 2.7.9
        Installed Applications:
        ('grappelli.dashboard',
         'grappelli',
         'filebrowser',
         'ckeditor',
         'django.contrib.admin',
         'django.contrib.auth',
         'django.contrib.contenttypes',
         'django.contrib.messages',
         'django.contrib.sessions',
         'django.contrib.staticfiles',
         'django.contrib.webdesign',
         'django.contrib.sites',
         'djangobower',
         'pipeline',
         'django_extensions',
         'debug_toolbar',
         'treemenus',
         'gunicorn',
         'foolab')
        Installed Middleware:
        ('django.middleware.common.CommonMiddleware',
         'django.contrib.sessions.middleware.SessionMiddleware',
         'django.middleware.csrf.CsrfViewMiddleware',
         'django.contrib.auth.middleware.AuthenticationMiddleware',
         'django.middleware.locale.LocaleMiddleware',
         'django.contrib.messages.middleware.MessageMiddleware',
         'django.middleware.clickjacking.XFrameOptionsMiddleware',
         'django.middleware.gzip.GZipMiddleware',
         'debug_toolbar.middleware.DebugToolbarMiddleware',
         'pipeline.middleware.MinifyHTMLMiddleware')


        Traceback:
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
          111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/views/generic/base.py" in view
          69.             return self.dispatch(request, *args, **kwargs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
          87.         return handler(request, *args, **kwargs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
          52.         response = view_func(request, *args, **kwargs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/grappelli/views/related.py" in get
          169.             data = self.get_data()
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/grappelli/views/related.py" in get_data
          160.         return [{"value": f.pk, "label": get_label(f)} for f in self.get_queryset()[:AUTOCOMPLETE_LIMIT]]
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/grappelli/views/related.py" in get_queryset
          154.         qs = super(AutocompleteLookup, self).get_queryset()
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/grappelli/views/related.py" in get_queryset
          74.         qs = self.get_filtered_queryset(qs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/grappelli/views/related.py" in get_filtered_queryset
          70.         return qs.filter(**filters)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/query.py" in filter
          691.         return self._filter_or_exclude(False, *args, **kwargs)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/query.py" in _filter_or_exclude
          709.             clone.query.add_q(Q(*args, **kwargs))
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in add_q
          1287.         clause, require_inner = self._add_q(where_part, self.used_aliases)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in _add_q
          1314.                     current_negated=current_negated, connector=connector)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in build_filter
          1138.         lookups, parts, reffed_aggregate = self.solve_lookup_type(arg)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in solve_lookup_type
          1076.         _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in names_to_path
          1383.             self.raise_field_error(opts, name)
        File "/Users/phretor/ve/foolab/lib/python2.7/site-packages/django/db/models/sql/query.py" in raise_field_error
          1389.                          "Choices are: %s" % (name, ", ".join(available)))

        Exception Type: FieldError at /grappelli/lookup/autocomplete/
        Exception Value: Cannot resolve keyword u'_to_field' into field. Choices are: acronym, conferenceedition, id, name

**Comment by int-ua** [comment]
I'm not sure that removing *.pyc was what helped me, but you can try that next time.

**Comment by int-ua** [comment]
Upgrading Grappelli from 2.5.7 to 2.6.5 should fix the issue.
