### ISSUE TITLE
grp-doc urls enabled on branch 2.5.x

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#530]
Hi all,

Why on brach 2.5.x all url(r'^grp-doc/...') are not commented and on brach 2.6.x it is?
I think that nobody want this urls in your production environment.

https://github.com/sehmaschine/django-grappelli/blob/dev/2.6.x/grappelli/urls.py

https://github.com/sehmaschine/django-grappelli/blob/dev/2.5.x/grappelli/urls.py

**Comment by mgedmin** [comment]
Any reason these are completely commented out instead of being protected with `if settings.DEBUG:` or something like that?

**Comment by sehmaschine** [comment]
No
