### ISSUE TITLE
Delete table icon is missing for TinyMCE skin

### ISSUE THREAD

**Issue by benebun** [sehmaschine/django-grappelli#534]
There is no icon for deleting a table (mce_delete_table).

Not sure why nobody has mentioned that so far, apart from deleting the table in the html code view there doesn't seem to be another way to delete the table?

Might be irrelevant with 3.0 and the change to the TinyMCE 4 skin?

**Comment by sehmaschine** [comment]
Closing this for now. Please note that we'll remove TinyMCE with the next major release.
