### ISSUE TITLE
Option to submit model actions with an explicit button click

### ISSUE THREAD

**Issue by GriceTurrble** [sehmaschine/django-grappelli#546]
I'm attempting to integrate django-import-export, specifically their 'ImportExportActionModelAdmin' class. This creates a second dropdown list of actions within the model admin: one to choose an action to take, another to choose the file type for the exporter.

I would like a simple option to turn off the js that causes an action menu selection to submit the form after a single click, and instead give me a button selection to submit the form manually.

I'm looking through the docs and can't seem to find anything mentioning this as an option. Have I missed it, or is it overlooked somehow?

**Comment by timkofu** [comment]
+1
I have *this exact problem* further more, It makes it impossible to have admin actions that need options selected via ActionForm, as it immediately runs the action without letting one select an option.

**Comment by noam-fairfly** [comment]
+1
Exact same for me.

**Comment by sehmaschine** [comment]
@parsch what do you think?

**Comment by parsch** [comment]
Let's implement a submit button

**Comment by noam-fairfly** [comment]
Thanks guys!!! :crown:
