### ISSUE TITLE
Prepopulated fields for inline forms

### ISSUE THREAD

**Issue by eandersons** [sehmaschine/django-grappelli#550]
VERSIONS: Grappelli 2.6.3, Django 1.7.1
    STATICFILES: OK
    JAVASCRIPTS: OK
    CUSTOMIZATIONS: NO

Hello!

First of all, thanks for this great app/skin for the Django admin!

Now lets move on to the issue. I saw something similar mentioned here:  [#484] (https://github.com/sehmaschine/django-grappelli/issues/484).
So the problem is that script for inline prepopulated fields is not working, it does not matter if, `extra` is defined or not in inline admin class.
In my case value for slug field, which I am defined as prepopulated field, is not generated for all inline rows, that are added with link "Add another" or button "+".
I checked this issue with fresh Django/Grappelli setup in Safari, Waterfox (same as Firefox), Chrome and Opera.

Thanks in advance!

**Comment by sehmaschine** [comment]
@eandersons thanks for looking into that – I think I've found a solution.
