### ISSUE TITLE
Filter background position.

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#559]
![filter](https://cloud.githubusercontent.com/assets/5805339/5516338/bfcda152-887e-11e4-83f5-e091f0ac5d1c.png)

Hi,

When I hover mouse on a filter, this background appears (see image). Anyone else?

I'm using last git 2.6.X version.

Thanks. 

on hover:
.grp-pulldown-container .grp-pulldown-handler {
    background-position: 100% -863px;
    ...

on click:
.grp-pulldown-container.grp-pulldown-state-open .grp-pulldown-handler {
    background-position: 100% -907px;

**Comment by int-ua** [comment]
It was a bit unclear for me: the fix was included in 2.5.7.
