### ISSUE TITLE
[Django 1.7] Grappelli installed without errors, but not changing admin site

### ISSUE THREAD

**Issue by Hiieu** [sehmaschine/django-grappelli#561]
https://gist.github.com/Hiieu/8a11236adea3d1a52bd2

I did everything step by step from the documentation. 
No erros, but when I run server and try to access admin panel, nothing has changed. I still have default admin page.

In the static I have following folders

/static_root/
/static_root/admin/
/static_root/grappelli/

When I type manage.py collectstatic it takes everything from

>C:\Python27\lib\site-packages\django\contrib\admin\static\admin\

to my static_root folder.

**Comment by sehmaschine** [comment]
grappelli has to be before django.contrib.admin with INSTALLED_APPS. besides, please use the google-group for asking questions (this is an issue tracker).

**Comment by Hiieu** [comment]
God Damn it, I only put grappelli before admin in urls.py
