### ISSUE TITLE
Checkbox with float valued tuple doesnot gets checked

### ISSUE THREAD

**Issue by ajayrokr27** [sehmaschine/django-grappelli#563]
Hi,
I came across this issue today while using my admin .
I have a tuple of version of my android application like (('3.1','3.1'), ('3.2','3.2'), ('3.3','3.3'),) and so on.
When clicked on save button the values is saved in the model object but the checkboxes are not checked.
I can get all checked values using django shell.
Also (('1','1'), ('2','2'), ('3','3'),) this gets checked and works fine
any help?

**Comment by sehmaschine** [comment]
how should we be able to reproduce this? grappelli version? django version? model? model-admin? any js errors?

please re-open with all necessary details.
