### ISSUE TITLE
Admin Docs View Show Nothing

### ISSUE THREAD

**Issue by edwinlunando** [sehmaschine/django-grappelli#566]
I want to make my documentation with admin docs, but the admin doc for views with grappelli is broken. It did not shown anything. Here is the screenshot.

![selection_055](https://cloud.githubusercontent.com/assets/1451080/5997429/9f71528c-aaed-11e4-84a0-c909b35a0e56.png)

If I turn off grappelli, it show the views normally.

![selection_056](https://cloud.githubusercontent.com/assets/1451080/5997443/d6098954-aaed-11e4-9682-fb841e6d0de0.png)

My setup is.

Django==1.7.3
django-grappelli==2.6.3
STATICFILES=OK / NO ERROR
JAVASCRIPT=OK / NO ERROR
CUSTOMIZATION=NONE

**Comment by sehmaschine** [comment]
just tested – works fine with my setup. you need to add django.contrib.admindocs to your INSTALLED_APPS after grappelli.

If you think this is a bug, please try to debug and open this issue adding some details.

**Comment by edwinlunando** [comment]
I think the problem is because the grappelli regroup the views based on site. 

    {% regroup views|dictsort:"site_id" by site as views_by_site %}

While the standard Django admin regroup by namespace.

    {% regroup views|dictsort:'namespace' by namespace as views_by_ns %}

From this commit, I think grappelli needs to follow this Django pull request. https://github.com/django/django/commit/a39d672ec7d53637805a61b45a51bc0e7d297a36

**Comment by sehmaschine** [comment]
thanks for looking into this. it's strange though that the docs work with my setup.

**Comment by edwinlunando** [comment]
I've created a simple pull request for this. :). https://github.com/sehmaschine/django-grappelli/pull/567

**Comment by sehmaschine** [comment]
@edwinlunando great. thank you!
