### ISSUE TITLE
Filter hover effect broken (Firefox Nightly)

### ISSUE THREAD

**Issue by wldcordeiro** [sehmaschine/django-grappelli#569]
When I hover over the filter it renders like this.
![screenshot from 2015-02-02 14 43 39](https://cloud.githubusercontent.com/assets/580982/6010282/5092d28e-aaee-11e4-9fdc-f22294a47f17.png)

**Comment by sehmaschine** [comment]
see https://github.com/sehmaschine/django-grappelli/issues/559
