### ISSUE TITLE
"Add" button in objects list (change_list.html) looks lighter and without plus icon.

### ISSUE THREAD

**Issue by raagin** [sehmaschine/django-grappelli#570]
I think, it is because class "grp-add-link" is missing on the add button.

![image](https://cloud.githubusercontent.com/assets/5389817/6056009/5899286e-ad1b-11e4-9fc6-4b7aae4af9b8.png)

Django==1.7.4
django-grappelli==2.6.4

**Comment by parsch** [comment]
thanks for reporting
