### ISSUE TITLE
with custom usermodel, username not displayed when logged in

### ISSUE THREAD

**Issue by lvr-dev** [sehmaschine/django-grappelli#571]
I use a custom usermodel with emailaddress as username. I also have a field added to my usermodel called 'userrole'. 
This is an excerpt from my customer usermodel:
    email = models.EmailField()
    userrole = models.CharField(max_length=20, choices=ROLE_CHOICES, default=GUEST)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["userrole",]

After installing Grappelli, I no longer see my emailaddress as the loggedin user, I just see '3', which seems to be my userrole-id. The old admin-interface does show my emailaddress as my username. I tried to find out in the docs if there's a setting of some sort for custom usermodels, but apparently there isn't??

**Comment by sehmaschine** [comment]
which grappelli version, which django version?

**Comment by lvr-dev** [comment]
django version 1.7 grappelli version 2.6.3

**Comment by sehmaschine** [comment]
base.htm, line 86:
{% firstof user.get_short_name user.get_username %}

so you say that isn't working for your case? any chance to debug this issue?

**Comment by lvr-dev** [comment]
Figured it out: get_short_name pointed to userrole. So that explains everything. Thanks for the hint.
