### ISSUE TITLE
Models without an explicit verbose_name_plural are not sorted correctly

### ISSUE THREAD

**Issue by stratoukos** [sehmaschine/django-grappelli#572]
The models in AppList and ModelList are ordered in [filter_models](https://github.com/sehmaschine/django-grappelli/blob/79f6005b0fef6ee8c665e78a10c80f20c510cd1b/grappelli/dashboard/utils.py#L112) using this key function: `lambda x: x[0]._meta.verbose_name_plural`.

verbose_name_plural for models that don't define it explicitly is `<django.utils.functional.__proxy__ object at 0x000000000>` so models end up being sorted incorrectly.

**Comment by sehmaschine** [comment]
can't reproduce ... models are being sorted fine even without verbose_name/verbose_name_plural with my test case. more details?

**Comment by sehmaschine** [comment]
ok ... finally got it.
