### ISSUE TITLE
Inlines with Autocomplete fields performance

### ISSUE THREAD

**Issue by GriceTurrble** [sehmaschine/django-grappelli#574]
I'm working with models that may contain several hundred child objects, shown in the admin using inlines. Each child also contains a foreign key to another object, which I'm handling at the moment using autocomplete fields (set up in the fashion described by the docs).

Problem is, the site is having performance issues when these several hundred inlines and several hundred autocompletes are being displayed on a single page (page hangs for a long time before finally showing everything, making any change takes about a decade, etc). I'm wondering if there's some simpler way to provide the same functionality without taking such a hit to page performance.

Any advice would be helpful. Thank you.

**Comment by sehmaschine** [comment]
I currently don't see any performance improvements ... the main issue is that we need to do a request for each and every autocomplete (because the functionality is not built-in with django and the necessary items are not available with an ordinary change form).

**Comment by GriceTurrble** [comment]
Is pagination a possibility? I haven't looked into it in detail yet, I'm afraid. I'd gladly cut the inline count down to 50 or so and provide pagination for the results.

**Comment by sehmaschine** [comment]
I don't think pagination is possible (though that is a django issue).

**Comment by sehmaschine** [comment]
IMO django should give us the object representation, but it currently doesn't. If we have the title (for example), we don't need to use an ajax-call when loading the page. I don't see a workaround unless django adds the necessary elements ... but they probably won't.
