### ISSUE TITLE
Not implementing TEMPLATE_STRING_IF_INVALID

### ISSUE THREAD

**Issue by alosultan** [sehmaschine/django-grappelli#575]
**settings.py**

    TEMPLATE_STRING_IF_INVALID = 'INVALID EXPRESSION: %s'

**accounts.admin.py**

    class UserProfileInline(admin.StackedInline):
        model = UserProfile
        can_delete = False
        verbose_name_plural = _('user profile')

    class MyUserAdmin(UserAdmin):
        inlines = (UserProfileInline, )
        form = UserChangeForm
        add_form = UserCreationForm
    
        def get_inline_instances(self, request, obj=None):
           if obj is None:
              return []
           return super(MyUserAdmin, self).get_inline_instances(request, obj)

    admin.site.unregister(User)
    admin.site.register(User, MyUserAdmin)

**Error Type:** *KeyError*.

**Error Message:** *"Key 'INVALID EXPRESSION: inline_admin_formset.opts.sortable_field_name' not found in 'UserProfileForm'"*

**template path:** ....../lib/python3.4/site-packages/grapple/templates/admin/edit_inline/stacked.html, error at line 17

**Error Line:** {% for inline_admin_form in inline_admin_formset|formsetsort:sortable_field_name %}

**Comment by sehmaschine** [comment]
this should already be solved ... which version of grappelli are you using?

**Comment by alosultan** [comment]
Version: 2.6.3

**Comment by sehmaschine** [comment]
According to the django docs, you should not assume the admin templates to be rendered correctly, if TEMPLATE_STRING_IF_INVALID is set to anything other than an empty string.

Therefore, what exactly is the issue here?

**Comment by alosultan** [comment]
But this issue does not occur when i work with default admin templates.

**Comment by sehmaschine** [comment]
that may be true, but it's a django design decision that admin doesn't have to work if that string is not empty. however, if you're able to submit a patch I'll give it a review (please reopen this issue if you wanna take on that work).
