### ISSUE TITLE
"white-space: normal" set on textarea, so newlines don't wrap

### ISSUE THREAD

**Issue by hobbsd** [sehmaschine/django-grappelli#582]
I'm using 2.6.4.

**Comment by parsch** [comment]
Sorry, can't reproduce this. Dou you have a screenshot and more information (browser etc.)?

**Comment by hobbsd** [comment]
My browser is Firefox 37.
Here is the textarea as-is:
![screen-2015-03-31_12-12](https://cloud.githubusercontent.com/assets/1676348/6923589/936551c0-d7a0-11e4-9902-cd816be04f2e.png)
And here it is with css adjusted as shown in the screenshot just below:
![screen-2015-03-31_12-13](https://cloud.githubusercontent.com/assets/1676348/6923593/9a982472-d7a0-11e4-97e5-97e882bd6900.png)
![screen-2015-03-31_12-14](https://cloud.githubusercontent.com/assets/1676348/6923595/9d7128d8-d7a0-11e4-846c-087c0405a364.png)
Thanks for looking into it, and let me know if there's any other info you need.

**Comment by parsch** [comment]
Thanks for additional info, fixed it assigning ```white-space: pre-wrap```
