### ISSUE TITLE
Autocomplete using `startswith` partially fails

### ISSUE THREAD

**Issue by BertrandBordage** [sehmaschine/django-grappelli#585]
When specifying a model like this:

``` python
class AnyModel(Model):
    name = CharField(max_length=50)

    @staticmethod
    def autocomplete_search_fields():
        return ('name__istartswith',)
```

If another model has an autocomplete lookup to this model, typing "what th" doesn’t show entries where name is "what the hell". This is because the query is split and therefore looks like:

``` python
AnyModel.objects.filter(Q(name__istartswith='what') & Q(name__istartswith='th'))
```

Of course it returns nothing.

Should `startswith` and `istartswith` be handled in a special way?

**Comment by sehmaschine** [comment]
Good point. I'm actually not quite sure how to solve this. I just tried with not splitting the term (line 139 in related.py) and it works as expected.
I don't remember why we decided to split the term. It doesn't seem to make much sense (but I might be missing something).

**Comment by BertrandBordage** [comment]
There’s a good reason for splitting the term.
Suppose you want an autocomplete on a Person model with two CharFields for first name and last name. You want to be able to search “Beethoven” or “Beethoven Ludwig”, as well as the full “Ludwig van Beethoven”. If we don’t split the term, either while using __istartswith or __icontains, nothing is returned.

I don’t see a good solution without using a search engine or using multiple queries.
The best solution IMHO may be to avoid splitting the term if there is only one __[i]startswith field in autocomplete_search_fields + give users a way to write their own query. In my case that would be relying on a search engine.

**Comment by sehmaschine** [comment]
Closing this since we plan to remove Grappelli autocompletes in favour of the now available Django autocompletes.
