### ISSUE TITLE
django admin inline autocomplete filter support

### ISSUE THREAD

**Issue by kokhoor** [sehmaschine/django-grappelli#587]
Is it possible for us to filter the autocomplete results in django grappelli inline autocomplete fields to specific items only?

For example, I have a Product model foreign key and I want to add filter:

    .filter(sell_ind=True)

I tried using formfield_for_foreignkey in the admin.TabularInline but doesn't seem to reflect in the autocomplete fields.

**Comment by sehmaschine** [comment]
Unfortunately, that's currently not possible. But it would make a fine improvement. Any idea on a good implementation?

**Comment by kokhoor** [comment]
Hopefully we can mess around with some settings in Model Admin to generate the <a href> link which will be intepreted by the auto-complete when user key in searches as well as the <a href> itself when opening the new dialog.

Besides just filtering, it is then possible to maybe (thinking crazily) populate other fields too. This will be useful for invoices for example, where in the line items it is possible to just select an item, and the default selling price and unit of measure are pre-populated.

Is it at all a good place to start such a customisation? I may be able to chip in some effort if it is considered useful for the project.

**Comment by sehmaschine** [comment]
The search-link is generated with Django (not Grappelli) by using raw-id fields. That's the link we use for autocompletes as well.

That being said, issue #403 is somehow similar in terms of retrieving ModelAdmin with the frontend. Generally speaking, I think ModelAdmin is the class to look at – we should try to define the lookup queryset with ModelAdmin instead of relying on ``autocomplete_search_fields`` (or maybe combine both setups).

**Comment by kokhoor** [comment]
I am quite clueless as to how the link is generated. Will try to do some research on it.

What I am afraid is for time being, I would just attempt a hack to make it work, and it might not be suitable for inclusion into the grappelli library.

**Comment by kokhoor** [comment]
What I believe can be done (although really feel hackish), is to override the function formfield_for_foreignkey in Inline, I believe is the same for ModuleAdmin, based on the function defined in BaseModelAdmin, and change  the widgets.ForeignKeyRawIdWidget construction in the following code:

        if db_field.name in self.raw_id_fields:
            kwargs['widget'] = widgets.ForeignKeyRawIdWidget(db_field.rel,
                                    self.admin_site, using=db)

What I did was subclass from widgets.ForeignKeyRawIdWidget and overwrite the url_parameters to add in my filters, which are actually defined in the actual Foreign Model Admin's list_filter

    def url_parameters(self):
        from django.contrib.admin.views.main import TO_FIELD_VAR
        params = self.base_url_parameters()
        params.update({TO_FIELD_VAR: self.rel.get_related_field().name})
        params['sell_ind__exact'] = '1'
        return params

**Comment by sehmaschine** [comment]
Sorry, but I'm not able to follow ... subclassing the widget is bound to a specific field (if I'm using M2Ms I need to subclass a different widget). That seems a bit strange ... or I just don't get it.

**Comment by sehmaschine** [comment]
closing this for now since there hasn't been any updates in a while now.
