### ISSUE TITLE
Update django-reversion templates

### ISSUE THREAD

**Issue by Sveder** [sehmaschine/django-grappelli#588]
The django-reversion templates that grappelli overrides are 3(!!) years old, and contain some things I consider deprecated (like the user.first_name and user.last_name fields, that don't exist for custom user models inherited from the AbstractBaseUser, and should be calls to get_full_name, etc).

Workaround: Put django-reversion before grapprlli in the installed_apps list.

**Comment by Sveder** [comment]
I just update object_history as it is the main offender for us. If someone wants to update the rest, go ahead.

**Comment by Sveder** [comment]
@sehmaschine Anything I can do to help get the pull request accepted? Do you want me to add/remove something?

**Comment by sehmaschine** [comment]
No worries, I just didn´t have the time yet.
