### ISSUE TITLE
UnicodeEncodeError on custom dashboard

### ISSUE THREAD

**Issue by tatterdemalion** [sehmaschine/django-grappelli#590]
VERSIONS: Grappelli 2.6.4, Django 1.8

I encountered an UnicodeEncodeError with my custom dashboard. It raises an error when i actually use the admin in Turkish.
I suppose it has something to do with this line in dashboard/utils.py L113:

```
pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural))
```

The problematic verbose_name for me here is: **Dergi İçerikleri**
When i change the line to

```
pattern_items.sort(key=lambda x: unicode(x[0]._meta.verbose_name_plural))
```

It works ok. But I am not familiar with Grappelli's codebase so I am not really sure if this tweak will or will not work for general purposes.

**Comment by sehmaschine** [comment]
interesting ... we just changed that because of a pull request (see #579). what python version are you using?

**Comment by tatterdemalion** [comment]
I encountered this problem both on my server and my local machine.

Server: Python 2.7.3
Local: Python 2.7.6

Ah. I got it now. unicode won't work in Python 3.
It is interesting because unicode_literals is already imported.

**Comment by twopac** [comment]
I have this problem too.
Python 2.7.6
Django 1.7.7

**Comment by Seleznev-nvkz** [comment]
Same problem.
Python 2.7.6
Django 1.7.7

**Comment by robslotboom** [comment]
Same here...

Python 2.7.2
Django 1.8

**Comment by sehmaschine** [comment]
I'm not able to reproduce this ... I'm using Grappelli 2.6.4 and Django 1.7.

verbose_name = u"Dergi İçerikleri"
verbose_name_plural = u"Dergi İçerikleri"

works fine.

**Comment by sehmaschine** [comment]
@tatterdemalion @twopac @Seleznev-nvkz @robslotboom ... can anybody give me a hint on how to reproduce this with django 1.7 and grappelli 2.6.4?

**Comment by Seleznev-nvkz** [comment]
of course. You can try pass this 

class Meta:
        verbose_name = u'Способ оплаты'
        verbose_name_plural = u'Способ оплаты'

and required python 2.7.x

**Comment by sehmaschine** [comment]
@Seleznev-nvkz thanks, but I don't get an error. works fine with my setup (python 2.7.3, django 1.7, grappelli 2.6.4)

**Comment by Seleznev-nvkz** [comment]
It's strangely, cause I have 
```UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)``` 
, but in version 2.6.3 all fine.
I attach screenshot below. And now we using 2.6.3 on production.
![grappelli_2 6 4](https://cloud.githubusercontent.com/assets/4374093/7292105/68606b8c-e9ba-11e4-9125-39a1ec30bb56.png)

**Comment by sehmaschine** [comment]
alright ... I finally could reproduce this. using "unicode" doesn't make sense since python3 uses "str".

my suggestion is to change line 113 of utils.py to:
pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))

maybe someone can test this as well and give some feedback. from my point of view, it's a clean solution and it should work with python2 and python3.

**Comment by ybigus** [comment]
also have this issue on django 1.7.8, python 2.7.3 @sehmaschine looks like this helps:pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural.encode('utf-8')))
