### ISSUE TITLE
Autocomplete doesn't work with postgres unaccent lookup (django 1.8)

### ISSUE THREAD

**Issue by honi** [sehmaschine/django-grappelli#591]
If configured to use the unaccent transform:

    @staticmethod
    def autocomplete_search_fields():
        return ['first_name__unaccent__icontains']

```/grappelli/lookup/autocomplete/``` raises an error: https://gist.github.com/anonymous/65f2b2a1988ab02d76bf

**Comment by sehmaschine** [comment]
That's because Grappelli is not yet compatible with Django 1.8.

**Comment by sehmaschine** [comment]
Please try with stable/2.7.x.

**Comment by sehmaschine** [comment]
Please reopen this ticket if the issue still exists.
