### ISSUE TITLE
Styles for branding block

### ISSUE THREAD

**Issue by ngzhian** [sehmaschine/django-grappelli#594]
Suggestion to tweak styles for `header#grp-header #grp-navigation div#grp-branding`, which are currently
```css
    float: left;
    margin: 0 10px 0 -20px;
    max-height: 36px;
    overflow: hidden;
    position: relative;
```
Not sure why the max-height is 36px, but this makes the branding block look really weird when placed beside the site title.
The entire top navigation bar is 52px tall, and since the branding is 36px with no top/bottom padding and margin, this makes the block stick to the top left corner.
![weird](https://cloud.githubusercontent.com/assets/1749303/7052044/17a647dc-ddfa-11e4-9e01-6c014b2f7ec9.PNG)

Can we consider changing it such that a padding of 8px 0 is given to the logo?
This will help center the logo vertically.
![correct](https://cloud.githubusercontent.com/assets/1749303/7052048/1de6c9b4-ddfa-11e4-8142-19a27e17cf74.PNG)

(also I'm assuming that most branding elements are logos, which is probably the case)
Also, happy to submit a PR if this makes any sense, thanks!

**Comment by parsch** [comment]
let me have a look at this before working on a pr

**Comment by parsch** [comment]
@ngzhian I'm not sure why your top navigation bar is 52px tall – did you apply any custom styles to it? Your ```ul#grp-user-tools``` on the righthand side must also suffer from that taller height, right?

**Comment by ngzhian** [comment]
well well great investigation @parsch , there was some styles overwriting the defaults, let me sort it out and see if this still remains and issue. Thank you for looking into this!

**Comment by ngzhian** [comment]
thanks again, problem solved, lots of messy styles caused the confusion. :see_no_evil:

**Comment by parsch** [comment]
allright
