### ISSUE TITLE
V2.6.4 cannot support chinese with Python 2.7.X

### ISSUE THREAD

**Issue by panweifeng** [sehmaschine/django-grappelli#599]
After I upgraded to 2.6.4,  my grappellli stop work because I use chinese as my module's verbose_name.

error is here grappelli/dashboard/utils.py 
line 113:
pattern_items.sort(key=lambda x: str(x[0]._meta.verbose_name_plural))

str cannot work with unicode in Python 2.7.X

**Comment by sehmaschine** [comment]
see #590
