### ISSUE TITLE
popup for related object does not work

### ISSUE THREAD

**Issue by and-nothing-else** [sehmaschine/django-grappelli#600]
When click "add related object" button executes function from related-widget-wrapper.js which exists in django.contrib.admin and does not exist in grappelli:

    container.on('click', '.related-widget-wrapper-link', function(event){
        if (this.href) {
            showRelatedObjectPopup(this);
        }
        event.preventDefault();
    });

but function `showRelatedObjectPopup` not exists in grappelli. Function name must be `showRelatedObjectLookupPopup`
![2015-04-19 13-45-36](https://cloud.githubusercontent.com/assets/10834021/7219160/5cb13d10-e69b-11e4-9537-cf89c4091085.png)

**Comment by sehmaschine** [comment]
which versions (django/grappelli)?

**Comment by and-nothing-else** [comment]
Django 1.8
Grappelli 2.6.4

**Comment by sehmaschine** [comment]
Note: Grappelli is not yet compatible with Django 1.8.

**Comment by m-aciek** [comment]
Workaround:
```
{% block extrahead %}
<script type="text/javascript">
  (function($) {
      $(document).ready(function() {
        $(".add-related, .change-related").each(function(num, link) {
          if ($(link).attr("href") != null) {
            $(link).attr("onclick", "event.preventDefault();showAddAnotherPopup(this)")
          }
        })
      });
  })(grp.jQuery);
</script>
{% endblock %}
```
in ```admin/base_site.html```. Looking forward to Django 1.8 support!

**Comment by mochawich** [comment]
Same as #591

**Comment by mochawich** [comment]
Same as #593

**Comment by sehmaschine** [comment]
see #593

**Comment by cossio** [comment]
I am not using Grappelli, but I am having the same issue (add related opens in same window instead of popup). I have no idea why this could be happening. Any ideas on how I can diagnose it?
