### ISSUE TITLE
Sizing/alignment issue for ManyToMany widget

### ISSUE THREAD

**Issue by c-nichols** [sehmaschine/django-grappelli#601]
Hi There,

Django 1.7.6, django-grappelli 2.6.4, Chrome 41.0.2272.118 (64-bit)

There's a slight issue with the default ManyToMany widget while using Grappelli -- the widget doesn't quite fit on one line, causing the second box to get bumped down below the left/right arrows. I'm not positive because I don't know much about the styling, but I'm guessing that fixed sizes + an added css border is causing the three elements not to fit.

See picture below:
![screenshot from 2015-04-21 10 56 29](https://cloud.githubusercontent.com/assets/7374139/7255277/35a1dc08-e816-11e4-90f9-93e183e0db2a.png)

**Comment by parsch** [comment]
@c-nichols Can't verify that problem (looks okay in my local environment using the same setup). I'm able to force this _only_ if I lower the width of ```.selector``` (from given 758px to < 758px). Are you sure there are no custom styles of yours? You might also try playing around with the width of that ```.selector``` (via web developer tools) and provide some more information on that problem.

**Comment by parsch** [comment]
Closing this as no further information was provided and issue couldn't be verified.

**Comment by c-nichols** [comment]
Sorry about the delay.  Turns out the way to reproduce is set zoom to <100%.
