### ISSUE TITLE
Autocomplete Lookups M2M clear all previous selected on search popup.

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#607]
Hi all,

I'm using the Autocomplete Lookups M2M and I notice that if I type and select many objects it works fine. But if I already selected some objects and I use de search button on right side to find a new one and select it on popup screen, all previous selected objects are cleaned and just this new one stay on selected objects instead just append with others previous selected.

I don't know if my explanations was good, but I'm where for any doubt.

**Comment by sehmaschine** [comment]
versions please!!!

**Comment by lzanuz** [comment]
Sorry, django-grappelli.git@stable/2.6.x#egg=grappelli

**Comment by sehmaschine** [comment]
and which django version???

**Comment by lzanuz** [comment]
django==1.7.7

**Comment by lzanuz** [comment]
Hi, I tried in another machine and it's OK. Maybe it's something wrong with my virtualenv. I'll reinstall everything for test.

**Comment by lzanuz** [comment]
It's working. There was someting wrong whith my envoriment on that time. Sorry.
