### ISSUE TITLE
django-constant template error [critical]

### ISSUE THREAD

**Issue by alex1989** [sehmaschine/django-grappelli#609]
Error happens due to grappelli constant template was create incorect it can be fixed just changing few lines of code. I have written it already, this is code lines:
```
{% if form.errors %}
  <ul class="grp-messagelist">
{% endif %}
{% for field in form.hidden_fields %}
  {% for error in field.errors %}
    <li class="grp-error">{{ error }}</li>
  {% endfor %}
    {{ field }}
{% endfor %}
{% if form.errors %}
  </ul>
{% endif %}
```
But now it is:
```
{% if form.errors %}
  <ul class="grp-messagelist">
  {% for field in form.hidden_fields %}
    {% for error in field.errors %}
      <li class="grp-error">{{ error }}</li>
    {% endfor %}
    {{ field }}
  {% endfor %}
  </ul>
{% endif %}
```

How you can see hidden_fields added to template only if we have error, it's not right.
Also I added link to github with this error for easy fix (https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/templates/admin/constance/change_list.html#L54).

I think it's critical error and it must be fixed as soon as possible. Thanks for grappelli.

P.S. Sorry for my english, if I have mistakes in this issue, I'm from Russia.

**Comment by sehmaschine** [comment]
Sorry, I don't get it ... you want to add <li> to a template without having a surrounding <ul>?

**Comment by alex1989** [comment]
I want to say that constant can be updated because of django-constant have hidden field version, and this field isn't include to template, and because of constant isn't save, just looking to django-constant admin template and you'll upderstand.

Links:
Template [https://github.com/jezdez/django-constance/blob/master/constance/templates/admin/constance/change_list.html#L43]
Admin file with form [https://github.com/jezdez/django-constance/blob/master/constance/admin.py#L62]

There is field version and this field is hidden, and if we don't change constance template it error will happens in the future

**Comment by sehmaschine** [comment]
I'm not sure it answers my question ... so you actually wanna add list-elements without having a list, right? Isn't that weird?

**Comment by alex1989** [comment]
I understood what you want, you can change it another way, something like this, but it's need correct
```
{% for field in form.hidden_fields %}
  {% if form.errors %}
    <ul class="grp-messagelist">
    {% for error in field.errors %}
      <li class="grp-error">{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  {{ field }}
{% endfor %}
```

**Comment by sehmaschine** [comment]
@alex1989 sorry for the delay. happy with the fix?

**Comment by sehmaschine** [comment]
Closing this since it should be fixed. Please reopen if the issue still exists.
