### ISSUE TITLE
when using `autocomplete_lookup_fields`, javascript break.

### ISSUE THREAD

**Issue by shnode** [sehmaschine/django-grappelli#611]
django version:  1.8
grappelli version : 2.6.4
python version: 3.4.3

add `autocomplete_lookup_fields` in `admin.ModelAdmin` will cause a javascript error like this:

![image](https://cloud.githubusercontent.com/assets/7784713/7627719/c744a1ac-fa4c-11e4-8121-90ddfba207cb.png)

(` Uncaught TypeError: Cannot use 'in' operator to search for '0' in [` in `jquery-1.9.1.min.js`)

this is my model:

    class Choice(models.Model):
        #...
        name = models.CharField(max_length=256, verbose_name=_('name'))
       
        def __str__(self):
            return self.name

        @staticmethod
        def autocomplete_search_fields():
            return ("id__iexact", "name__icontains",)

    
    class Question(models.Model):
        #...
        choice = models.ForeignKey(Choice, blank=True, null=True, verbose_name=_('ctqa'))

and the admin:

    class QuestionInline(nested_admin.NestedStackedInline):
        raw_id_fields = ('choice',)
        autocomplete_lookup_fields = {
            'fk': ['choice',],
            'm2m': [],
        }

I don't know why when I add the `autocomplete_lookup_fields`, the mistake appears.

Is there something wrong with my usage?

**Comment by m-aciek** [comment]
Note that Grappelli is not compatibile with Django 1.8 yet.

**Comment by lzanuz** [comment]
Try dev/2.7.x with django 1.8+
But it's development.

**Comment by sehmaschine** [comment]
should work with stable/2.7.x ... please reopen if the issue still exists.
