### ISSUE TITLE
verbose name of inline formset is rendered, styled as "display: none;'

### ISSUE THREAD

**Issue by ngzhian** [sehmaschine/django-grappelli#613]
Relevant code is [here](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/templates/admin/edit_inline/tabular.html#L33):
```python
<h3 style="display: none;"><b>{{ inline_admin_formset.opts.verbose_name }} #{{ forloop.counter }}</b>&nbsp;&nbsp;{% if inline_admin_form.original %} {{ inline_admin_form.original }}{% endif %}</h3>
```
Any reason why this is displayed as such? Maybe we use JavaScript to toggle the display of this? (probably not because there are no styles associated with this). If we don't need it we can probably strip out this line.

The relevant template for django is [here](https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/edit_inline/tabular.html).

**Comment by parsch** [comment]
We chose to hide that headline because showing it reduces the clarity/readability of the tabular layout.

**Comment by ngzhian** [comment]
@parsch understood, in that case can we just remove that line then? In my use case it is an extra DB hit to query the name.

**Comment by parsch** [comment]
@ngzhian currently not (we wanted to leave it in there for e.g use with document outlines etc.)

**Comment by ngzhian** [comment]
@parsch got it, thanks!
