### ISSUE TITLE
Changelist with Sortable Field

### ISSUE THREAD

**Issue by antoyo** [sehmaschine/django-grappelli#614]
Hello.
It would be nice to have an option like `sortable_field_name` of Inline Sortable that works on the model directly on the change list as provided by [django-admin-sortable](https://github.com/iambrandontaylor/django-admin-sortable).
Thanks.

**Comment by sehmaschine** [comment]
that would be nice indeed. does django-admin-sortable work with grappelli? do we just need to change the styles?

**Comment by antoyo** [comment]
Yeah, it works together, but the style needs to be updated.

**Comment by HWDexperte** [comment]
This would be really really nice!

**Comment by sehmaschine** [comment]
closing this since django-admin-sortable seems to be outdated (no updates for quite some time and looking for maintainers).
