### ISSUE TITLE
support change/delete link with django 1.8?

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#618]
there is now an option to show a changelink with inlines (show_change_link). moreover, FK dropdowns have an edit/delete link.

question is if we should support this, because the implementation is strange and not consistent – e.g., why is edit/delete only available with dropdowns and not with raw-id-fields. why can I edit an FK (via popup) and get back to the original admin page while this is not true with editing inlines. at first glance, this "feature" looks like noone thought about a decent implementation (so it's a feature just for the sake of having it and therefore confusing).

that said, I'm open for discussions.

**Comment by lzanuz** [comment]
Hi @sehmaschine

I really think that is important, so I had developed an improvement on my system to do that. I added a button on left widget that on click open a popup to edit the selected object.  If this feature was supported on grappelli will be very useful for all.

/admin/<app>/<object>/<id>/?_popup=1

![2015-06-15 09-07-22](https://cloud.githubusercontent.com/assets/5805339/8159592/8e7c0fda-133e-11e5-8377-d6e26f60aac4.png)

**Comment by m-aciek** [comment]
Hi, I think it would be great if Grappelli would cover all of the standard admin features and extend it, and do not left it behind in functionality. I think answer to your question is in deed question of resources to do that.

**Comment by sehmaschine** [comment]
I'm having a raw-id-field with tabular inlines ... I do get the edit link with the field. The same field within the changeform and no edit link is given. Can someone please explain how this "feature" is supposed to work, because I just don't seem to get it!

**Comment by lzanuz** [comment]
Sorry. I never used raw-id-fields with inlines.

**Comment by andreynovikov** [comment]
@lzanuz How did you add this button? I'm seeking for it too.

**Comment by olivierdalang** [comment]
@Izanuz I'm also very interested in your modification (in the meantime it's implemented in master), do you have a branch ?

**Comment by dbinetti** [comment]
I use this for inlines; when viewing inline children of a parent record it is incredibly useful to easily click to a child record that requires further inspection -- particularly when the inline only shows a subset of all available fields.  Yes, it is easy to create such a link and include it, but this is how i used the `show_change_link` parameter when using the default admin app.

**Comment by brenouchoa** [comment]
https://github.com/CrossWaterBridge/django-grappelli-autocomplete-fk-edit-link
seams that have accomplished what you guys and i need.

**Comment by philippeluickx** [comment]
My use case is that I would love to have the edit and delete links in the FK dropdowns, but nothing in the inlines.
It's basically to simplify interaction. It saves a lot on navigation and searching.

**Comment by helenst** [comment]
I'd like this. I've currently got this (the change bit anyway, for FK dropdowns) working on a site of mine but I've had to override the bits of Grappelli that override the bits of Django that implement this, which is kind of messy.

Would a PR be accepted / considered?

**Comment by sehmaschine** [comment]
it would be considered ... a consistent implementation is a requirement though (see my first comment).

**Comment by kevkdl** [comment]
It's useful to have it, I use it from a TabularInlines to another modelAdmin with inlines.
I started on the example of @lzanuz for my tool by modifying the tabular.html

![image](https://cloud.githubusercontent.com/assets/16896831/21810521/76baf428-d74c-11e6-89f8-700d8c6763a0.png)

**Comment by phcerdan** [comment]
Hey, I really like grappelli, but please don't drop built-in functionalities, it is not fun to read django docs, try them in my app, and not working because of an external plugin. I thought `grappelli` was an extension of the default `admin`.

**Comment by phcerdan** [comment]
+1 for this sorry for not being more helpful.

**Comment by dancastellani** [comment]
+1 for this.
Is there any update on this?
Any guidelines on how to implement it?

**Comment by sehmaschine** [comment]
Solved with 2.12.2.
