### ISSUE TITLE
LANGUAGE_BIDI not working

### ISSUE THREAD

**Issue by mohamad-xtouch** [sehmaschine/django-grappelli#619]
hi
i am set a variable in the setting with this name "LANGUAGE_BIDI"
value of the variable is True
but template does not change to rtl mode

settings.py
LANGUAGE_BIDI = True

# rtl mode does not working

**Comment by sehmaschine** [comment]
please reopen the tickets with adding versions (django, grappelli).

**Comment by mohamad-xtouch** [comment]
django 1.8
grappelli 2.6.5
