### ISSUE TITLE
FilteredSelectMultiple widget: trigger opening of "add new object" popup when Enter hit and no matches to filtering string.

### ISSUE THREAD

**Issue by m-aciek** [sehmaschine/django-grappelli#623]
Regarding widget for many-to-many field in `filter_horizontal` tuple in admin changeview.

When you start to filter out objects to choose from, when you hit Enter, first item in filtering list is being selected. It works perfectly.

It would be great if hitting enter after writing name in the filter input when there is no matches in a list would cause "add new object" popup to show and one of fields (specified before) to be filled with string just written in a filter input.

Or at least if just clicking `+` button on the right would cause preserving entered string to some field in creation form.

**Comment by sehmaschine** [comment]
sorry, but that seems to be out of scope. besides, shouldn't that be a django issue instead of a grappelli issue?

IMHO the filter_horizontal widget should be removed completely.
