### ISSUE TITLE
How to change the admin datepicker format to DD/MM/YYYY? 

### ISSUE THREAD

**Issue by niranjfantain** [sehmaschine/django-grappelli#624]

**Comment by parsch** [comment]
Please use the google group for asking questions (this is an issue tracker).

Basically you have to add a custom datepicker-js by using a Media inner class on your ModelAdmin (see https://docs.djangoproject.com/en/dev/ref/contrib/admin/#modeladmin-media-definitions).

A description and axample file can be found here: https://groups.google.com/forum/#!searchin/django-grappelli/datepicker/django-grappelli/nPZe74hR9NE/I_mOY9gZjGsJ
