### ISSUE TITLE
grp-content css top position missplaced

### ISSUE THREAD

**Issue by menarguez** [sehmaschine/django-grappelli#626]
There is a problem with the top property of grp-content in the static css file, which is set to 80. 
 
![error top](https://cloud.githubusercontent.com/assets/5756883/8092220/0eebbfae-0f7e-11e5-96fe-d4b2d3afadfe.png)

Setting top manually to 115 in the grappelli/static/grappelli/stylesheets/screen.css and collecting static files again file solves it.
![error top-fixed](https://cloud.githubusercontent.com/assets/5756883/8092300/714cc6a2-0f7e-11e5-837c-96ad6bcad67b.png)

Django==1.8
django-grappelli==2.6.5
python = 2.7
static-files are loaded with no errors and are updated

**Comment by parsch** [comment]
@menarguez Seems you customized your admin title, right? If so, you'll have to customize the styles, too.

**Comment by parsch** [comment]
Closing this, as issue couldn't be verified and no further information has been provided.
