### ISSUE TITLE
Import Warning Django 1.8

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#629]
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.

File: grappelli/dashboard/registry.py

**Comment by oelium** [comment]
you have the same warning in File: grappelli/views/related.py line 17

**Comment by sehmaschine** [comment]
@oelium cannot reproduce. please open a new ticket and add some details (django.utils.importlib is not available with related.py).

**Comment by oelium** [comment]
ok sorry. it's and error.
the import on File: grappelli/views/related.py line 17 -> from django.contrib.admin.util .... Removed in Django 1.9 by django.contrib.admin.utils

sorry for this confusion

**Comment by sehmaschine** [comment]
there is no django.contrib.admin.util in related.py

**Comment by oelium** [comment]
![capture du 2015-07-23 13 08 18](https://cloud.githubusercontent.com/assets/13416461/8848944/ef33e832-313b-11e5-86f8-267b2f2bfb0e.png)

**Comment by sehmaschine** [comment]
wrong grappelli version, I guess:
https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/views/related.py#L17

**Comment by oelium** [comment]
ok. i see. when i download the zip file i have in related.py 'django.contrib.admin.util' but not with git clone.

Thank..
