### ISSUE TITLE
Small skin issues on grappelli 2.7.x

### ISSUE THREAD

**Issue by lzanuz** [sehmaschine/django-grappelli#633]
Different height on multiple widget on right element style in 9px higher that left.

![screenshot-localhost 8008 2015-06-17 21-30-01](https://cloud.githubusercontent.com/assets/5805339/8221785/06da503a-1539-11e5-993d-5113d39cf095.png)

On inlines widget now seems that there is a yellow background on mouse over a item.

![screenshot-localhost 8008 2015-06-17 21-30-02](https://cloud.githubusercontent.com/assets/5805339/8221817/6cd9634e-1539-11e5-9cac-2609f213a213.png)

**Comment by parsch** [comment]
@lzanuz which browser are you using?

**Comment by lzanuz** [comment]
This happens for me on both browsers.

Goggle Chrome  42.0.2311.90 (64-bit) 
Firefox 38.0.5

On rigth select multiple widget <id_field_to> there is a inline style thtat set the height. If I remove it the height is the same on both sides.

About the yellow backgroud on inlines widget, I think that jquery UI is using a different theme, because if you run this on 2.6.x version and 2.7.x version is different theme. On 2.7.x is a yellow theme.

run on browser console:   grp.jQuery('#grp-content-title').dialog();

**Comment by parsch** [comment]
Thank you! I'll take a look at that...
