### ISSUE TITLE
Fields are not displaying at Grappelli Django Admin.

### ISSUE THREAD

**Issue by hemantkshirsagar8** [sehmaschine/django-grappelli#636]
Hi guys,

I have integrated Grappelli Django admin interface with existing django admin pannel,
Everything is working fine, but Formd Fields are not displaying, whenever i click on Add New/Change button.
Example: 
1. Home/Groups/Add
2. In this page is loading but no fields are available to enter data.

Please help me on this. Thanks !

**Comment by sehmaschine** [comment]
Please use the Google-Group for asking questions (hint: add Django/Grappelli versions). If you think this is a bug, please reopen this ticket and add some debugging details.
