### ISSUE TITLE
Grappelli's object_history view hardcodes first LogEntry message

### ISSUE THREAD

**Issue by michael-fairfly** [sehmaschine/django-grappelli#637]
The first LogEntry message in the history view (object_history.html) is hardcoded to be "Created Object":

```
                            {% ifequal forloop.counter 1 %}
                                {% trans "Created object" %}
                            {% else %}
```

This is not great because:
1. Created objects can also have "change" messages that are useful (for example whether it was created by admin, app, website, code)
2. When creating outside of the admin view, sometimes the ADDITION LogEntry doesn't exist, and the first is a CHANGE LogEntry, thus this is obstructing the message.

The fix is just to remove this line and have only this:
```
{{ action.change_message }}
```

(Adding a pull request in a bit)

**Comment by sehmaschine** [comment]
@michael-fairfly do you know how that fix is related to this ticket? because the pull-request is about the reversion template, your ticket doesn't mention reversion.

**Comment by Sveder** [comment]
Haha, sorry, I didn't sync my branch so it looks like github added the merge and my previous commit to the PR. If you look at the files changed, it shows the actual only change which is the one above. 
Feel free to close the pull request and just copy paste the change into your own commit.

**Comment by sehmaschine** [comment]
alright, thanks for the clarification.
