### ISSUE TITLE
Class selector (filter_horizontal) isn't working properly after refresh in the latest FF

### ISSUE THREAD

**Issue by niorko** [sehmaschine/django-grappelli#645]
__VERSIONS__: Grappelli 2.7.1, Django 1.8.3, Firefox 37.0.2
__STATICFILES__: OK
__JAVASCRIPTS__: OK
__CUSTOMIZATIONS__: using filter_horizontal

1) Load the admin interface (for examples Groups).
2) See all the results
3) Refresh the page
4) Selected items on the right is missing (there are like not selected)
5) Go to the URL bar, hit the enter to reload the page from the scratch
6) Items are selected

So as you are refreshing the page, selected items are missing in the every m2m relations with filter_horizontal. In every other browser (Vivaldi, Chrome, Safari) it's working properly.
It doesn't depend on the version of the Django or even the Grappelli, so it has something to do with the actual or even older version of the Firefox.

It is happening in the 4 projects with different configurations.

**Comment by parsch** [comment]
Seems to be a Django bug: https://code.djangoproject.com/ticket/22955

**Comment by niorko** [comment]
But when I disable grappelli, items remain selected after refresh.
So it seems like a bug in some of the grappelli .js.

**Comment by parsch** [comment]
@niorko When I disable Grappelli (Djano only) I get the same behaviour...

**Comment by parsch** [comment]
Might be an issue with the cache of SelectBox.js as the misbehaviour doesn't appear if the page is reloaded with overriding the cache (cmd+shift+r OSX)
