### ISSUE TITLE
Django 1.8 Warning - url from future tag Removed in Django 1.9

### ISSUE THREAD

**Issue by oelium** [sehmaschine/django-grappelli#648]
RemovedInDjango19Warning: Loading the `url` tag from the `future` library is deprecated and will be removed in Django 1.9. Use the default `url` tag instead.
  RemovedInDjango19Warning

In some template grappelli use the 'url' tag from the future.py module like this
{% templatetag openblock %} load url from future {% templatetag closeblock %}
But in django 1.9 this tag will be removed. 
You can find them in
* grappelli/templates/grp_doc/change_form.html line 53
* grappelli/templates/grp_doc/change_list.html line 53

so need to use directly {% url 'my_views' %}

**Comment by sehmaschine** [comment]
true ... but that's just the template documentation, so not a major issue here. we'll take a look.

**Comment by oelium** [comment]
for info you have the same in fillebrowser.
I open a ticket on the repo with the list files.

**Comment by parsch** [comment]
@oelium Sorry, cannot find"load url from future" or  "future" in any of the grappelli 2.7.x templates and surely not on the lines (53) mentioned above. Can you specify that issue?

**Comment by sehmaschine** [comment]
closing this since nor further details are given. please reopen if this issue still exists.
