### ISSUE TITLE
Random relationship statistics on delete confirmation page

### ISSUE THREAD

**Issue by byashimov** [sehmaschine/django-grappelli#652]
There is only one post in blog with only one post-hub relation. New statistics every page reload:
<img width="436" alt="screen shot 2015-07-31 at 11 17 39" src="https://cloud.githubusercontent.com/assets/1560043/9004390/db89ee90-3775-11e5-9eee-754e2538f2bc.png">

    django 1.8.3
    django-grappelli 2.7.1

**Comment by sehmaschine** [comment]
what happens if you deactivate grappelli? do you get a different result?

**Comment by byashimov** [comment]
It's totally okay
![c9f66f2bb88a44236479ff843fc223c7](https://cloud.githubusercontent.com/assets/1560043/9006746/2f726554-378b-11e5-930f-d676d431096d.png)
:

**Comment by sehmaschine** [comment]
can you try to find out what's causing this? because I'm not able to reproduce it.

**Comment by byashimov** [comment]
Looks like it's not "grappelli" thing. I've reproduced the issue without grappelli on my Prod config.
<img width="488" alt="screen shot 2015-07-31 at 14 02 45" src="https://cloud.githubusercontent.com/assets/1560043/9006988/6b42fe66-378d-11e5-8d63-48efb3f4240e.png">
Thank you for your time.
