### ISSUE TITLE
How add my own css to all the pages or how to extend base.html?

### ISSUE THREAD

**Issue by vartagg** [sehmaschine/django-grappelli#653]
I need to add some css file to my admin page, but I didn't find the solution for including it to all the admin pages. Is there a way for it? Or is there a way for extend grappelli `base.html`?

**Comment by sehmaschine** [comment]
Please use the google-group for asking questions. Thank you!

Besides: there is a whole lot of answers to this question already (because it is not related to grappelli).

**Comment by vartagg** [comment]
Thanks for your answer.

**Comment by sehmaschine** [comment]
search for extending django admin templates (not related to grappelli). you can add custom css with your model admin definition or you can overwrite base.html and add your css there.

https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#modeladmin-asset-definitions
https://docs.djangoproject.com/en/dev/ref/contrib/admin/#overriding-admin-templates
