### ISSUE TITLE
Showing all models in dashboard

### ISSUE THREAD

**Issue by fcasco** [sehmaschine/django-grappelli#658]
When I login with a user with limited permissions I can see all models in the dashboard.

This happens only if I had logged in with an staff user previously (even in another browser).

I think it only calls 'init_with_context' once and then always uses the same dashboard without leaving only the models that the current user has permissions to see.

**Comment by sehmaschine** [comment]
did you try to debug this issue? any details?

**Comment by fcasco** [comment]
I think I know where the problem is in some module we define some DashboardModule, then we import it in the dashboard module and add it in `init_with_context`.
My guess is that the module is the same for all the requests and so it is not changed according to the request being served.
I will try to fix this in short and post back if I can't make it work.

**Comment by fcasco** [comment]
z
