### ISSUE TITLE
pass_reset_done.html incorrect sentence

### ISSUE THREAD

**Issue by Wenze** [sehmaschine/django-grappelli#660]
Hi,

I'm using Django 1.8 with Grapelli 2.7.1. When using a internationalization I found an incorrect sentence in: pass_reset_done.html

**Line 16 is:**
We've emailed you instructions for setting your password. You should be receiving them shortly.

**And should be:**
We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

**Comment by parsch** [comment]
Thanks for reporting
