### ISSUE TITLE
on add click popup full website is shown

### ISSUE THREAD

**Issue by techietek** [sehmaschine/django-grappelli#661]
Hey Guys,

So when I click the add as shown in the screenshot
![screen shot 2015-09-04 at 11 21 14 pm](https://cloud.githubusercontent.com/assets/8494130/9695634/b2ae5680-535b-11e5-8cb8-28855162d54b.JPG)

once i add the record it saves and does not return to my original screen it used to work nicely not sure where to look for this one.

**Comment by sehmaschine** [comment]
which version of grappelli? which django version? which browser?

**Comment by techietek** [comment]
hi i should have added that information apologies:

django==1.7.9
django-grappelli==2.7.1
browser==chrome

**Comment by sehmaschine** [comment]
grappelli 2.7 is not compatible with django 1.7, see http://django-grappelli.readthedocs.org/en/latest/#versions-and-compatibility
