### ISSUE TITLE
Validation of unused inlines

### ISSUE THREAD

**Issue by jieter** [sehmaschine/django-grappelli#664]
When I have a form for model A with inlines for moel B, with model B having a foreign key to model C, the foreign key field in the unused inlines prevents the form from being submitted:

![example](https://github.com/jieter/grappelli-inline-validation-example/raw/master/2015-09-11-112702_1001x1028_scrot.png)

If I remove 'grappelli' from my INSTALLED_APPS, its works as expected.

Am I missing  something in the grappelli docs, or is this a bug?

Example here: [@jieter/grappelli-inline-validation-example](https://github.com/jieter/grappelli-inline-validation-example)

**Comment by sehmaschine** [comment]
see http://django-grappelli.readthedocs.org/en/latest/customization.html#sortable-excludes

If there is one value within the row (e.g. quantity or units) we assume that this row has been added. Therefore the validation error (even with a different field).

**Comment by jieter** [comment]
@sehmaschine allright, it works now, thanks. 

Maybe the wording in the docs could be made more clear.

**Comment by sehmaschine** [comment]
@jieter any suggestion on the wording?

**Comment by jieter** [comment]
I think it should be clear what happens if you do not add `sortable_excludes`. It now says 'you <b>may</b> want to define...', which is not clear. I'm also not sure what you mean by 'having an effect on the position field'. In general, I think I expect these kind of docs (not strictly API docs), to be in the form of `problem -> solution` and not `solution -> problem`.

Maybe something like: 'If you enable sorting on inlines with default values, you should define `sortable_excludes` to exclude those fields while checking if something changed.... ' 

Also the comments in the example are not very helpful as it is very clear that `sortable_excludes` is defined without the comment. I think it could help more if it tells why 'field_1' and 'field_2' are added to that tuple.

Another issue when looking at these code examples: the comment in the code fragment just above the Sortable excludes paragraph basically states that sortable_field_name is 'position' by default, in an example about `GrappelliSortableHiddenMixin`. I think that comment should be reflected in the text about `sortable_field_name` and maybe in its example, but it's distracting in the docs about `GrappelliSortableMixin`

**Comment by sehmaschine** [comment]
@jieter thanks ... good points. I reopen this ticket as a reminder for updating the docs.

**Comment by jieter** [comment]
If you are on it: I just discovered that having a `position = models.PositiveSmallIntegerField()` on a model makes it impossible to ignore the position field while not working in the admin. I want to be able to just add related models, so maybe you should include `null=True` in the docs to make that possible while retaining sorting capabilities in the admin.

**Comment by sehmaschine** [comment]
@jieter Tried my best to explain the behaviour. Please reopen if you still think we can improve this.

**Comment by jieter** [comment]
much better :+1:
