### ISSUE TITLE
switch_user_dropdown() fails in 2.7.1

### ISSUE THREAD

**Issue by SebasSBM** [sehmaschine/django-grappelli#665]
VERSIONS: Grappelli 2.7.1(stable), Django 1.8.3, Python 2.7.6
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: NONE

I am testing the new version of django-grappelli (downloaded with pip repository).

Everything seems to work properly: the admin panel has Grappelli style, collapsable forms work, etc.

But, when I run `python manage.py test grappelli`, 2 of 9 tests fail:

    Creating test database for alias 'default'...
    .....FF..
    ======================================================================
    FAIL: test_switch_login (grappelli.tests.test_switch.SwitchTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/venvs/mdrcms/lib/python2.7/site-packages/grappelli/tests/test_switch.py", line 62,
      in test_switch_login
        self.assertEqual(t, t_cmp)
    AssertionError: '' != '<li><a href="/grappelli/switch/user/3/?redirect=/admin/grappelli/
    category/" class="grp-switch-user-is-target">Editor001</a></li><li><a href="/grappelli/
    switch/user/4/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">
    Editor002</a></li>'
    
    ======================================================================
    FAIL: test_switch_superuser001_editor001 (grappelli.tests.test_switch.SwitchTests)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/venvs/mdrcms/lib/python2.7/site-packages/grappelli/tests/test_switch.py", line 126,
     in test_switch_superuser001_editor001
        self.assertEqual(t, t_cmp)
    AssertionError: '' != '<li><a href="/grappelli/switch/user/1/?redirect=/admin/grappelli/
    category/" class="grp-switch-user-is-original">Superuser001</a></li><li><a href="/grappelli/
    switch/user/3/?redirect=/admin/grappelli/category/" class="grp-switch-user-is-target">
    Editor001</a></li><li><a href="/grappelli/switch/user/4/?redirect=/admin/grappelli/category/"
      class="grp-switch-user-is-target">Editor002</a></li>'

    ----------------------------------------------------------------------
    Ran 9 tests in 12.952s

    FAILED (failures=2)

I did read the testing script reffered in the traceback, and I "figured out" that it seems to be a dropdown menu's rendering failure (after all, switch_user_dropdown() is returning empty string in both cases).

**Due to I'm not sure about that Python 2.7.9 is deprecated or not**, I considered reporting this issue
would probably help somehow. I am not using multiple users in my own "manual testing" I might add.

**Comment by sehmaschine** [comment]
thanks for reporting. why do you think python 2.7.9 could be deprecated?

**Comment by SebasSBM** [comment]
Due to I compiled it from source because it wasn't available in apt-get repositories. In addition, this Python 2.7.9 console lacks some features (like moving the cursor in the command prompt, or switching to the commands you used earlier with up and down arrows) that the default Python 2.7.3 included.

Due to this cause, I consider plausible that some functions available in 2.7.3 became deprecated in 2.7.9, or work in a different way, or something else with the potential to "break" the code, to say something.

Now I think 2.7.9 is not the problem at all. In any case, I'm not sure.

**Comment by SebasSBM** [comment]
I've been looking at the function switch_user_dropdown() itself, and it is made to return empty string if SWITCH_USER is False. I don't know enough details to be sure about if this has been made on purpose or not, but I think the test is probably giving a "false negative" - in other words, assertion fails even if it is working as it has to work?

I hope this helps.

**Comment by SebasSBM** [comment]
After fixing incorrect configurations of STATIC_ROOT, MEDIA_ROOT and STATICFILES_DIRS in `myproject/settings.py`, those 3 errors has dissappeared. Instead, this error appeared in the test:

```
======================================================================
FAIL: test_autocomplete_lookup (grappelli.tests.test_related.RelatedTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/venvs/mdrcms/lib/python2.7/site-packages/grappelli/tests/test_related.py", line 198, in test_autocomplete_lookup
    self.assertEqual(response.content, json.dumps([{"value": None, "label": "0 results"}]))
AssertionError: '[{"value": null, "label": "0 resultados"}]' != '[{"value": null, "label": "0 results"}]'
```

This new error is probably caused by `LANGUAGE_CODE = 'es-es'` in `myproject/settings.py` (the only difference between the expected result and the actual result is the word `resultados` which is results in Spanish). So, this is a minor failure of the test itself that makes assert statement to fail just because the language is different...

**MY OPINION:**
Due to the original cause of the opening of this issue has dissappeared, and seemed to be caused by my own misconfiguration, maybe this issue should be closed...

**Comment by sehmaschine** [comment]
just tested the original issue (switch user dropdown) again and it works fine with my setup. I'm closing this issue for now ... please reopen a new one if this error (or one of the others) still exists.

no worries about the waste of time. you mainly figured it out yourself anyway.
