### ISSUE TITLE
Grapelli 2.7.1's backoffice fails selecting records with checkboxes

### ISSUE THREAD

**Issue by SebasSBM** [sehmaschine/django-grappelli#666]
VERSIONS: Grappelli 2.7.1(stable from pip), Django 1.8.3, Python 2.7.9
STATICFILES: OK
JAVASCRIPTS: OK? I'm not sure due to this failure (Tested in Firefox 40)
CUSTOMIZATIONS: NONE *
\* ...unless adding tinymce.js through `myapp/admin.py` counts as a customization...

The failure itself looks simple: if I try to select a model's record in admin panel clicking the checkboxes, it keeps saying "selected 0 of n" and doesn't let me perform DELETE operation through the admin's GUI. This issue happens with any kind of model; even the basic ones, like the users for example.

Maybe I can try to figure out why this happens - (I mean, I feel comfortable with Python, HTML, CSS -not so comfortable with CSS, but I understand it xD-, JavaScript, jQuery -technically, it is a JavaScript's library :P- and SQL languages; and I have been dealing with Django framework for six months or more)... The problem is that I have no idea where are the functions that control the checkbox's state to start debugging (I mean, I know where to find the package and the source in my machine, but not which order should I follow to analyze the implied functions/classes, because I just don't know them yet)... however, I would try it out.

PD: How do things work in case I want to self-assign this issue? I guess I would probably need permission or something...

**Comment by SebasSBM** [comment]
It looks like `python manage.py collectstatic` didn't collect `grappelli/static/admin` (see <a href="https://django-grappelli.readthedocs.org/en/2.7.1/quickstart.html#setup">the Quickstart Guide setup section</a>). I tried to copy/paste that folder into my project's static directory, but the bug didn't fix...

**Comment by sehmaschine** [comment]
are you sure the right actions.js is being loaded (the grappelli one and not the one from django admin)?

**Comment by SebasSBM** [comment]
Well, I'm not sure at all. Right now I was trying to debug JS with Firebug. The following log is shown:

    TypeError: $(...).actions is not a function
        $("tr input.action-select").actions();

I am trying to track this hardcoded JS function through the templates. It looks like it is in `templates/admin/change_list.html` line20...

**Comment by sehmaschine** [comment]
just check if actions.js is equal to grappellis actions.js (you only need to copy the URL and check with your browser).

**Comment by SebasSBM** [comment]
I made copy-paste from `actions.js` from Firebug to a dumb file, to compare them with `diff`. Identations are different (they come as tabs from Firebug) and this is interfering with the result. I'll replace tabs for spaces with vim to see if I can obtain a better comparison...

**Comment by sehmaschine** [comment]
Well ... then you have to make sure the correct one is being loaded. Seems more like a setup/Django issue than related to grappelli.

**Comment by SebasSBM** [comment]
Probably... but it is strange: the rest of grappelli's JS seem to be correct (grappelli's style loaded, collapsables also work). I will check once again my `settings.py` file just in case, but, in theory, static files load well...

**Comment by sehmaschine** [comment]
yep, it's strange indeed. there has been a ticket about this issue a while ago, but I've never been able to reproduce this behaviour.

**Comment by SebasSBM** [comment]
It is some kind of conflict between `django/contrib/admin/static/admin/js/actions.js` and the one coming from Grappelli. In any case, I remember that when I installed Grappelli following <a target="_blank" href="https://django-grappelli.readthedocs.org/en/2.7.1/quickstart.html">the Quickstart Guide</a> and run collectstatic, suddenly a folder called "grappelli" appeared in my static directory, but **the "admin" directory didn't**. I am not sure if this is correct behaviour or not...

In any case I don't know how Grappelli (or some other external app) is supposed to deal with static conflicts like this one, when it wants to override them. I just know django uses "the first file it finds". `python manage.py findstatic actions.js` returns "No match found". I am stuck here...

I will search in Django docs to see if there is a clean way to deal with this kind of overriding...

**Comment by dhbahr** [comment]
@sehmaschine sorry for duplicating the issue, my bad
@SebasSBM have you found any reason for this, as I see on my debugger, the static/admin/js/actions.js is included. I have no actions.js from Grappelli though. 
What I am getting is an error 
```
Uncaught TypeError: $(...).actions is not a function
```
on line 63 of the html document
```
    $(document).ready(function() {
        $("tr input.action-select").actions();
    });
```

**Comment by dhbahr** [comment]
Well.. bless me if you want to. I did a second `collectstatic` (which by the way said nothing needed to be done), hitted Ctrl+R on my browser et voilá: actions.js is working just fine ... misterious ways

**Comment by sehmaschine** [comment]
/static/admin/js/actions.js should be the grappelli file (although it probably isn't with your setup). due to the way collectstatic works, you might wanna try to re-install grappelli and then do collectstatic again.

if you do ```python manage.py findstatic admin/js/actions.js``` the grappelli file should be the first one.

**Comment by SebasSBM** [comment]
In my case, the one included was that one from django, instead of the one from the Grappelli module. But I finally got an idea to resolve it: just adding this in `myproject/settings.py`:

    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        'django.contrib.staticfiles.finders.FileSystemFinder',
    )

This way Django will lookup in the apps first. However, this doesn't seem clean enough as a general solution (it looks a little hacky, it would alter the default behaviour of Django). I would be making a fork of grappelli/settings.py to include this setting otherwise...

**Comment by sehmaschine** [comment]
@SebasSBM this seems like a strange solution, because both /django/contrib/admin/ and /grappelli/ are apps. so changing the order with ```STATICFILES_FINDERS``` shouldn't really change anything.

**Comment by dhbahr** [comment]
@sehmaschine it does shows up first (Grappelli's action.js that is). I'm thinking it might have been something with the browser cache solved when I `Ctrl+R`ed.
@SebasSBM as for me, I have no definition of the `STATICFILES_FINDERS` on my `settings.py`

**Comment by SebasSBM** [comment]
I discovered that setting by a casuality debugging the project I'm working on. Not all the global settings are included in a templateproject/settings.py, but any of the ones existing at <a target="_blank" href="https://github.com/SebasSBM/django/blob/master/django/conf/global_settings.py">django.conf.global_settings</a> can be overriden.

**Comment by dhbahr** [comment]
@SebasSBM I'm aware, I just wanted to point out that I didn't need to override it.

**Comment by SebasSBM** [comment]
I misunderstood you. Sorry.

You have a point. For some reason, this only happened to me.

I installed other external apps (filebrowser, modeltranslation) and one of the things I tried a few days ago is putting grappelli on top of INSTALLED_APPS tuple, just in case the others were interfering... But no, they weren't. I have no idea how could this happen.

For your information, I am doing the tests on a Virtual Machine, and I took some snaphots, so I can come back to an earlier state, in case some additional research is needed...

**Comment by SebasSBM** [comment]
@dhbahr When you say "I didn't need to override it", do you mean you have resolved your issue without that setting?

**Comment by dhbahr** [comment]
@SebasSBM Yes, as I said 5 comments earlier, seems to me my issue was really browser cache related, after hitting `Ctrl+R` it went away.

**Comment by SebasSBM** [comment]
@dhbahr Other sentence that I misunderstood... my apologies for the inconvenience.

**Comment by dhbahr** [comment]
@SebasSBM nevermind, best of lucks

**Comment by SebasSBM** [comment]
@dhbahr Thinking about it, how many times did I become crazy looking up for something that wasn't working, and then "oops, I forgot to clear cache"... xD. Best of lucks, as you said; it earns a lot of headaches.

@sehmaschine about this issue itself, I can go backwards to a previous snapshot, as I said before, for researching's sake. However, I am clueless about which direction to take... except for that I have notice reviewing my notes that I installed django-filebrowser==3.6.1 before django-grappelli==2.7.1. I will give it a try to install grappelli first, in a previous snapshot, to discard (or confirm) that django-filebrowser somehow interfered in the process. **I will EDIT this comment to post the result.**

**Comment by sehmaschine** [comment]
filebrowser doesn't interfere. what could interfere though is updating django (after installing grappelli).

that being said, I have no clue about which direction to take either. people already opened tickets about this topic – but soon afterwards, they closed it because of caching or setup issues. I'm glad if somebody is able to find out if this is a problem indeed and if it is related to grappelli.

**Comment by SebasSBM** [comment]
@sehmachine Well, then better I don't waste my time with filebrowser's idea...

I have thought about the dependencies I installed **after** grappelli - but I don't think they are interfering, due to grappelli is on top of INSTALLED_APPS:

    * Pillow==2.9.0
    * django-modeltranslation==0.10.1
    * django-tinymce==2.0.5

Maybe it is a Django issue, due to the problems that its STATICFILES system has. I don't know Django, neither the Grappelli app, to be sure about this though...

**Comment by sehmaschine** [comment]
@SebasSBM what do you mean by "external apps" vs "internal apps"? IMO there is no such difference, there are just apps.

**Comment by SebasSBM** [comment]
@sehmaschine By "internal apps", I meant those ones that were included in the Django project itself; and by "external apps" I meant those ones that didn't come with django by default. Might it be incorrect to call them this way?

In any case, the "hacky solution" (for the record: I call it like this on purpose because it was an ugly solution) is not necessary anymore. After fixing the mess I had in STATIC_ROOT, MEDIA_ROOT and STATICFILES_DIRS, **the ugly setting is not necessary anymore.**

What was said in <a target="_blank" href="https://github.com/sehmaschine/django-filebrowser/issues/286#issuecomment-143185855">the issue I opened in filebrowser</a> is related with this issue too. Same for <a target="_blank" href="https://github.com/sehmaschine/django-grappelli/issues/666">issue #666</a>. So, due to **this issue was caused by my own configuration errors**, I will close it inmediately.

THE MESS THAT CAUSED THIS (:-$):
This was my project's `settings.py` before opening this issue:
```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# PROJECT_DIR equals myproject/myproject
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

#Here are the messy settings that caused this issue
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
MEDIA_ROOT = os.path.join(BASE_DIR, 'myproject/') # <- Terrible mistake

# These two ones weren't necessary at all...
FILEBROWSER_DIRECTORY = "static/uploads/"
FILEBROWSER_VERSIONS_BASEDIR = "static/_versions"

# Desperate try due to "why the heck STATIC_ROOT files are not processed?"
STATICFILES_DIRS = (
       os.path.join(PROJECT_DIR, "static"),
)
```

Before opening this issue, I didn't understood correctly the difference between STATIC_* and MEDIA_* settings, not even the real purpose of STATIC_ROOT and STATICFILES_DIRS. So, for the sake of clarification, I will expose my fatal errors configuring my Django project:

**WHAT I THOUGHT I KNEW BEFORE:**
STATIC_ROOT = The folder where all static files must be (wrong!)
MEDIA_ROOT = Similar to STATIC_ROOT? Doesn't seem to be necessary (completely wrong!)
STATICFILES_DIRS = Additional directories in which detect static files (definetely wrong!)

**WHAT I "KNOW" NOW:**
STATIC_ROOT = The folder where all static files in the path contained in STATICFILES_DIRS and other Django apps will be collected into.
MEDIA_ROOT = All uploaded files must be included here! So, `uploads` and `_versions` directories must be here
STATICFILES_DIRS = Tuple of directories from which `python manage.py collectstatic` will copy static files into STATIC_ROOT folder.
