### ISSUE TITLE
Selecting Objects in admin not working for me on Django 1.8

### ISSUE THREAD

**Issue by dhbahr** [sehmaschine/django-grappelli#667]
I'm working on a Django 1.8 project and I wanted to try out Grappelli, but when listing objects selecting them to, say 'delete selected <model>s', the interface doesn't seem to notice that there are any entries selected. Also trying to select all by checking the box on the table header doesn't do anything either.

I'm I missing something? I'm new to Grappelli so it is possible that I missed out on something, I just can't seem to notice what that would be.

Best regards

**Comment by sehmaschine** [comment]
see #666 ... seems that your staticfiles are not loaded correctly (esp. actions.js).
