### ISSUE TITLE
django-solo incompatibility with hardcoded "../../../"

### ISSUE THREAD

**Issue by vinnyrose** [sehmaschine/django-grappelli#668]
#### Issue
In `grappelli/static/grappelli/js/jquery.grp_autocomplete_generic.js` and `grappelli/static/grappelli/js/jquery.grp_related_generic.js` within the `lookup_link` functions `"../../../"` is used to get back to `"/admin/"`. It assumes that the current url is of the form `"/admin/app/model/id/"`, but with django-solo (an app for using singletons in the admin) the url is `"/admin/app/model/"`.
#### Fix
This can be fixed by replacing `"../../../"` with `window.ADMIN_URL`. Which is defined in `grappelli/templates/admin/base.html`.
#### Questions
Is there a reason that `"../../../"` is being used besides what I assumed? Or is it safe to make the outlined change in a PR?

**Comment by sehmaschine** [comment]
just by looking at the code briefly this seems like a good change (no reason whatsoever for hardcoding these values).
