### ISSUE TITLE
TabularInline pagination?

### ISSUE THREAD

**Issue by theeluwin** [sehmaschine/django-grappelli#674]
related article: http://stackoverflow.com/questions/6664806/paginator-for-inline-models-in-django-admin
As you know, TabularInline's default behavior is like showing all the things that has to be shown. We need some kinda pagination.
I've succeed to merge [django-suit][1]'s [tabular_paginated][2] with this `django-grappelli` but having some trouble with making it useful enough to request PR.
How do you guys think about this?
It should looks like this:
![11111](https://cloud.githubusercontent.com/assets/1303549/10434899/584a9d24-7157-11e5-97cf-10b7ea1e98d4.png)

[1]: https://github.com/darklow/django-suit "django-suit"
[2]: https://github.com/darklow/django-suit/issues/65#issuecomment-29606850 "tabular_paginated"

**Comment by sehmaschine** [comment]
I'd use a separate modeadmin instead (with list_editables on the changelist). To be honest, I don't see how pagination with inlines could work ... are you able to show a demo?

**Comment by sehmaschine** [comment]
@theeluwin what exactly is the issue you are having with putting together a PR? do you have in mind that we need to deal with possible form errors on all the different sub-pages?

**Comment by theeluwin** [comment]
The problem is when there are too many items to show with tabular inline but.. I think it won't be an easy task. I'll try some more research myself. Sorry for bothering.

**Comment by sehmaschine** [comment]
closing this for now ... although it's an interesting topic. happy to take a look at a PR.
