### ISSUE TITLE
Intermediate Page for admin Interface

### ISSUE THREAD

**Issue by jonnymcgow7** [sehmaschine/django-grappelli#680]
This may be the completely wrong place to be asking this question, but I'm pretty new to django and I'm not really used to asking questions about these things so I wasn't really sure where to go.  Sorry if I'm in the wrong place!

So I've been working for a couple days now on setting up a pretty basic bulk edit action for my server that consists of selecting all of the objects you want to change a designated field on, being redirected to an intermediate page, entering a new integer value for the designated field, and then clicking accept to make the changes to all of the objects.  I used the bulk delete that comes pre-installed with all models as a template to make my action, form, and template for the intermediate page, and I don't get any errors, but when I submit my changes on the intermediate page, I'm redirected to the objects list page and my action is not run again.  

I'm not sure how to get the redirect from the template to correctly call my action after it returns, I've tried a lot of things and nothing seems to work.  I'll post the code and screenshots below:
## __my action definition:__
```
def change_min_interval(self, request, queryset):
    form = None
    opts = self.model._meta
    app_label = opts.app_label
    if not self.has_change_permission(request):
        raise PermissionDenied
    using = router.db_for_write(self.model)
    if 'apply' in request.POST:
        form = self.ChangeMinIntervalForm()
        if form.is_valid():
            new_interval = form.cleaned_data['new_interval']
            rows_updated = queryset.update(min_interval=new_interval)
            plural = ''
            if rows_updated != 1:
                plural = 's'

            self.message_user(request, "Successfully changed min_interval to %s on %d node%s." % (tag, count, plural))
        return None
    if len(queryset) == 1:
        objects_name = force_text(opts.verbose_name)
    else:
        objects_name = force_text(opts.verbose_name_plural)

    if not form:
        form = self.ChangeMinIntervalForm()

    context = dict(
        self.admin_site.each_context(request),
        app_label=app_label,
        title="Change min_interval",
        objects_name=objects_name,
        nodes=queryset,
        opts=opts,
        new_interval_form=form,
    )

    request.current_app = self.admin_site.name
    return TemplateResponse(request, 'admin/change_min_interval.html', context)
change_min_interval.short_description = "Change Minimum Interval"
```
## __my form definition:__
```
class ChangeMinIntervalForm(forms.Form):
        new_interval = forms.IntegerField()
```
## __my template definition:__
```
{% extends "admin/base_site.html" %}
{% load i18n admin_urls %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-min-interval-confirmation{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst|escape }}</a>

&rsaquo; {% trans 'Change min_interval' %}
</div>
{% endblock %}

{% block content %}

<p>Enter new minimum interval to apply:</p>

<form action="" method="post"> {% csrf_token %}
<div>
    {{ new_interval_form }}

    <p>The new minimum interval will be applied to:</p>

    <ul>{{ nodes|unordered_list }}</ul>

    <input type="hidden" name="action" value="change_min_interval" />
    <input type="submit" name="apply" value="{% trans "Apply Minimum Interval" %}" />
    <a href="#" onclick="window.history.back(); return false;" class="button cancel-link">Cancel</a>
</div>
</form>

{% endblock %}
```
## __screenshots:__
Selecting node to run the action on.
<img width="1314" alt="screen shot 2015-11-04 at 1 04 55 pm" src="https://cloud.githubusercontent.com/assets/8634916/10951938/f0e7cfc6-82f4-11e5-85e6-8b05bf605d63.png">
Selecting new min_interval for the node
<img width="312" alt="screen shot 2015-11-04 at 1 05 09 pm" src="https://cloud.githubusercontent.com/assets/8634916/10951941/f3ec4c38-82f4-11e5-8d6e-bf5c5bd2ef46.png">
Lack of results after submitting the form.
<img width="1324" alt="screen shot 2015-11-04 at 1 05 15 pm" src="https://cloud.githubusercontent.com/assets/8634916/10951942/f61ff950-82f4-11e5-95d1-bd2ba55008bd.png">
Shell outputs throughout this proccess.
<img width="500" alt="screen shot 2015-11-04 at 1 05 33 pm" src="https://cloud.githubusercontent.com/assets/8634916/10951945/f8526780-82f4-11e5-8881-8f94eb57b9cc.png">

**Comment by sehmaschine** [comment]
this is not related to grappelli, is it?
