### ISSUE TITLE
[QUESTION] Python 3 Support?

### ISSUE THREAD

**Issue by dhilipsiva** [sehmaschine/django-grappelli#682]
I work for @appknox. I porting our entire codebase to python3. Grappelli happens to be one of the dependency. I have currently forked this repo to [appknox/django-grappelli](https://github.com/appknox/django-grappelli) to port it to python 3 (without loosing support for python 2). 

Would you guys like PR after I have completed the port?

**Comment by sehmaschine** [comment]
grappelli is already working with python 3.4 for quite a while (see travis tests).
