### ISSUE TITLE
support Content-Security-Policy: default-src 'self'

### ISSUE THREAD

**Issue by graingert** [sehmaschine/django-grappelli#684]
There's a relatively new security feature in modern browsers to completely prevent XSS attacks, authors can simply set the header `Content-Security-Policy: default-src 'self'`.

Django [currently has a PR open](https://github.com/django/django/pull/5567) to make the django admin compliant with this header by removing all inline JS, HTML event handlers and `javascript:` URIs.

It would be great if we could duplicate this effort in Grappelli

**Comment by sehmaschine** [comment]
thanks. is that PR going to be part of django 1.9?

**Comment by graingert** [comment]
I think 1.9 is in feature freeze. I'd imagine this is going into 1.10

**Comment by sehmaschine** [comment]
I see ... how do you think we should handle this with grappelli? Wait until it's being implemented with Django or try to figure it out right now? Any preferences?

**Comment by graingert** [comment]
@sehmaschine it's not too hard to figure out now.

**Comment by sehmaschine** [comment]
@graingert just tried to use your patch, but I'm seeing lots of errors with my local setup (JS variables not defined etc). is this supposed to work?

**Comment by sehmaschine** [comment]
@graingert I've reverted the merge with stable/2.8.x ... there's just too many issues for me to resolve now (e.g. almost all paths are wrong, you use "grapelli" instead of "grappelli" etc). happy to take a look at this again if you're sending a tested PR.

**Comment by graingert** [comment]
Yeah sorry about that. Is there a document on how to run grapelli on an
example project?

**Comment by sehmaschine** [comment]
sorry, but I don't understand that question. you could just use it with any given project.

**Comment by sehmaschine** [comment]
closing this for now. please reopen with a new PR (thanks for your effort on this topic).

**Comment by atodorov** [comment]
@sehmaschine are you still open to receiving PRs about this issue? 

We've recently introduced CSP in our application and from what I can see grappelli is the biggest offender in our code base. I counted 50+ inline `<script>` tags in the current source code.

Since I don't think we use any specific grappelli functionality which may be implemented in JavaScript (other than Admin pages looking great) I'm thinking to start with some small changes to see how it goes. What do you think ?

**Comment by sehmaschine** [comment]
@atodorov Yes, I'm open to a PR. But how does introducing CSP with your application relate to Grappelli? We use CSP with all our apps, but never with the admin interface ...

**Comment by atodorov** [comment]
> @atodorov Yes, I'm open to a PR. But how does introducing CSP with your application relate to Grappelli? We use CSP with all our apps, but never with the admin interface ...

We configure the CSP headers unconditionally via nginx before the application which also causes all admin pages to be affected. I haven't checked whether or not we can make this conditional and whether that makes sense in our case or not.  Hence the need to modify grappelli.

**Comment by sehmaschine** [comment]
@atodorov I see, that makes sense – we use a different strategy so we usually don't run into this issue. However, I'm happy to take a look at a PR. But only if CSP is handled with the vanilla Django admin as well (otherwise, it does not make sense to integrate it with Grappelli IMO) ... is it?
