### ISSUE TITLE
Preserve filters feature is missing from Reversion templates

### ISSUE THREAD

**Issue by tdruez** [sehmaschine/django-grappelli#687]
@etianen 
In https://github.com/sehmaschine/django-grappelli/tree/master/grappelli/templates/reversion

See changes like https://github.com/sehmaschine/django-grappelli/commit/8fc84d83ca7acdfecafed236cf3a6172708bcae1 for example.

**Comment by sehmaschine** [comment]
@tdruez that issue should be addressed with django reversion first, right?

**Comment by etianen** [comment]
I'm afraid that I know very little about the preserve filters feature. I believe that it's part of the django core admin, and not just a Grappelli add-on? In that case, it certainly belongs in django-reversion too.

I'm not entirely sure what's involved to implement it, however. I'm happy to take a pull request if any changes are needed in reversion.

**Comment by sehmaschine** [comment]
yes, preserve filters is not related to grappelli. it's mainly about using the "add_preserved_filters" template tag with links.

**Comment by sehmaschine** [comment]
closing this for now since it's not mainly related to grappelli. once the reversion templates are updated, we'll take a look as well.
