### ISSUE TITLE
Error 'NoneType' object has no attribute 'get' when i try to load a custom admin

### ISSUE THREAD

**Issue by dhararon** [sehmaschine/django-grappelli#688]
Hi,
I'm trying to create my custom admin I'm currently using Django 1.8 and Grappelli 2.7.2

this is my custom admin
```python
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from grappelli.dashboard import modules, Dashboard
from grappelli.dashboard.utils import get_admin_site_name

class CustomIndexDashboard(Dashboard):
    def init_with_context(self, context):
       self.children.append(modules.ModelList(
            _('ModelList: Administration'),
            column=1,
            collapsible=False,
            models=('django.contrib.*',),
        ))
```

Just send error when I try ti load A ModelList or AppList

**Comment by sehmaschine** [comment]
should be fixed with master – can you give that a try?

**Comment by dhararon** [comment]
[Solved] I run "pip install -e git+https://github.com/sehmaschine/django-grappelli.git#egg=grappelli "  and everything it's ok.  thank you.

**Comment by sehmaschine** [comment]
@dhararon thanks! will do another release pretty soon.

**Comment by rstalbow** [comment]
I've had this error would be great to get 2.7.3 live asap.

**Comment by sehmaschine** [comment]
2.7.3 is out now
