### ISSUE TITLE
Doesn't work with django 1.9rc1.

### ISSUE THREAD

**Issue by Dharmik8478** [sehmaschine/django-grappelli#689]
While moving my app to django 1.9rc1 i am facing this problem with putting grappelli.dashboard in my settings.py, below is the error
>  raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by sehmaschine** [comment]
there's probably lots of errors with django 1.9 ... we'll deal with this once 1.9 is being released (see docs).

**Comment by debnet** [comment]
Django 1.9 out. ;)

**Comment by HWDexperte** [comment]
For the reference:  #678
