### ISSUE TITLE
  Error parsing template.

### ISSUE THREAD

**Issue by HellerCommaA** [sehmaschine/django-grappelli#691]
Hey all.

Currently hitting this error while trying to deploy a new version (with https://django-compressor.readthedocs.org/en/latest/usage/ on Django 1.8.3

`Error parsing template /opt/python/run/venv/local/lib/python2.7/site-packages/grappelli/dashboard/templates/grappelli/dashboard/dummy.html: Invalid template name in 'extends' tag: ''. Got this from the 'template' variable.`

**Comment by sehmaschine** [comment]
Is this a question or a bug report? Any details resp. debugging infos?

**Comment by HellerCommaA** [comment]
That's literally all the info I had from the AWS logs. I tried compressor with admin-bootstrap after I opened this ticket, I honestly think it's an issue with compressor, not with grappelli. I'll mark as closed.

**Comment by florianm** [comment]
I just ran into this exact error with `django-grappelli==3.0.4` when running `./manage.py compress --force --follow-links`. I have a somewhat unusual URL config stemming from my use of django-viewflow and django-material and my rudimentary understanding of these two packages' idosyncrasies may have broken something.

Without the time available to figure out the real cause of the error message, my patch is to create a file `templates//grappelli/dashboard/dummy.html` with the content

```
<!--
    This file fixes an error
    Error: "Invalid template name in 'extends' tag: ''. Got this from the 'template' variable."
    Our Grappelli dashboard has an attribute "template" which seems to be ignored here.
    Reproducible: ./manage.py compress --force --follow-links
    See https://github.com/sehmaschine/django-grappelli/issues/691
-->
{% extends "admin/index.html" %}
```

where the file `templates/admin/index.html` contains merely a fix for the missing favicon.
This patch should work with the stock `admin/index.html`.
```
{% extends "admin/app_index.html" %}
{% load static %}
{% block stylesheets %}
    {{ block.super }}
    <link rel="shortcut icon" href="{% static 'images/favicons/favicon.ico' %}">
    <link href="{% static 'css/grappelli_dashboard.css' %}" rel="stylesheet">
{% endblock %}
```
