### ISSUE TITLE
Inlines only displaying for superuser

### ISSUE THREAD

**Issue by mykljohn** [sehmaschine/django-grappelli#693]
I'm not sure if this is a grappelli issue, but I have 3 Stacked inlines:

class EvalEvaluationResponseInline(admin.StackedInline):
       model = EvaluationResponse
       verbose_name_plural = 'Questionnaire 1'
       inline_classes = ('grp-collapse grp-open',)
       form = EvaluationResponseform
       max_num=1
       extra = 1
class EvalEvaluationResponse2Inline(admin.StackedInline):
       model = EvaluationResponse2
       verbose_name_plural = 'Questionnaire 2'
       inline_classes = ('grp-collapse grp-closed',)
       form = EvaluationResponse2form
       max_num=1
       extra = 0
class EvalScoreInline(admin.StackedInline):
       model = EvaluationScore
       verbose_name_plural = 'Observations'
       inline_classes = ('grp-collapse grp-open',)
       max_num=1
       extra = 1
class EvaluationAdmin(admin.ModelAdmin):
        ('Scheduling Info',    {'fields': [('candidate',), ('evaluationdate',), ('user', ), ('status'), ('source'),]}),
        ("Questionnaire 1", {"classes": ("placeholder evaluationresponse_set-group",), "fields" : ()}),
        ("Questionnaire 2", {"classes": ("placeholder evaluationresponse2_set-group",), "fields" : ()}),
        ("Observations", {"classes": ("placeholder evaluationscore-group",), "fields" : ()}),
        ('Comments', {'fields': [('comments')]}),
        inlines = [EvalEvaluationResponseInline, EvalEvaluationResponse2Inline, EvalScoreInline]

They display properly only when the user is a Superuser.  If the user is not a Superuser, only the last inline displays, the other 2 are collapsed and can't be opened.  Any ideas why?

**Comment by sehmaschine** [comment]
no idea – but it should be straightforward to debug this issue. besides, please use the google-group for asking questions ... if you think this is a bug, please add some details.
