### ISSUE TITLE
autocomplete and autofocus

### ISSUE THREAD

**Issue by dahrens** [sehmaschine/django-grappelli#695]
VERSIONS: Grappelli 2.7.x, Django 1.8.x
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: NONE

When typing the full matching term into a autocomplete-field and hitting enter, your model gets saved, but the value is not saved because it is not yet set - you need to explicitly hit the option, when it gets responded by the ajax call.

This might be confusion for the user - he expects to value to be saved.

Maybe it is an option that [autoFocus](http://api.jqueryui.com/autocomplete/#option-autoFocus) is supported somehow.

Additionally: there is no visual feedback when using the keyboard to navigate through the possible options. 

EDIT: adds information described in contributing guideline...

**Comment by sehmaschine** [comment]
which version of grappelli are you using?

**Comment by dahrens** [comment]
had this issue with 2.7.1 and 2.7.2

**Comment by dahrens** [comment]
i played around with this a little...

Regarding the keyboard focus stuff it seemed as if there is just :hover on the inner a causing a different appearance - but :focus does nothing. The styles should comes from jquery-ui as those are used for styling.

The pull request adds autoFocus, so the first element gets focus and enter chooses it instead of saving the model (without changing the value)
