### ISSUE TITLE
Autocomplete does not appear to respect limit_choices_to when used with Q objects

### ISSUE THREAD

**Issue by dbinetti** [sehmaschine/django-grappelli#698]
Django 1.8.7, grappelli 2.7.2

I have a FK with `limit_choices_to` that uses a Q object for filtering.  This does not appear to be respected by Grappelli.

You will notice in the below that I tried a more usual dictionary lookup for the `limit_choices_to` param (currently commented), and the autocomplete respected that.  However, using the Q object returned the full set.  Also, disabling the autocomplete and using the normal Django pull-down also respected the Q object.  

```
# models.py
from model_utils.models import (
    TimeStampedModel,
)


class Common(TimeStampedModel):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    name = models.CharField(
        help_text="""
            The name of the resource.""",
        max_length=200,
        unique=True,
        validators=[
            validate_trimmed,
        ],
        error_messages={
            'unique': 'The name must be unique.  Add middle initials, suffixes, years, or other identifiers to make the name unique.',
        }
    )

    ...

    class Meta:
        abstract = True


class Person(Common):

    ...

    @staticmethod
    def autocomplete_search_fields():
            return ("id__iexact", "name__icontains",)


class Certification(TimeStampedModel):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    person = models.ForeignKey(
        'Person',
        related_name='certifications',
    )

    ...


class Judge(TimeStampedModel):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    ...

    person = models.ForeignKey(
        'Person',
        related_name='contests',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        # limit_choices_to={'kind': 2},
        limit_choices_to=models.Q(certifications__isnull=False),
    )


# admin.py
@admin.register(Judge)
class JudgeAdmin(admin.ModelAdmin):
    change_list_template = "admin/change_list_filter_sidebar.html"
    fields = [
        'name',
        ('status', 'status_monitor',),
        'contest',
        'person',
        'organization',
        ('category', 'slot',),
    ]

    ...

    raw_id_fields = (
        'contest',
        'person',
    )

    autocomplete_lookup_fields = {
        'fk': [
            'contest',
            'person',
        ]
    }
```

**Comment by dbinetti** [comment]
This may help, if I understand how autocomplete works.  (Well, it helps answer the question, but I'm still stuck I think...)

https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.limit_choices_to

> If limit_choices_to is or returns a Q object, which is useful for complex queries, then it will only have an effect on the choices available in the admin when the field is not listed in raw_id_fields in the ModelAdmin for the model.

**Comment by sehmaschine** [comment]
@dbinetti I think you answered your own question with the 2nd comment. We need to use raw_id_fields, because otherwise we do not get the related link we need to use the js autocomplete workaround. Not sure if we're able to solve this ... if you have an idea, please let me know.

**Comment by dbinetti** [comment]
Nope, no ideas.  Closing
