### ISSUE TITLE
[meta] Responsive css: Is anyone working on this already?

### ISSUE THREAD

**Issue by ninapavlich** [sehmaschine/django-grappelli#702]
Hello!

I'm interested in making Grappelli responsive and mobile-friendly. Is there anyone currently working on this?

If not, I've forked it here (https://github.com/ninapavlich/django-grappelli) and would be interested in collaborating with anyone that wants to help!

-Nina

**Comment by ninapavlich** [comment]
Oops -- I just saw the Google Group! Closing this question!

**Comment by olivierdalang** [comment]
@ninapavlich Hi, I couldn't find anything relevant on the google groups, and I'm very interested in a more mobile-friendly grappelli, and could probably contribute (even if I'm by no mean a css-specialist). Did you make any progress or findings on that matter ? (sorry for discussing here...)

**Comment by parsch** [comment]
Just to let you know: we're not working on that officially nor do we know about any contributors working on that.

**Comment by ninapavlich** [comment]
Hi @parsch, 

I emailed a little bit back in January with Patrick Kranzlmüller, and he mentioned that the developers would be discussing internally the future of the project and would be shooting to have a roadmap for this in March. 

He mentioned that on the table was whether or not to overhaul the look and feel entirely, and he suggested that it would make more sense to hold off on any efforts to make it responsive until that overhaul is underway. 

Whenever that is underway, you have have two volunteers (me and @olivierdalang) to help!

**Comment by olivierdalang** [comment]
@ninapavlich 
But without talking of the major overhaul, wouldn't there be a much shorter term strategy in "hacking" the css to make it a bit less unpractical on mobile devices ?

In particular, I think of some hardcoded widths that could probably relatively easily be removed, or dealing with the fixed header and footer that take up all the screen on smartphones.

I haven't spent time into this yet, and I'm a complete newbie to grappelli's CSS (and to css grids in general), so I may underestimate the complexity of it, but I can't believe we can't improve rendering on mobiles through a few well thought media queries.

**Comment by sehmaschine** [comment]
Hi @ninapavlich and @olivierdalang ... it's great that you both wanna help improving Grappelli (thanks!!!). Unfortunately, we are still not sure about the roadmap. Giving the current structure (e.g. inlines), it's very hard to make it work with mobile devices. Still thinking about a decent solution ...

Concerning "hacking" the CSS to make it a bit less unpractical: Our goal is to offer a good solution, not one which is "less unpractical". Therefore, I don't think that's the right way to go.
