### ISSUE TITLE
Password reset confirm form does not work

### ISSUE THREAD

**Issue by pista329** [sehmaschine/django-grappelli#703]
```
VERSIONS: Grappelli 2.7.2, Django 1.8.7
```
There's bug in template `grappelli/templates/registration/password_reset_confirm.html` that somehow has got in to master in commit https://github.com/sehmaschine/django-grappelli/commit/0061cbc1e70d15b5ea7620739f8a67f9dcd6817d see this [diff]( https://github.com/sehmaschine/django-grappelli/commit/0061cbc1e70d15b5ea7620739f8a67f9dcd6817d#diff-729d062a7a1a1183501a6a02a61d8146L9) 

Logic for showing password reset form should be reveresed. Otherwise password reset form will never show.
`{% if not validlink %}` should be `{% if validlink %}`

Thanks.

**Comment by parsch** [comment]
@pista329 oops, thanks for reporting, fixed it.
