### ISSUE TITLE
Is there a native grappelli dashboard, compatible with Django 1.9 new layout?

### ISSUE THREAD

**Issue by dbykadorov** [sehmaschine/django-grappelli#710]
For now I copied admin/base_site.html and admin/base.html from django.contrib.admin to make my dashbord looks like native Django 1.9 admin, but dashboard itself not compatible with new layout:

http://prntscr.com/9nigf9

**Comment by sehmaschine** [comment]
sorry, I don't understand your question ... grappelli is not yet compatible with django 1.9. besides, please use the google-group for asking questions.

**Comment by dbykadorov** [comment]
I see that it is not compatible, but I want to know wether the fix is planned or not?

**Comment by sehmaschine** [comment]
Compatibility with Django 1.9 is planned. And grappelli has a dashboard ... but I still don't understand the question.

**Comment by dbykadorov** [comment]
The question was about exists layouts compatible with Django 1.9 (maybe I miss them). Your answer is "Not yet".

I was planed upgrade of some old projects using grappelli to Django 1.9 and also I need to start new project with Django 1.9. 

Currently I need to postpone the upgrade and in the new project I'll not use grappelli before it will be compatible with Django 1.9.

Thanks for your answer!
