### ISSUE TITLE
undefinedimg/icon-unknown.gif in Django 1.9 (many to many field widget)

### ISSUE THREAD

**Issue by dvkovner** [sehmaschine/django-grappelli#712]
Good day! I use django-grappelli in my application based on django 1.9. After updating from django 1.7 to 1.9 I began to receive http 404 error messages in console of my development server. This message is appear when i open any model containing many to many field for editing. I found that this error is related to "icon-unknown.gif" file. This icon is used for indicating help message in header of many to many field widget. In django 1.9 this file does not exist at all. It is replaced by .svg file. Also <image> tag corresponding to this file is not showing at all because of its "display: none;" css property. Moreover the value of "src" attribute of this tag is "undefinedimg/icon-unknown.gif". This is computed by "admin_static_prefix + 'img/icon-unknown.gif'" in "grappelli\static\admin\js\SelectFilter2.js". I think admin_static_prefix is computed to "undefined" in django 1.9. In django 1.8 and 1.7 the path to image is computed properly. (tested today) I think the link of image should be fixed or image should be removed at all.

P.S. Sorry for my english =)

![image](https://cloud.githubusercontent.com/assets/13110972/12256406/975bb3d4-b948-11e5-89ea-81a1aa326748.jpg)

**Comment by sehmaschine** [comment]
you know that the current release is not compatible with django 1.9, right?

**Comment by dvkovner** [comment]
Yes. I think it is better to say than to remain silent. =)

**Comment by sehmaschine** [comment]
see #714
