### ISSUE TITLE
Related Lookup popup window not well-supported on mobile browsers

### ISSUE THREAD

**Issue by trevoriancox** [sehmaschine/django-grappelli#713]
My Django admin site is used much of the time from an iPad or other tablet. Mobile browsers may not support popup windows. Related/autocomplete lookup uses window.open() to open a child window. On iOS/Safari, this opens a new tab, but it still works - you can choose an item. With iOS/Chrome, I don't think you can make a selection successfully.

Even on the desktop, we're risking popup blocker issues.

As a simpler solution than a full AJAX rewrite, perhaps a jQueryUI dialog that contains an IFRAME? The IFRAME could load the popup page using the same URL as the popup has today.

**Comment by sehmaschine** [comment]
these are issues with django.contrib.admin, not grappelli ... right?

**Comment by trevoriancox** [comment]
Sorry, yup. Tho imho django's raw_id_fields are useless w/o grappelli. :)
