### ISSUE TITLE
Adding of related object through pop up window

### ISSUE THREAD

**Issue by dvkovner** [sehmaschine/django-grappelli#717]
Hello. I use grappelli (2.7.3) in my django (1.9) application. After adding of new object  in a popup window ('plus' icon) i cant save form immediatly if new object is selected. It seems that <option> tag of added element has attribute "value=""". This value is incorrect foreign key of object. I think it's django 1.9 compatibility issue. In django 1.8.3 with grappelli 2.7.1 all works fine.
![bug](https://cloud.githubusercontent.com/assets/13110972/12391992/5c6bd210-be37-11e5-9379-1d3ce4e47eb4.png)

**Comment by sehmaschine** [comment]
grappelli 2.7 is not compatible with django 1.9. use grappelli 2.8 and reopen this ticket, if the problem still exists.

**Comment by dvkovner** [comment]
I have the same issue in grappelli 2.8.1.

**Comment by gb119** [comment]
Possibly related, the search window popup for a generic foreign key from appA to appB/modelB is giving an unmatched url (of the form /admin/appA/appB/model/?&_popup=1 ). This is with current git stable/2.8.x branch and django-1.9.2

**Comment by maffacow** [comment]
I can verify this also with grp 2.8.1 and Django 1.9.2
Thanks

**Comment by sehmaschine** [comment]
tested with stable/2.8.x and master ... works for me (might be related to the last commit which fixed popup_response.html). so please give this a try again and reopen if the bug still exists.
