### ISSUE TITLE
Wrong file name ../../admin/img/icon_deletelink.svg

### ISSUE THREAD

**Issue by PaoloC68** [sehmaschine/django-grappelli#721]
VERSIONS: Grappelli 2.8.x, Django 1.9

as i explain here https://github.com/sehmaschine/django-grappelli/commit/9304dca1de244a1ad0b080cc157d6f5cc96a5e3c there is no file `../../admin/img/icon_deletelink.svg` but instead a file `../../admin/img/icon-deletelink.svg` is there to be found

https://github.com/django/django/blob/1.9.1/django/contrib/admin/static/admin/img/icon-deletelink.svg

**Comment by parsch** [comment]
Thanks for reporting & fixing it!
