### ISSUE TITLE
GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS doesn't take effect

### ISSUE THREAD

**Issue by garyelephant** [sehmaschine/django-grappelli#723]
GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS doesn't take effect when I set it ni settings.py,
but the following code works as expected:

```
    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "name__icontains",)
```

**Comment by tdruez** [comment]
Could you provide the value assigned to GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS?

**Comment by sehmaschine** [comment]
@garyelephant closing this for now – please reopen with additional information in order to reproduce this.
