### ISSUE TITLE
filter_horizontal and filter_vertical issue

### ISSUE THREAD

**Issue by mehdipourfar** [sehmaschine/django-grappelli#724]
when I use filter_horizontal, I can't select any item in the boxes, but by disabling max width of the hint about "press ctrl or cmd key on the mac", I'll be able to do that.

![2016-02-06 12 55 16](https://cloud.githubusercontent.com/assets/13090047/12865976/bebcbff2-ccd2-11e5-9c0f-4982d05c5058.png)

**Comment by mehdipourfar** [comment]
I think I was wrong. The problem is that you should change clear value of grp-help class to right in your rtl.css
I'm waiting for fix.

**Comment by mehdipourfar** [comment]
And also, those horizontal selectors work inverse for rtl, because the position of  selector-chosen divs will be reversed. I hope you fix that too.

**Comment by parsch** [comment]
Thanks for reporting, fixed in stable 2.7.x and 2.8.x branches
