### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by ivanscm** [sehmaschine/django-grappelli#725]
SyntaxError: expected expression, got '&'
allowedExtensions: [&#39;.mp3&#39;, &#39;.mp4&#39;, &#39;.wav&#39;, &#39;.aiff&

**Comment by michalwerner** [comment]
I had similar issue, but it was related with django-filebrowser, not grappelli ([fix](https://github.com/sehmaschine/django-filebrowser/pull/300)).
