### ISSUE TITLE
Recent actions box overflowing on long text

### ISSUE THREAD

**Issue by AndreMiras** [sehmaschine/django-grappelli#730]
VERSIONS: django-grappelli==2.7.3, Django==1.8.7
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: NONE

This is the exact same as upstream [admin: prevent long text from overflowing recent actions box](https://code.djangoproject.com/ticket/14868).
When the item text is too long in the "Recent Actions" box, it overflows its container, see screenshot.
![grappelli_recention_actions_overflow](https://cloud.githubusercontent.com/assets/24973/13253370/065df63e-da3c-11e5-83e4-c7a562207004.png)

However this problem doesn't appear without Grappelli as it was fixed in [upstream #14868](https://code.djangoproject.com/ticket/14868), see screenshot.
![mainstream_recention_actions_nooverflow](https://cloud.githubusercontent.com/assets/24973/13253402/29dcdd96-da3c-11e5-83f3-2703ccd86b89.png)

I'm currently fixing the issue by using a custom template in templates/admin/base_site.html with the following code:

```
{% extends 'admin/base.html' %}
{% load admin_static %}
{% block extrastyle %}
<style>
/* "Recent Actions" long text overflow in Grappelli */
ul.grp-listing-small li a {
overflow: hidden;
text-overflow: ellipsis;
-o-text-overflow: ellipsis;
}
</style>
{% endblock %}
```

**Comment by sehmaschine** [comment]
@parsch please take a look at this one and fix with stable/2.7.x, stable/2.8.x and (upcoming) stable/2.9.x
