### ISSUE TITLE
GRAPPELLI_ADMIN_TITLE no longer allows HTML

### ISSUE THREAD

**Issue by maffacow** [sehmaschine/django-grappelli#732]
I have just started my first project in Django 1.9

In <= 1.7 I was able to place HTML within the admin title which allowed me to put the name of the site along with my contact details.

Not sure if this is an issue with Grappelli or Django itself.

**Comment by sehmaschine** [comment]
I don't think that HTML with the admin title has ever been possible ... but if you're able to give me a hint on the specific commit, I'm happy to check this issue.

**Comment by maffacow** [comment]
Hi there and thanks for looking into this.

Ok, so as basic test in a Django 1.7 running Grappelli==2.6.5
`GRAPPELLI_ADMIN_TITLE = '<a href="#">This is a hyperlink</a>'`

produces the following. It always has back since Django 1.4 which is where I started using your Grappelli Module (fantastic by the way)

![screen shot 2016-02-26 at 17 23 07](https://cloud.githubusercontent.com/assets/2813210/13359861/15d5cf32-dcae-11e5-9ba3-111ae1b8e053.png)


The next screenshot is Django 1.9 with the very latest Grappelli

![screen shot 2016-02-26 at 17 27 40](https://cloud.githubusercontent.com/assets/2813210/13359889/46166bca-dcae-11e5-9529-ebc6ab0cde1f.png)

This has always allowed me to add a little custom branding with my contact details etc

Keep up the good work

**Comment by sehmaschine** [comment]
see https://github.com/sehmaschine/django-grappelli/blob/stable/2.6.x/grappelli/templates/admin/base.html#L78

are you sure that you did not use a custom template?

**Comment by maffacow** [comment]
Maybe it is Django itself which has changed.

I found a work around using:

from django.utils.safestring import mark_safe
GRAPPELLI_ADMIN_TITLE = mark_safe(myHTML)

**Comment by sehmaschine** [comment]
I don't get how this could be affected by Django itself. But I guess I have to give up here (not able to understand/reproduce this issue). Feel free to reopen with additional details (a PR would be useful).
