### ISSUE TITLE
actions.min.js

### ISSUE THREAD

**Issue by stas630** [sehmaschine/django-grappelli#733]
After commit b90fec24 in file actions.min.js. Action select box doesn't working. But in debug mode use  file actions.js is working!!

**Comment by sehmaschine** [comment]
What do you mean with "not working"? There's now a GO-Button to submit an action.

**Comment by stas630** [comment]
If select value in select-box "Delete selected...", 
When I select a value "Delete selected..." in the select-box, then nothing happens (settings.DEBUG=False, use actions.min.js).
When I select a value "Delete selected..." in the select-box, java-script runs and deletes (settings.DEBUG=True, use actions.js).
File actions.min.js and actions.js are different in your project.
I use: Django (1.9.2) django-grappelli (master)

**Comment by sehmaschine** [comment]
should be fixed now.
