### ISSUE TITLE
Can't see the top of the grp-content div

### ISSUE THREAD

**Issue by NickCliff** [sehmaschine/django-grappelli#735]
Hey Guys,

Have just tried my first install and it all seems to have worked except this one css bug (possible that it's specific to my install as I can't find anything about it online)

The #grp-content{top: 80px} is way to high and the banner is covering it as can be seen here, on other pages it also covers the "add <item>" button

![grappelli-css](https://cloud.githubusercontent.com/assets/1989595/13415381/59f0d308-dfae-11e5-96a3-67d7d928ec02.png)

Updating top to 115px fixes this as below

![grappelli-fixed-css](https://cloud.githubusercontent.com/assets/1989595/13415382/5b1f2658-dfae-11e5-8af1-7a5302cdb91b.png)

Using 
- Django 1.9.2
- Grappelli 2.7.3

**Comment by parsch** [comment]
Please note that Grappelli 2.7.3 is not compatible with Django 1.9, you should use the 2.8 development branch (https://github.com/sehmaschine/django-grappelli#releases)

Furthermore the height works well in my environment but you're talking about an "add" button – do you have any customizations implemented?

**Comment by NickCliff** [comment]
The add button for example "add user" on other pages.

No I have no customizations implemented. I'll upgrade our grappelli version in a few hours and see if that fixes the height.

**Comment by sehmaschine** [comment]
I'm closing this since 2.7.3 is not compatible with Django 1.9. If the problem still exists with 2.8.x, please reopen this ticket.

**Comment by NickCliff** [comment]
No problem.

**Comment by jqsjqs** [comment]
https://github.com/sehmaschine/django-grappelli/issues/758
