### ISSUE TITLE
Update django version on PyPI

### ISSUE THREAD

**Issue by wjakob** [sehmaschine/django-grappelli#736]
The versions of grappelli on PyPI are really outdated, which makes it impossible to install a working setup for Django 1.9.x
```
 % pip install django-grappelli==2.8.1
Collecting django-grappelli==2.8.1
  Could not find a version that satisfies the requirement django-grappelli==2.8.1 (from versions: 1.3, 2.1, 2.1.1, 2.2, 2.3, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.4.10, 2.4.11, 2.4.12, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.1, 2.7.2, 2.7.3)
No matching distribution found for django-grappelli==2.8.1
```
Would it be possible to upload a more recent release?

**Comment by sehmaschine** [comment]
2.8.1 is still under development and there hasn't been a lot of feedback so far. but I see your point and I'll do a release later today (but please be aware that this version isn't fully tested).

**Comment by wjakob** [comment]
I've been using master from this repository in the meantime, and it works perfectly.

**Comment by sehmaschine** [comment]
alright – that's good to know.

**Comment by jieter** [comment]
For what it's worth: master works great with Django 1.9 for me too. Shouldn't we have more automatic testing, maybe something using selenium?
