### ISSUE TITLE
filter_horizontal not aligned box

### ISSUE THREAD

**Issue by mrJungle** [sehmaschine/django-grappelli#737]
in new 2.8.1 on dj 1.9.x found this problem of alignment (biggest issue regard the first record of the "selector-available" box is not readable) 

![issue_grappelli](https://cloud.githubusercontent.com/assets/948342/13578612/4a132bee-e499-11e5-9f2f-f459703bafd2.png)
 
for the sake of simplicity I fix it changing size on screen.css 

1 - shifted box
.selector{position:relative;float:left;overflow:hidden;width:758px}
>>
.selector{position:relative;float:left;overflow:hidden;width:768px}

2 - unredable first line
.selector .selector-filter input[type=text]{position:relative;margin:0;width:326px !important;max-width:326px !important}
>>
.selector .selector-filter input[type=text]{position:relative;margin:0;width:295px !important;max-width:295px !important}

 
i'm sure there are a better way, but i leave this up to u
best regards

Davide

**Comment by Quantra** [comment]
1.  I am unable to recreate.

2.  Exists in IE11 and Firefox.  This issue is making the admin site unusable in these cases.  Patch please!
