### ISSUE TITLE
Constance template does not support Django 1.9 svg icons

### ISSUE THREAD

**Issue by utapyngo** [sehmaschine/django-grappelli#740]
VERSIONS: Grappelli 2.8.1, Django 1.9, django-constance 1.1.2

![084_selection](https://cloud.githubusercontent.com/assets/1124655/13918790/a77a53fc-ef93-11e5-8a81-3eccf675373b.png)

    <img src="{{ STATIC_URL }}admin/img/icon-{% if item.modified %}yes{% else %}no{% endif %}.gif" alt="{{ item.modified }}" />

should be changed to

    {% if item.modified %}
        <img src="{% static 'admin/img/icon-yes.'|add:icon_type %}" alt="{{ item.modified }}" />
    {% else %}
        <img src="{% static 'admin/img/icon-no.'|add:icon_type %}" alt="{{ item.modified }}" />
    {% endif %}

**Comment by parsch** [comment]
Implemented suggested changes (didn't test them).

**Comment by izqs** [comment]
I don't see a commit.

**Comment by utapyngo** [comment]
> Invalid block tag on line 110: 'static', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
