### ISSUE TITLE
Remove Multiple IDs

### ISSUE THREAD

**Issue by jpotterm** [sehmaschine/django-grappelli#741]
Currently in `grappelli/templates/admin/base.html` there is an element with multiple IDs:

```
<div id="container grp-container">
```

I'm not sure whether this is legal according to the spec, but in Chrome and Firefox this prevents either ID from being used in CSS or JavaScript selectors. See [demo](http://codepen.io/anon/pen/EKmPZr).

Can you only use one ID, or use classes instead?

**Comment by jpotterm** [comment]
This regression was introduced in commit c43288f840457945e7ca4636715f87d1474fd48e.

**Comment by parsch** [comment]
Thanks for reporting. I defined ```grp-container``` as class using ```container``` as only ID (providing compatibility, see #494).

**Comment by mick-t** [comment]
Will there be a tagged django-grappelli branch with this fix? django-grappelli==2.7.3 still has this problem.

**Comment by sehmaschine** [comment]
It's in 2.8.1 (for example).

**Comment by mick-t** [comment]
I'm using Django 1.8.x and the django-grappelli docs say to use the 1.7 branch. I won't be upgrading to Django 1.9 as I want to stick to 1.8 as it's classed as a long-term support (LTS) release with support for the next 3 years.

**Comment by sehmaschine** [comment]
I see. We'll think about doing a 2.7 release with this fix included. Unfortunately, we are not able to add  LTS comparable to django (we just don't have the necessary ressources).

Besides, we don't say to use the 1.7 branch. First, this branch doesn't exist. Second, we refer to releases (not branches).

**Comment by sehmaschine** [comment]
We decided to not release a new version for 2.7, but you can use the branch stable/2.7.x instead.
