### ISSUE TITLE
Constance template is broken (missing {% load static %})

### ISSUE THREAD

**Issue by utapyngo** [sehmaschine/django-grappelli#742]
VERSIONS: 
- Grappelli 2.8.1 from GitHub (commit https://github.com/sehmaschine/django-grappelli/commit/13c827565acc76c827c1d2b135480bc5aa26bbcc, latest in the stable/2.8.x branch)
- Django 1.9
- django-constance 1.1.2

Trying to open the constance config page leads to the following exception:

> Invalid block tag on line 110: 'static', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?

**Comment by parsch** [comment]
@utapyngo As I'm not able to set up constance right now: can you please check if adding ```{% load static %}``` solves the problem or if there are further requirements (we're usually using a ```{{ STATIC_URL }}```). Happy to integrate it then.

**Comment by utapyngo** [comment]
Yes, I have changed the LOADING section to `{% load admin_list i18n grp_tags admin_urls static %}`, and it works. Thanks!

**Comment by parsch** [comment]
Thank you.
