### ISSUE TITLE
Template Documentation

### ISSUE THREAD

**Issue by dco5** [sehmaschine/django-grappelli#744]
How can I see the documentation if the urls for the documentation are commented? How do I enable them? I try uncommenting them but it just gave me a whole bunch of errors.

**Comment by sehmaschine** [comment]
what do you plan to do with these docs? I'm not sure they are up-to-date.

**Comment by dco5** [comment]
I need to create a custom admin view for a custom admin action. I need it too look and feel like still inside the admin.

**Comment by sehmaschine** [comment]
that makes sense ... you could just copy/paste the URLs to your own urls.py (or outcomment them with grappelli).
