### ISSUE TITLE
Tests throw a ProgrammingError

### ISSUE THREAD

**Issue by paolostefan** [sehmaschine/django-grappelli#747]
VERSIONS: Grappelli 2.8.1, Django 1.9.5
STATICFILES: OK
JAVASCRIPTS: OK (not relevant)
CUSTOMIZATIONS: Custom user model, without "is_staff" field

The command:

`./manage.py test grappelli.tests -v2`

always throws the following error: 

`django.db.utils.ProgrammingError: relation "users_mycustomuser" does not exist`

The error happens after these output lines:

```
  Creating tables...
    Creating table grappelli_category
    Creating table grappelli_entry
    Creating table corsheaders_corsmodel
    Running deferred SQL...
Traceback (most recent call last):
```
My own apps' tests are running fine (so I think it's a problem with Grappelli). Anyway, the admin interface works just fine. I found out this issue after I tried to activate GRAPPELLI_SWITCH_USER, which threw an error itself and refused to work (so, I ran the tests which failed).

My `pip freeze`:
```
Django==1.9.5
django-allauth==0.24.1
django-braces==1.8.1
django-cors-headers==1.1.0
django-countries==3.4.1
django-debug-toolbar==1.4
django-filter==0.11.0
django-friendship==1.3.1
django-grappelli==2.8.1
django-hvad==1.4.0
django-rest-auth==0.7.0
djangorestframework==3.3.3
djangorestframework-gis==0.10
ecdsa==0.13
Fabric==1.10.2
oauthlib==1.0.3
paramiko==1.16.0
Pillow==3.1.1
psycopg2==2.6.1
pycrypto==2.6.1
python-openid==2.2.5
PyYAML==3.11
requests==2.8.1
requests-oauthlib==0.5.0
six==1.10.0
sqlparse==0.1.18
```

**Comment by sehmaschine** [comment]
according to the error `relation "users_mycustomuser" does not exist` it is definitely not related to grappelli.

**Comment by paolostefan** [comment]
Ok, seems like that but I'm opening another issue to explain what I meant.
