### ISSUE TITLE
GRAPPELLI_SWITCH_USER throws FieldError with custom user model

### ISSUE THREAD

**Issue by paolostefan** [sehmaschine/django-grappelli#748]
VERSIONS: Grappelli 2.8.1, Django 1.9.5
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: user model

I want to use the 'switch user' with a custom user model. When I add this setting:

`GRAPPELLI_SWITCH_USER=True`

it throws an error like this:

> FieldError at /admin/myuser/customuser/
> Cannot resolve keyword 'is_staff' into field. Choices are: customgroup, date_of_birth, email, first_name, groups, groups_owned, id, is_active, is_admin, last_login, last_name, logentry, password, subscribed_on, username

Without this setting, the admin area works just fine but **the tests fail**.

# Steps to reproduce the issue

1. in a "clean" virtualenv, install Django (1.9.5, as of today) and Grappelli (2.8.1) and start a new Django project;
3. within the new project create an app, e.g. `python manage.py startapp customuser`
4. edit customuser/models.py like [this Gist](https://gist.github.com/paolostefan/59a3b683ddd4f793e6a031bfdb8e068a)
5. edit customuser/admin.py like [this Gist](https://gist.github.com/paolostefan/0df2a90e598e610d362859f260588d9e)
6. add `customuser` and `grappelli` to INSTALLED_APPS;
7. add these lines to the default `setting.py`:
```
STATIC_ROOT = 'www/'
SITE_ID = 1
AUTH_USER_MODEL = 'customuser.CustomUser'
GRAPPELLI_SWITCH_USER = True
```
8. run `python manage.py makemigrations`, `python manage.py migrate` and `python manage.py collectstatic`
9. try `python manage.py test grappelli.tests` and/or adding `GRAPPELLI_SWITCH_USER=True`
to the settings.

**Comment by sehmaschine** [comment]
again, this is not a grappelli issue. you cannot use a custom user model without admin attributes (e.g. is_staff) for admin-related features.

**Comment by paolostefan** [comment]
Can you elaborate a bit?
Do you mean that a custom user model will break tests programmatically?
Switch won't be possible at all with a custom user model?
Is there a place where these "do and don't"s are documented?

Anyway, the model _has_ the property `is_staff` defined in https://gist.github.com/paolostefan/59a3b683ddd4f793e6a031bfdb8e068a#file-models-py-L89
do you mean that is_staff has to be defined as a _field_ (as opposed to a _property_)?

Thank you.

**Comment by sehmaschine** [comment]
> Do you mean that a custom user model will break tests programmatically?
Not necessarily. It depends on the customization, but we are not able to foresee every possible case.

> Switch won't be possible at all with a custom user model?
Depends on the customization. You can check the function `switch_user` for details.

> Is there a place where these "do and don't"s are documented?
No. But if you find something which should be documented, we'll integrate it ... or (even better) you send a PR with the updated docs.

Generally speaking, it should be easy for you to figure out what's wrong. You can than either send a PR with the updated code (if tests are included, a merge is easier) or docs or you give us a hint on what we can/should do.
