### ISSUE TITLE
grp-content-title underneath grp-context-navigation

### ISSUE THREAD

**Issue by kierun** [sehmaschine/django-grappelli#752]
The div `grp-content-title` appears to be hidden underneath the `grp-context-navigation` one.  This means that the "Add" button (for example) is hidden.

Here is a screen shot:

![untitled](https://cloud.githubusercontent.com/assets/3079575/15012312/a366b28c-11ef-11e6-81e3-3b52d667e5d2.png)

**Comment by sehmaschine** [comment]
it seems like you're using a custom header, right?

**Comment by kierun** [comment]
Not as far as I am aware but I could be... I am pretty new to Django. I am using `django-revision` as well if that impacts things...

**Comment by sehmaschine** [comment]
no issue with ``django-reversion``, but your screenshot definitely shows a header with a custom height.

**Comment by kierun** [comment]
Hum... Any idea where my broken setup got broken?... (Yeah, you can mock me for asking.)

**Comment by sehmaschine** [comment]
no, sorry. but check for your header "Isotek ..." within your code.

**Comment by kierun** [comment]
hum... I'll keep digging.  Many thanks indeed.

**Comment by kierun** [comment]
`templates/admin/base_site.html` was the culprit in case this bugs anyone else.
