### ISSUE TITLE
"view on site" redirection error

### ISSUE THREAD

**Issue by extremewaysback** [sehmaschine/django-grappelli#754]
I am a green on django-grappelli.
Here is the issue: I write a post in my admin site in django and want to have a preview of it with the **view on site** button. But it redirect to the address like **http://https//origint.herokuapp.com/blog/2016/05/12/color-coded-parallel-coordinates-plot/**. And the correct address is **https://origint.herokuapp.com/blog/2016/05/12/color-coded-parallel-coordinates-plot/**. I don't what is wrong with this issue. It would be very appreciated if anyone can give me a tip.

![screen shot 2016-05-15 at 11 11 57 am](https://cloud.githubusercontent.com/assets/13831728/15271837/3bed782c-1a8f-11e6-833e-2d0755ceecda.png)

**Comment by sehmaschine** [comment]
please check if this happens without grappelli as well (I assume it's not related to grappelli). you could also use the google-group for asking questions.

**Comment by extremewaysback** [comment]
@sehmaschine Thanks!
