### ISSUE TITLE
Django 1.8.13 and python 3.5.1

### ISSUE THREAD

**Issue by kitex** [sehmaschine/django-grappelli#758]
I successfully installed grappelli and I can see the skin but the header as in picture is extended. How do I fix it? The text hides behind header.
![capture](https://cloud.githubusercontent.com/assets/7269068/15882307/20017f56-2d5d-11e6-8571-4735f053c180.PNG)

**Comment by parsch** [comment]
see #752

**Comment by kitex** [comment]
![capture](https://cloud.githubusercontent.com/assets/7269068/15884914/3b839050-2d73-11e6-9d3e-d19feca8d1ec.PNG)

I don't have any customer header.

**Comment by kitex** [comment]
I removed 

<h1 id="site-name"><a href="{% url 'admin:index' %}">CMDB</a></h1>

 from 
templates/admin/base_site.html

**Comment by parsch** [comment]
So you did define ```<h1 id="site-name"><a href="{% url 'admin:index' %}">CMDB</a></h1>``` in templates/admin/base_site.html?

If yes, you end up with two ```<h1>``` (not a good thing) and of course you have to apply styles to your custom heading.

If no, please let me know where this ```<h1 id="site-name">``` might come from, I can't reproduce it.

**Comment by kitex** [comment]
Yes I defined it. So grappelli provides the other one?

**Comment by parsch** [comment]
Yes, maybe that's not very clear that you shouldn't use ```<h1 id="site-name">```.
Using the ```{% block branding %}``` you can define/insert whatever you want, of course you have to take care about the styles on your on behalf. As suggested in the comment of ```{% block branding %}``` you can use ```<div id="grp-branding">``` as a container for a logo or whatsoever, it's positioned correctly. But you will have to apply some styles on your own, too, as there's no way to guess how people use the branding block.

**Comment by kitex** [comment]
Thank you parsch! Is there any document regarding this?

**Comment by jqsjqs** [comment]
Just so you know where this is coming from and why multiple people are reporting it, if you follow the Django tutorial, it's one of the things you add. Given there's a straight path between that tutorial and this bug, you might want to raise this to the level of the FAQ or something.

https://docs.djangoproject.com/en/2.2/intro/tutorial07/#customizing-your-project-s-templates
