### ISSUE TITLE
[problem] Filter in 2.7.3

### ISSUE THREAD

**Issue by mykljohn** [sehmaschine/django-grappelli#759]
I just upgraded to 2.7.3 from 2.7.1 and my filter stopped working.  I get a javascript error:
(index):63 Uncaught TypeError: $(...).actions is not a function

![image](https://cloud.githubusercontent.com/assets/11919990/15981774/0b20645a-2f40-11e6-95d4-b4268add4b91.png)

**Comment by mykljohn** [comment]
@sehmaschine  @myii 

I kind of confused and stuck here. 
I went through the steps in Filter functionality on admin pages don't work unless actions = None on ModelAdmins #214, and /mysite/static/admin/js/jquery.init.js is:

// dropped
// not used in grappelli
// kept this file to prevent 404

but in devtools it still shows:
// Puts the included jQuery into our own namespace
var django = {
    "jQuery": jQuery.noConflict(true)
};

I've done a hard refresh <ctrl><f5> to clear cache and reload (correct?) but to no avail.
I even went to /files/home/geeval/.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js and changed it to:

// dropped
// not used in grappelli
// kept this file to prevent 404

But it still shows as original...it definitely appears to be a caching issue, so I rebooted and it still shows the same.   

I additionally tried staticfile finder (which really doesn't make sense because it's the default anyway)

STATICFILES_FINDERS = (
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
'django.contrib.staticfiles.finders.FileSystemFinder',
)

I've tried in both Chrome and Firefox (on win10)

My versions are:
python (2.7)
django (1.8.6)
django-grappelli (2.7.3)

my installed apps, middleware and static in settings.py are:
INSTALLED_APPS = (
    'django.contrib.contenttypes',
    'grappelli.dashboard',
    'grappelli',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_spaghetti',
    'django_tables2',
    'eval',
    'mail_templated',
    'multiselectfield',
    'ckeditor',
    'explorer',
    'model_report',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

STATIC_ROOT = "/home/myapp/mysite/static/"

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    "/home/myapp/mysite/eval/static/eval/",
    "/home/myapp/mysite/static"
)

**Comment by myii** [comment]
@mykljohn 

I've run into this problem a number of times and I am definite that the issue lies between `collectstatic` and the configuration of your web server for serving static files.  You didn't mention either of these above and it would help if you could explain these further.

> but in devtools it still shows:
> // Puts the included jQuery into our own namespace
> var django = {
> "jQuery": jQuery.noConflict(true)
> };

This indicates that your web server is still serving the file provided by `django-admin` instead of `grappelli`.  So that is where you need to look for resolving this.

> But it still shows as original...it definitely appears to be a caching issue, so I rebooted and it still shows the same.

I'm definite that it is not a caching issue.  Configuration and serving of static files is where I'm sure you will find the problem.

One way to do that is find the URL where `jquery.init.js` is being served from.  For example, using Firefox dev tools:

1. Go to the Network tab
1. Reload the page if necessary
1. Locate `jquery.init.js`
1. Right-click and open in a new tab

What's the URL being used?  What's the content of the file?

Leave this tab open while you are trying to resolve this problem, since you can keep refreshing it each time you make changes to see if it is making any difference.  Then try these steps:

1. Using the URL, locate the `jquery.init.js` file that is being served by your web server
  1. One easy way to tell that you have the right one is to simply rename the file and the refresh the tab you have opened
  1. If you have found the right one, then you should end up with a `404 Not Found` page
  1. Rename the file back to `jquery.init.js`
1. At this point, manually change this file to have the correct content (as you have done above) and confirm that is displayed when you refresh the page again
1. If that works, then the filter button should work again once you refresh _that_ page (i.e. the page with the filter button on it)

If you get this far, then the problem is somewhere with `collectstatic` or the web server configuration.

Notes:

1. At no point during this process did I need to restart the web server or clear the browser cache
1. As soon as changes are made to the correct file, they are displayed when refreshing the pages in the browser, even for the filter button

**Comment by mykljohn** [comment]
Hey thanks for the reply....I already checked the location...it's myserver/static/admin/js/jquery.init.js.  

So I went and deleted that file, and sure enough, I got a 502 error.   I then recreated the file with the code dummy code and refreshed and now I get Bad Request (400).  That's with Debug = False, If I set Debug = True, it goes in, but has the old code.  
but the file at that address is correct.  I'm guessing somehow the old file has been cached on the server (?)  I'm hosted on pythonanywhere.com so I sent a message to tech support there as well.

This is really confounding me because I never had to do a reload to the server for js or html...only php.

**Comment by myii** [comment]
The following resources might be useful to you:

* https://help.pythonanywhere.com/pages/502BadGateway
* https://help.pythonanywhere.com/pages/Django400BadRequest

How about `python manage.py collectstatic --noinput --clear`?  Quoting from my post on the other issue:

> https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#django-admin-option---clear:
> 
> `--clear`
> 
> Clear the existing files before trying to copy or link the original file.
> A caveat:
> 
> Using `--clear` is like a sledgehammer; it will clear all static files that aren't needed by the current project
> So if you are using the same `STATIC_ROOT` for more than one project, then better to leave this method -- there's a more nuanced, less destructive method outlined further down
> Essentially, **don't use this for anything other than testing**, unless you're comfortable to rebuild `STATIC_ROOT`
> 
> Now the steps:
> 
> Ensure you have `'grappelli'` before `'django.contrib.admin'` in `INSTALLED_APPS`, as shown in the reference above
> Run `python manage.py collectstatic --noinput --clear`
> Test from the browser, with full reload of the page with the filter button on it -- error should be resolved

**Comment by mykljohn** [comment]
That's what I did at first.  and it looked good in my static files, but it still in devtool it still had the old code.  so I went and edited /files/home/geeval/.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js and copied the Grappelli no use code there.  So in theory, there should be no jquery.init.js existing with the old code.  But it still shows up in devtool.  That's why I'm stumped :(  

I've just zipped up the .virtualenvs folder and I'm searching it for jquery.init.js just to see if it's located anywhere else.

**Comment by mykljohn** [comment]
I upgraded Grappelli because the dashboard wasn't working.  :(  I'm regretting that decision now :)

**Comment by myii** [comment]
> I then recreated the file with the code dummy code and refreshed and now I get Bad Request (400). That's with Debug = False, If I set Debug = True, it goes in, but has the old code.

From https://help.pythonanywhere.com/pages/Django400BadRequest:

> ```
> 400 Bad Request
> ```
> 
> Unfriendly huh? It's a common django problem though (as you'll see from a quick google search, and the answer is that you need to set the `ALLOWED_HOSTS` setting in your settings.py (or switch `DEBUG` back to True)

To be able to set `DEBUG = False`, you need to set the `ALLOWED_HOSTS` value.  Something like:

```
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'Site_URL_goes_here',
]
```

Obviously, modify `'Site_URL_goes_here'` with your site URL.

Get it working with this setting and then see if the static file is served properly.

**Comment by mykljohn** [comment]
Ok, a little progress.  I got rid of the 400 error.  But it still has the static file error.

**Comment by mykljohn** [comment]
Just to reiterate, these are my files in question. 
static/admin/js/jquery.init.js 
    // dropped
    // not used in grappelli
    // kept this file to prevent 404

.virtualenvs/django18/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js
    // dropped
    // not used in grappelli
    // kept this file to prevent 404

So I have no idea where it's getting the old code from.  still scanning .virtualenv....70% complete

**Comment by myii** [comment]
From what I mentioned earlier:

> One way to do that is find the URL where `jquery.init.js` is being served from. For example, using Firefox dev tools:
> 
> 1. Go to the Network tab
> 1. Reload the page if necessary
> 1. Locate `jquery.init.js`
> 1. Right-click and open in a new tab
> 
> What's the URL being used? What's the content of the file?

Please specifically mention the URL.

Then get the `404` error like I mentioned above:

> Leave this tab open while you are trying to resolve this problem, since you can keep refreshing it each time you make changes to see if it is making any difference.  Then try these steps:
> 
> 1. Using the URL, locate the `jquery.init.js` file that is being served by your web server
>   1. One easy way to tell that you have the right one is to simply rename the file and the refresh the tab you have opened
>   1. If you have found the right one, then you should end up with a `404 Not Found` page
>   1. Rename the file back to `jquery.init.js`

Do you get the `404` error or not?

**Comment by mykljohn** [comment]
the link address in devtool is:
http://mykl.pythonanywhere.com/static/admin/js/jquery.init.js

Which is correct, but in devtool it contains: 
// Puts the included jQuery into our own namespace
var django = {
    "jQuery": jQuery.noConflict(true)
};


But the file at that address and in .virtualenv both contain: 
// dropped
// not used in grappelli
// kept this file to prevent 404

no 404 error.

**Comment by mykljohn** [comment]
Ok, it's official, the code shown does not exist in my files on the webserver.  the only js programs that have the line "jQuery": jQuery.noConflict(true) are \mysite\static\grappelli\js\grappelli.js
and .virtualenv\django18\lib\python2.7\site-packages\grappelli\static\grappelli\js\grappelli.js

It's got to be some sort of caching on the server.   yes?  It's not making sense to me otherwise.

Where is it getting that code from?

**Comment by myii** [comment]
Just to confirm, I've followed your link and this is what I've got:

```
// dropped
// not used in grappelli
// kept this file to prevent 404
```

So that's the correct version being served here.  Perhaps the pythonanywhere people can explain what is going on at their end.

**Comment by mykljohn** [comment]
I'm sorry the link address is http://geeval.pythonanywhere.com/static/admin/js/jquery.init.js

the other wasn't updated.

**Comment by myii** [comment]
Right, that one is showing the `django-admin` version:

```
// Puts the included jQuery into our own namespace
var django = {
    "jQuery": jQuery.noConflict(true)
};
```

So now the issue is with the static files that are on the web server.  You normally need to copy these over.  Please post your web server configuration.

**Comment by mykljohn** [comment]
Please post your web server configuration.   I'm sorry what do you mean?

**Comment by mykljohn** [comment]
I just found this on the dashboard web.  Static files:

/static/admin/	/usr/local/lib/python2.7/dist-packages/django/contrib/admin/media

I'm guessing I should delete this...yes?

**Comment by mykljohn** [comment]
I deleted it and it works !!!!  Thanks for your help!  I've been going crazy with this.

**Comment by myii** [comment]
No, don't delete anything, you might make the situation worse.  But the static files are being served by a web server.  Which one are you using?  Or which one is provided by PythonAnywhere?

**Comment by mykljohn** [comment]
hahaha, too late, but everything seems to be working now.  That must have been created when I opened the account because I sure didn't set it.

**Comment by myii** [comment]
Well, that's good news!  I'm glad I was able to help, even if indirectly.  If all is OK, please go ahead and close this issue.

**Comment by mykljohn** [comment]
Question...is there any clearer documentation on setting up the dashboard?  or a video?

**Comment by myii** [comment]
Really sorry, don't have any experience with the dashboard. Perhaps ask a question on the Grappelli Google Group @ http://groups.google.com/group/django-grappelli.
------------------
Sent from my BlackBerry
________________________________

**Comment by mykljohn** [comment]
@myii FYI, you were right...it made things worse :)  It all worked fine yesterday, but when I turned on my pc today...no glory.  couldn't even startup.  So I reset it and now I'm back where I was...the jquery.init.js is in this /usr/local/lib/python2.7/dist-packages/django/contrib/admin/media folder, but it's hidden and protected.  I've sent a msg to pythonanywhere.com to help.  cheers.  Mykl
