### ISSUE TITLE
[Question] Dashboard

### ISSUE THREAD

**Issue by mykljohn** [sehmaschine/django-grappelli#760]
I'm using Model Reports for my clients to output data.  I would like to put them on the dashboard.  Is there a documented way to do this? or a video?

**Comment by sehmaschine** [comment]
Here is the documentation: http://django-grappelli.readthedocs.io/en/latest/dashboard_api.html

You could use a custom dashboard, for example. But there's probably different ways to achieve this. Besides, please use the google-group for asking questions.

**Comment by mykljohn** [comment]
thanks...just found the google-group
