### ISSUE TITLE
filter_horizontal covers first item in ManytoMany in admin

### ISSUE THREAD

**Issue by ArtemBernatskyy** [sehmaschine/django-grappelli#762]
In Firefox linux first item is covered by Filter field 
Screehshot : [click](https://drive.google.com/open?id=0B045JEsT1LHnblhiVDBRZU5PZUE)

**Comment by sehmaschine** [comment]
which version of django/grappelli?

**Comment by ArtemBernatskyy** [comment]
2.8.1 , latest as i see

**Comment by ArtemBernatskyy** [comment]
P.S. Firefox hasn't installed Flash. Firefox version is 46.0b1

**Comment by parsch** [comment]
@ArtemBernatskyy Can you please check if this is solved with ede5b66 (or similar to #737)

**Comment by ArtemBernatskyy** [comment]
Yes, this solved my problem [(click),](https://drive.google.com/open?id=0B045JEsT1LHnNWY3RjgwTWE3SXc) now it looks like this ([click](https://drive.google.com/open?id=0B045JEsT1LHnOE1weE9WYUlfQ2c)) .
P.S. Yes, my Django is 1.9 version as mentioned in #737.
Should i close this issue and wait for updates ?

**Comment by parsch** [comment]
The suggested solution you cited is not the one I used in the end. You should check out https://github.com/sehmaschine/django-grappelli/tree/stable/2.8.x (the commit ede5b66 contains the changes fixing #737), or at least get the ```screen.css``` of ede5b66
