### ISSUE TITLE
Feature Request: Auto-Complete Lookup on CharFields

### ISSUE THREAD

**Issue by danielniccoli** [sehmaschine/django-grappelli#765]
It would be great if the auto-complete feature would work on CharFields in a similar matter.

A practical example could be a model with a field `product_name`. Many objects can have the same product name, but a `ForeignKey` field to a model `Product` would be a management nightmare because of the sheer inifite number of product names. So instead of using a `ForeignKey`, we simply use a `CharField` and let the user type in the product name.

A user could set an object's `product_name` to _"Intel® Xeon® Processor E5-2620 v3"_. In this case he copy-pasted the product name from the internet, along with the special char _"®"_

The next user could create a new object with the same `product_name`, but he types it in on his keyboard, also missing the _"v3"_ at the end. The product name of the second object looks like this: _"Intel Xeon Processor E5-2620"_

With an auto-complete lookup on `CharFields`, the second user would have typed in _"Intel"_ and would have already gotten suggested _"Intel® Xeon® Processor E5-2620 v3"_. :cool:

**Comment by sehmaschine** [comment]
I see what you mean and I generally agree.

That said, I'm not sure that the database setup you described with regards to `product_name` is the best solution ... there's still the possibility of people using the wrong name for similar products.

**Comment by Borkason** [comment]
Nice to hear :)

About your objection. I fully agree, the possibility that users choose to ignore the suggestions persist. However, in my case I had to weigh up usability versus consistency. Since the product name is only a descriptive property, it's not bad if there are slight differences. Thanks for the hint.

**Comment by rcooke** [comment]
I want something similar.  Client repairs industrial electronics, there is a db of "parts" needed for each repair. The technicians have to type in the part specification every time such as "Resistor, 220 Ohm, 1/2Watt, 5%, SMD".

This is a Character field, their lives would be a LOT easier if I could give them an auto complete that searches all the previous Part row entries.

It would help keep descriptions orderly too.

**Comment by sehmaschine** [comment]
The plan is to remove Grappelli autocompletes in favour of the now available Django autocompletes. So I guess this issue is obsolete (see also #981)
