### ISSUE TITLE
Question about Auto-Complete Lookup: Why do two fields look different?

### ISSUE THREAD

**Issue by Borkason** [sehmaschine/django-grappelli#766]
I'm having an issue using the lookup. I have two lookups on my model `Asset`. The fields I apply a lookup are `invoice` and `credit_note`. They both refer to model `Invoice`.

The issue I am having is that on the admin page the field `invoice` looks different than the field `credit_note`. Also, the Invoice value *"10"* is really the `pk` of my model `Invoice`, instead of the `number`field.

![Model:Asset](https://cloud.githubusercontent.com/assets/2971735/16977702/0379ed66-4e58-11e6-830b-f05210979b0e.PNG)

Can you help me understanding what is wrong?

Those are my models (shortened):

```
class Invoice(models.Model):
    number = models.CharField(max_length=64, verbose_name='Invoice Number', **null)

    def __str__(self):
        return self.number

    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "number__icontains",)


class Asset(models.Model):
    invoice = models.ForeignKey(Invoice, verbose_name='Invoice', related_name='invoice', **null)
    credit_note = models.ForeignKey(Invoice, related_name='credit_note', **null)
```

And this my Admin (shortened):

```
@admin.register(Asset)
class AssetAdmin(admin.ModelAdmin):
'category')
    form = AssetAdminForm

    raw_id_fields = ('invoice', 'credit_note', )
    autocomplete_lookup_fields = { 'fk': ['invoice'], 'fk': ['credit_note'] }
```

**Comment by sehmaschine** [comment]
are the autocompletes working? can you do a search within the fields?

**Comment by Borkason** [comment]
Invoice: I can click on the magnifying glass and choose an invoice. If I type in a number autocomplete does not work. There is no HTTP/GET request sent to the server.

Credit Note: Everything works okay.

**Comment by sehmaschine** [comment]
you need to define the autocomplete lookup fields like this:

```
autocomplete_lookup_fields = { 'fk': ['invoice', 'credit_note'] }
```

**Comment by Borkason** [comment]
Oooohhh, that explains why the value is a list. (Something that I forgot to ask in the other question! :+1:
