### ISSUE TITLE
Documentation about Auto-Complete Lookups

### ISSUE THREAD

**Issue by Borkason** [sehmaschine/django-grappelli#767]
I am currently implementing some auto-complete lookups. I found the documentation at http://django-grappelli.readthedocs.io/en/latest/customization.html#autocomplete-lookups

**I have some questions.**

```
class MyModel(models.Model):
    @staticmethod
        def autocomplete_search_fields():
            return ("id__iexact", "name__icontains",)
```

What is the nature of the tuple? What is `"id__iexact"` and what is `"name__icontains"`? I assume the latter states  the field I am searching and how it should match. But the first surprises me. I could imagine id is what internally is returned to the form to identify the object behind the search result. But why is there a field lookup (`__iexact`) appended?

**Next Question**

```
class MyModelAdmin(admin.ModelAdmin):
    raw_id_fields = ('invoice', 'credit_note', 'related_to' )
    autocomplete_lookup_fields = { 'fk': ['invoice'], 'fk': ['credit_note'], 'm2m': ['related_to'], }
```

Beggining from the bottom, I assume the *key* part in that dictionary can be one of either 'fk', 'm2m' or 'generic' depending of the type of relationship. Is that correct or am I missing something?

Following that thought, why do I need `raw_id_fields` if I already state the fields I want to lookup in `autocomplete_lookup_fields`? I suppose there is a reason why I specifically have to add `raw_id_fields` that also include `'invoice', 'credit_note', 'related_to'` which brings me to the question what other possibilities I have here.

Thanks for your time and hopefully some insights. I very much enjoy Grappelli only for the lookups already.

**Comment by sehmaschine** [comment]
1. the tuple is used for searching. with the mentioned example, you search for id (exact) and name (icontains).
2. key: right. 
3. you need raw_id_fields, because autocompletes is kind of a hack. we need the output of raw_id_fields with the template, because otherwise we do not get the ID.

**Comment by Borkason** [comment]
Just to clarify:
1. So what I have is the possibility to either remove `id__iexact` if I'd like to search only for `name__icontains`? Or add the option to search for a third, fourth, … field within the object?  
I tried to remove `id__iexact` leaving only `name__icontains`, but that gives me an error, so I assume I did not understand that part.

2. and 3. Thanks, I understood! :smile:

**Comment by sehmaschine** [comment]
you can use djangos field lookups. not sure why there's an error when removing `id__iexact` ... that shouldn't be the case (you may wanna try to debug that)

**Comment by Borkason** [comment]
Okay thank you for clarifying this. The error would be my fault then!
