### ISSUE TITLE
Getting RemovedInDjango110Warning on InlineAdminForm rendering

### ISSUE THREAD

**Issue by ydaniv** [sehmaschine/django-grappelli#768]
Comes from: 
- `grappelli/templates/admin/edit_inline/stacked.html` line 26
- `grappelli/templates/admin/edit_inline/tabular.html` line 66

```
RemovedInDjango110Warning: InlineAdminForm.original_content_type_id is deprecated and will be removed in Django 1.10. If you were using this attribute to construct the "view on site" URL, use the `absolute_url` attribute instead.
```

**Comment by rcooke** [comment]
Does this apply to any editable in place inlines?  I have one admin form that uses this, and have not observed a problem in testing with Django 1.10 yet.  I will dig deeper if I know what I'm looking for?

**Comment by sehmaschine** [comment]
I think it only applies to inlines with "view on site" (that is, objects with get_absolute_url defined).

**Comment by ydaniv** [comment]
Could be. @sehmaschine  if there's a problem duplicating this plz let me know if I can help. Any how, I've added the lines in the code where the deprecated property is used, so it should be as simple as replacing it.

**Comment by sehmaschine** [comment]
see #780
