### ISSUE TITLE
Django 1.10 inline JavaScript compatibility

### ISSUE THREAD

**Issue by tdruez** [sehmaschine/django-grappelli#770]
From https://docs.djangoproject.com/en/1.10/releases/1.10/#django-contrib-admin

> All inline JavaScript is removed so you can enable the Content-Security-Policy HTTP header if you wish.

Before, the `dismissRelatedLookupPopup` JavaScript was inlined within the  changelist `<a>`:
`onclick="opener.dismissRelatedLookupPopup(window, '123'); return false;"`

Now, the following attribute is set instead: `data-popup-opener="123"`

The new code to handle those attributes, available in Django at https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L142, needs to be added in the Grappelli's `RelatedObjectLookups.js` file as well.

**Comment by tdruez** [comment]
Similar issues for the select multiple widget.
The following snippet needs to be added on the Grappelli side: https://github.com/django/django/blob/master/django/contrib/admin/static/admin/js/SelectFilter2.js#L228

Actually, all the JavaScript files overrided in Grappelli should be compared and updated from the new ones in Django 1.10

**Comment by sehmaschine** [comment]
@tdruez thanks. we are aware of these issue and have not yet started with 1.10 compatibility.

**Comment by sehmaschine** [comment]
solved with stable/2.9.x
