### ISSUE TITLE
Cannot install grapelli on Django 1.9.5 in virtualenv

### ISSUE THREAD

**Issue by RompePC** [sehmaschine/django-grappelli#771]
I was gonna give a try to your admin app, but in the installation I got an error that seems weird at first view:

>Could not find a version that satisfies the requirement django-grapelli (from versions: )
No matching distribution found for django-grapelli

I'm using Python3, with virtualenv and Django 1.9.5 just installed. What can be wrong? (I'm sure this will be some fault of my, but cannot know what)

**Comment by sehmaschine** [comment]
it is grappelli (not grapelli)
