### ISSUE TITLE
Is anybody using Grappelli with a record locking system like Django-Locking?

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#774]
I love Grappelli, but I have a client that has to have record locking to prevent frequent data loss!

I have been using a variant of [django-locking](https://github.com/rcooke/django-locking) that has a few changes to make it work with an earlier version of Grappelli.

I was wondering if anybody is already maintaining a fork of django-locking with updated mods.  Or maybe there is a better locking system?

Or maybe it should be _incorporated_ into Grappelli as a new _feature_?

**Comment by sehmaschine** [comment]
definitely interesting, but out of scope. besides, it seems that django-locking is no longer actively developed.

**Comment by rcooke** [comment]
Likely because it still works!  heheh

Actually, ONE big issue with it is lack of support by Mobile browsers!  It catches unexpected exits using a DOM model event that fires before the web page is deleted from memory.  Works great on desktops.  But, all mobile browsers have decided to NOT implement it!  

All of them saying its for "user security", since some nasty websites use that function to try and keep the user on their site.

Their answer is to write an APP for their device.  Then you can handle that event any way you like.

Its enough to make me think its part of some master plan to force developers to develop for their platform!
