### ISSUE TITLE
Related widget add-another tool position.

### ISSUE THREAD

**Issue by sonarun** [sehmaschine/django-grappelli#775]
Django 1.9.7
Django Grappelli 2.8.1
django-autocomplete-light

Related widget tools position are missing / incorrectly placed.

Here is an example:
<img width="969" alt="screen shot 2016-09-03 at 12 53 02 pm" src="https://cloud.githubusercontent.com/assets/593557/18226324/6420d314-71d5-11e6-8863-f753428e5bfc.png">

.grp-related-widget-tools has a padding left of 760 px, and isn't floated to the form.

Meanwhile, on using an Inline, the add-another styling is completely hidden.
<img width="905" alt="screen shot 2016-09-03 at 12 47 50 pm" src="https://cloud.githubusercontent.com/assets/593557/18226305/eaabf716-71d4-11e6-85e3-a9110fbe4372.png">

I can make the styling show up by removing the padding-left and setting a z-index to 1.
<img width="889" alt="screen shot 2016-09-03 at 12 50 34 pm" src="https://cloud.githubusercontent.com/assets/593557/18226313/0da72772-71d5-11e6-9735-bf29e6c9fb32.png">

But that makes the non-inlined add-another widget incorrectly placed. It should be floated to the left of the form.

Anyone else running into this? I cleared and re-created my static files and the issue persists.

**Comment by sehmaschine** [comment]
Is this related to grappelli or to django-autocomplete-light?

**Comment by sonarun** [comment]
It's definitely Grappelli, I was even having the issue on non-autocomplete fields. I modified the code in the Grappelli css and it is working fine. It's an issue that i've been having for a while.

The CSS Should be:
.grp-related-widget-tools {
    position: relative;
    top: 2px;
    z-index: 1;
}

    input + &,
    select + &,
    textarea + &,
    .radiolist + &,
    .checkboxlist + & {
       position: relative;
       display: inline-block;
       float: right;
       padding-left: 0;
       margin-right: 0
    }

I was working on a production system, so I didn't have access to the compass files at the time.

In a few days I can spin up another test system and I will issue a pull request. I was wondering if anyone had noticed it.

**Comment by parsch** [comment]
Thanks for reporting – and fixing it!
