### ISSUE TITLE
Reverse for 'view_on_site'  not found

### ISSUE THREAD

**Issue by MikeVL** [sehmaschine/django-grappelli#780]
**Django 1.10**

Affected templates:
- grappelli/templates/admin/edit_inline/stacked.html 
- grappelli/templates/admin/edit_inline/tabular.html 

```
{% url 'admin:view_on_site' inline_admin_form.original_content_type_id inline_admin_form.original.pk %}
```

`InlineAdminForm.original_content_type_id` is deprecated and will be removed in Django 1.10. If you were using this attribute to construct the "view on site" URL, use the `absolute_url` attribute instead.

**Comment by sehmaschine** [comment]
solved with stable/2.9.x
