### ISSUE TITLE
No wheel for latest version 2.8.2

### ISSUE THREAD

**Issue by adamchainz** [sehmaschine/django-grappelli#787]
This project has `bdist_wheel` configuration in its `setup.cfg` but no wheel has been published. This implies that the `bdist_wheel` step was missed in release. A full sdist + bdist_wheel release can be done with `python setup.py clean sdist bdist_wheel upload`. You can also upload the wheel right now by checking out the source code at that point and running `python setup.py clean bdist_wheel upload`. This will speed up everyone's installs 🐇 😄

**Comment by tdruez** [comment]
@sehmaschine I've been also running successfully a download of the 2.9.x branch for the past month, any plans for a proper 2.9.1 pypi release?
Thanks!

**Comment by sehmaschine** [comment]
@tdruez I'll do a release in the next couple of days. I just waited for some feedback on compatibility with django 1.10.

**Comment by tdruez** [comment]
Great news! No issues with the 2.9.x branch so far on my side :)

**Comment by sehmaschine** [comment]
hope this issue is solved.

**Comment by tdruez** [comment]
@sehmaschine that's great! Thanks 👍

**Comment by adamchainz** [comment]
And there's a wheel, yay! ☸️ 🎡 🎉
