### ISSUE TITLE
Cannot select values in `raw_id_fields` popup with Django 1.10

### ISSUE THREAD

**Issue by frnhr** [sehmaschine/django-grappelli#790]
VERSIONS: Grappelli 2.8.2, 2.8.1, Django 1.10.3
STATICFILES: OK / runserver
JAVASCRIPTS: OK / no errors
CUSTOMIZATIONS: NONE

Click on the magnifying glass icon opens the popup. However, a click on the object does not close the popup and fill in the ID. Instead, the changeview is opened inside the popup.

Works fine if Django is downgraded to <1.10.
Also works on Django 1.10 without Grappelli, of course.

**Comment by sehmaschine** [comment]
please try branch stable/2.9.x ... 2.8.x is not compatible with django 1.10.
