### ISSUE TITLE
Inline table title formatting problem in Grappelli 2.9.1

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#791]
One of the problems I found testing Django 1.10 against Grappelli 2.8 was in how in-lines are displayed in the Admin.

I have a repair database - it holds data about electronic device diagnosis and repair at the PCB level.  Each repair is going to need at least 1 part replaced (usually 10-50).  So I made PARTS db an in-line.

DJ1.10 styles the inline table header to have a "?" character after the centered title.  Hovering over the "?" character shows the help for that column field - saves a lot of space!

Grappelli 2.8 and 2.9.1 both are making the column titles left-justified.  And putting the help text below each field in the column - effectively doubling the space each row needs.

Back in 2.8 I tried to figure out how to update the Grappelli JS files that replace the original admin ones, I had to give up.  Not understanding the history of the changes made it too hard for me to sort out the <table> layout conversion to <span>s.  I am hopping smarter people will resolve it....

Or is this something you have seen in testing, and it indicates a problem in my install or setup?

Thanks in advance!

**Comment by sehmaschine** [comment]
@rcooke you are right. we are aware of this issue and decided to not go with the "?" since it´s not consistent. that said, with regards to your usecase it definitely makes sense. we´ll take another look ...

**Comment by rcooke** [comment]
The other issue is it is repeating the HELP message text on every row.  So rows are at least twice as tall as necessary.  Especially since half of the "info" is the same string repeated over and over underneath each field.

If your against having an icon, why not make the help text into a hover-over message on the field or the column title?

**Comment by sehmaschine** [comment]
@parsch can you answer that?

**Comment by parsch** [comment]
@rcooke Is it an option to use a description (instead of help texts)? See #216

**Comment by rcooke** [comment]
@parsch Thanks!  But -1 for not linking to what "description" is!

Are you referring to this?:

[Field API reference - description](https://docs.djangoproject.com/en/1.10/ref/models/fields/#django.db.models.Field.description)

And I don't see any Grappelli docs on how it would be used with or instead of help_text.

**Comment by rcooke** [comment]
Or maybe you meant:

[ModelAdmin.fieldsets](https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets)

The Description item is mentioned here too.  But there is a note that it is not always displayed.


## description

A string of optional extra text to be displayed at the top of each fieldset, 
under the heading of the fieldset. _This string is not rendered for TabularInline_ 
_due to its layout._

**Comment by rcooke** [comment]
Heh.  One quick fix is to hide the help text with some JS in JQuery:

```
django.jQuery(document).ready(function($){
  $(".inline-group .grp-help").hide()
});

```
I'm trying to learn enough JS/JQuery to copy or move the HELP TEXT someplace else.  Either as the "title" text for the input field, or the column title.

**Comment by rcooke** [comment]
Heh.  Ok.  So I figured out the Jquery to copy the help text message onto the cell container's "title" attribute.  So hovering the mouse over the cell pops it up.  I might try and figure out how to target the input cell itself, if users complain the pop ups are too distracting this way.

```
django.jQuery(document).ready(function($){
  $(".inline-group .grp-help").hide()
  $('.inline-group .grp-help').each(function() {
    this.parentNode.title = this.innerHTML;
  });
});

```

**Comment by sehmaschine** [comment]
change to django-style help text.

@parsch please add styling
