### ISSUE TITLE
TemplateDoesNotExist at /admin/password_change/

### ISSUE THREAD

**Issue by ArtemBernatskyy** [sehmaschine/django-grappelli#793]
django-grappelli==2.8.3
Django 1.9.11
with Dasboard setup when i click on "Change password" in top header menu

"""control_panel/base.html
Request Method:	GET
Request URL:	http://172.16.0.19:8000/admin/password_change/
Django Version:	1.9.11
Exception Type:	TemplateDoesNotExist
Exception Value:	
control_panel/base.html
Exception Location:	/var/webapps/mutual_funds/env/lib/python3.4/site-packages/django/template/engine.py in find_template, line 169
Python Executable:	/var/webapps/mutual_funds/env/bin/python
Python Version:	3.4.3
Python Path:	
['/var/webapps/mutual_funds/code',
 '/var/webapps/mutual_funds/env/lib/python3.4',
 '/var/webapps/mutual_funds/env/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/webapps/mutual_funds/env/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/var/webapps/mutual_funds/env/lib/python3.4/site-packages',
 '/var/webapps/mutual_funds/code']
Server time:	Sat, 19 Nov 2016 14:19:43 +0000
"""

**Comment by parsch** [comment]
@ArtemBernatskyy Can't verify that, works fine with my setup. Do you use any customized versions (of the dashboard)?

**Comment by ArtemBernatskyy** [comment]
Omg, it was my fault, i used it with my modified django-registration-redux and it was overlapping urls and loading my broken template :(  

Thanks for great app !
