### ISSUE TITLE
change_list_template set to reversion/change_list.html ignoring admin/<my_app>/change_list.html and admin/<my_app>/<my_model>/change_list.html 

### ISSUE THREAD

**Issue by orlra** [sehmaschine/django-grappelli#794]
Hi, 

I had a problem with templates while adding a button to change_list.html 

context:

> django-grappelli==2.7.3
> Django==1.8.16
> django-reversion==2.0.7

I have expected same mechanism for **change_list** as **change_form**.
default structure seems to be ignored for both admin/<my_app>/change_list.html  and admin/<my_app>/<my_model>/change_list.html 
what I found is that variables are set differently:

```
change_form_template = None
change_list_template = reversion/change_list.html
```

I've found 2 solutions: 
changing default to `change_list_template = None` on modelAdmin is enough to make template engine look into  `admin/<my_app>/<my_model>/change_list.html  ` while all extension files need to `{% extends "reversion/change_list.html" %}` instead of `{% extends "admin/change_list.html" %}`
second solution would be creating EXACT change_list file that does desired changes in `reversion/change_list.html`

Desired effect: 
Ability to extend Admin list view with admin/<my_app>/<my_model> OR docs entry that this is done differently. Bellow print screen with example buttons, 1 model specyfic, 1 global.
![zrzut ekranu z 2016-11-24 12-46-41](https://cloud.githubusercontent.com/assets/20792810/20598127/dc77e412-b247-11e6-9bb7-87e0b45c2a3b.png)

**Comment by sehmaschine** [comment]
@orlra sorry, but I cannot follow. you know that overriding templates is a django issue, right? we don´t change that behaviour.
