### ISSUE TITLE
Actions Box - stop auto submit on selection

### ISSUE THREAD

**Issue by zobbo** [sehmaschine/django-grappelli#795]
**VERSIONS: Grappelli 2.7.1, Django 1.8.3
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: NONE**

I am trying to use Django Import Export (https://github.com/django-import-export/django-import-export) with Grapelli. It changes the admin interface to add an extra selection box next to actions. This lets you select from the actions, "Export selected" and then choose the format you want to export the data in. 

Because Grapelli auto submits on selection of an action this won't work as the format can never be chosen. Is it easily possible to change this behaviour in Grapelli?

Many thanks 

Ian

**Comment by sehmaschine** [comment]
We changed this behaviour with Grappelli 2.8. It is not planned to update 2.7 though.

**Comment by zobbo** [comment]
Ah excellent - time to upgrade. Many thanks!

Ian
