### ISSUE TITLE
FilteredSelectMultiple widget is not used for m2m fields.

### ISSUE THREAD

**Issue by surennata** [sehmaschine/django-grappelli#796]
VERSIONS: Grappelli 2.9.1, Django 1.10.2
STATICFILES: OK
JAVASCRIPTS: ERROR, addevent.js seems to be missing.
CUSTOMIZATIONS: NONE

Hi,

I am using django-grappelli 2.9.1 with Django 1.10.2 for the admin page.
In the earlier versions for django-grappelli and Django, if a m2m field is included in the 'filter_horizontal'
the FilteredSelectMultiple widget was used for m2m fields.

But in the latest version this seems to be missing and the reason is that one of the dependencies for SelectFilter2.js, 
the addevent.js has been removed.

I made a workaround to make this work.  I added the below lines in 'grappelli/templates/admin/base.html' after the
specification of jquery.js files.

```
   <script type="text/javascript">
       addEvent(window, "load", function(e) {
           SelectFilter.init("", "", 0, "/static/admin/"); 
       });
   </script>
```

Could this be included in the django-grappelli package so that I don't have to maintain the patched version.

Thanks and regards,
Vijay.

**Comment by sehmaschine** [comment]
I'm not able to reproduce this. Works fine for me. Any details?

**Comment by surennata** [comment]
Yes.  This issues seems to have gone now.  Don't know what was wrong before and how that was corrected.

Anyways, thanks for your time on this issue.  

Please feel free to reject this issue.  Or should I do it?

**Comment by sehmaschine** [comment]
Thanks for the clarification.
