### ISSUE TITLE
Having formatting or layout problem with import-export and Reversion

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#799]
I tried to add ExportMixin to my system.  Because I'm using 

https://github.com/etianen/django-reversion

Which uses its own custom admin, I had to use your ExportMixin.  When put second in the class list it did not seem to work.  So I put it first, as in:

`@admin.register(Parts)`
`class PartsAdmin(ExportMixin, VersionAdmin):`

Which works, but the change list view is not as shown in the sample photos. 

The "Add Parts" button used to be a large oval above the "Filter" tab. Both it and the "Export" button are simple text hyperlinks against the left hand margin.

Also, django-reversion had a "Recover Deleted" button beside the "add Parts" button, it seems to have vanished.

I'm going to start trying to untangle the various CSS logic in play here, but wanted to post first in case this is a know issue with a quick and easy fix.

Thanks in advance!

My setup:
 - Hosted on Python Anywhere
 - Django 1.10
 - Python 2.7

Cross-Posting this to all 3 libraries in use:
 
https://github.com/django-import-export/django-import-export/issues/561

https://github.com/etianen/django-reversion/issues/615

**Comment by sehmaschine** [comment]
as @etianen already mentioned, we need to adjust the templates. since I'm personally not using reversion, I didn't recognize that there have been changes according to the templates. my suggestion is to look into the reversion templates and compare it with the grappelli reversion templates and find the diffs. shouldn't be a big deal IMO.

**Comment by sehmaschine** [comment]
closing this since there hasn't been any updates for a while.
