### ISSUE TITLE
Use get_change_message in object history template

### ISSUE THREAD

**Issue by tsouvarev** [sehmaschine/django-grappelli#801]
Django 1.10 brought new method `LogEntry.get_change_message()`, which nicely formats change messages (which become JSON in 1.10). So, Grappelli can use it, instead of just dumping JSON string in history table.

**Comment by sehmaschine** [comment]
@tsouvarev I don't quite understand where exactly we should use this new method. Any details on this?

**Comment by tdruez** [comment]
@tsouvarev See the change in https://github.com/sehmaschine/django-grappelli/commit/9da2bc3d03f234962254f44eba377e502eb7c588

**Comment by tsouvarev** [comment]
@tdruez that's it, thank you
