### ISSUE TITLE
Popup closing issue

### ISSUE THREAD

**Issue by kaizenapp** [sehmaschine/django-grappelli#804]
Recently I started facing the issue when popup freezes in the **Popup closing...** state. 

I investigated and found that when I click **Save** in the popup, it refreshes and I get this error in Google Chrome console:
```
Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at popup_response.js:4
    at popup_response.js:16
```

I debugged further and found that `document.getElementById('django-admin-popup-response-constants').dataset.popupResponse`, which we pass to the `JSON.parse(..)` is empty.

Then I checked view source of the page when it is in the **Popup closing...** state, and HTML looked like this:
```
<!DOCTYPE html>
<html>
  <head><title>Popup closing...</title></head>
  <body>
    <script type="text/javascript"
            id="django-admin-popup-response-constants"
            src="/static/admin/js/popup_response.js"
            data-popup-response="">
    </script>
  </body>
</html>
```

For some reason, `data-popup-response` is always empty.

Does anyone have ideas on why it started happening and how to fix it?

**Comment by jamesbaltar** [comment]
Same here, I'm also encountering this issue on pop-ups with `related_lookup_fields`. If it helps here's the versions that I'm using in `Python3`:

`Django==1.9.8`
`django-grappelli==2.9.1`

**Comment by ecomesana** [comment]
Check version of grappelli for your version of django. 
@jamesbaltar since you are using django 1.9.8, you shoud be using django-grappelli 2.8.3 (as is explained in README.md: Grappelli 2.8.3 (November 8th, 2016): Compatible with Django 1.9)

**Comment by sehmaschine** [comment]
please reopen if the problem still exists with the correct grappelli/django combination.
