### ISSUE TITLE
Autocomplete limits search results to ten.

### ISSUE THREAD

**Issue by kierun** [sehmaschine/django-grappelli#809]
+ VERSIONS: 
  + Grappelli 2.9.1,
  + Django 1.11.1
+ STATICFILES: OK
+ JAVASCRIPTS: OK
+ CUSTOMIZATIONS: NONE.

I have set up one of  my model to use autocomplete, I get the correct widget and the search works fine. However, the search displays only the top ten search results and not the full results list. The [documentation](https://django-grappelli.readthedocs.io/en/latest/customization.html#autocomplete-lookups) makes no mention that the results are thus limited or how to change what the limit is.

**Comment by sehmaschine** [comment]
see https://django-grappelli.readthedocs.io/en/latest/customization.html#available-settings

**Comment by kierun** [comment]
@sehmaschine OOPS! Thank you. ☺
