### ISSUE TITLE
The inline foreign key did not match the parent instance primary key

### ISSUE THREAD

**Issue by mpeddle** [sehmaschine/django-grappelli#810]
When using a TabularInline with Grappelli, it looks like the management_form is not rendering properly (resulting in the error above).  I'm using Django 1.10.5 and Grappelli 2.9.1.  Thoughts on what might be causing this issue?

A sample of my admin classes for context : 

class BikeInline(admin.TabularInline):
    model = Bike
    fields = ('id', 'resident_name', 'phone', 'brand', 'color', 'serial', 'access',
              'status', 'registration_date', 'stolen_date')
    classes = ('grp-collapse grp-open',)
    extra = 0

class UnitBikeAdmin(admin.ModelAdmin):
    fields = ('id', 'address')
    list_display = ('id', 'address',)
    readonly_fields = ('id', 'address')
    search_fields = ('id', 'unit__address', 'bike__resident_name')
    search_fields = ('id', 'unit__address', )
    inlines = [BikeInline, ]

**Comment by sehmaschine** [comment]
I'm pretty sure this is not related to grappelli. You could try to deactivate grappelli and check if the error still exists – if that´s not case, please reopen this ticket.
