### ISSUE TITLE
Related Lookup problem

### ISSUE THREAD

**Issue by abithyzis** [sehmaschine/django-grappelli#816]
I recently updated from django 1.5 to 1.11 and grappelli to 2.9.1 and I noticed that all my edit buttons (pencils) stopped working when there is an existing item.
Updating to grappelli  2.10.1 which supports django 1.11 the pencils completely dissapear

_models.py_
```
class Collection(models.Model):
    items = models.ManyToManyField(...)
```
_admin.py_
```
class CollectionAdmin(admin.ModelAdmin):
    model = Collection
    fieldsets = (
        (None, {'fields': (..., 'item',)}),
    )
```
This used to work with the older versions of django and grappelli.

I am not sure if this a bug or me not configuring things properly. I tried [this](https://django-grappelli.readthedocs.io/en/latest/customization.html#related-lookups) but it does not produce the outcome I expect (a dropdown with edit/create actions)
[This](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/static/admin/js/admin/RelatedObjectLookups.js#L185) is what I think creates the problem, but I guess if I put it back in I will have issues elsewhere?

Thank you

**Comment by sehmaschine** [comment]
see #639

**Comment by abithyzis** [comment]
I am following up on another issue in the RelatedObjectLookups.js
The elem referenced [here](https://github.com/sehmaschine/django-grappelli/blob/a0e442d8e5ba02a1b976d6561ce34a0bb7cccfc7/grappelli/static/admin/js/admin/RelatedObjectLookups.js#L117) is undefined 
Not sure if this will be part of the bigger overhaul
