### ISSUE TITLE
How i can change time in timewidget?

### ISSUE THREAD

**Issue by Zverushko** [sehmaschine/django-grappelli#817]
Hello!
i have http://joxi.ru/KAxozv7sMQOwp2.png
how i can change it for
now
9-00
9-15
9-30
9-45
etc
17-45
18-00

thx!

**Comment by sehmaschine** [comment]
please use the google-group for asking questions (this is an issue tracker).

hint: js/jquery.grp_timepicker.js (from lines 22). you should be able to use `default_time_list`.
