### ISSUE TITLE
Undefined `elem` in RelatedObjectLookups.js

### ISSUE THREAD

**Issue by donatogr** [sehmaschine/django-grappelli#821]
Django 1.8.9, Grappelli 2.8.1.

In `RelatedObjectLookups.js` both `dismissChangeRelatedObjectPopup` and `dismissDeleteRelatedObjectPopup` trigger `elem.focus();` but `elem` is undefined.

https://github.com/sehmaschine/django-grappelli/blob/a0e442d8e5ba02a1b976d6561ce34a0bb7cccfc7/grappelli/static/admin/js/admin/RelatedObjectLookups.js#L117

https://github.com/sehmaschine/django-grappelli/blob/a0e442d8e5ba02a1b976d6561ce34a0bb7cccfc7/grappelli/static/admin/js/admin/RelatedObjectLookups.js#L131

**Comment by sehmaschine** [comment]
can you please try with Grappelli 2.8.3? I'm not saying this issue is solved, but you refer to a version which is not maintained.
