### ISSUE TITLE
Autocomplete lookup across apps not working

### ISSUE THREAD

**Issue by pista329** [sehmaschine/django-grappelli#823]
VERSIONS: Grappelli 2.10.1, Django 1.11.3

Hi guys, I am trying to use autocomplete lookup of fields from another apps.

```
class MyModel(models.Model):
    sibling_fk = models.ForeignKey('SiblingModel')
    app_fk = models.ForeignKey('another_app.OtherModel')
```

```
class MyModelAdmin(admin.ModelAdmin):
    raw_id_fields = ('sibling_fk', 'app_fk')
    autocomplete_lookup_fields = {
        'fk': ['sibling_fk', 'app_fk'],
    }
```

Autocomplete for `sibling_fk` works fine, but  for `app_fk`, grappelli is not able to produce correct autocomplete url. What I am getting is url where app_label is false and model_name is false.
`/grappelli/lookup/autocomplete/?term=abc&app_label=false&model_name=false&query_string=false`

Also autocompletes between fields in other models in `another_app` works fine.

Thanks for your help.

**Comment by sa9** [comment]
I having the same issue as well. Any solution for this?

**Comment by EpicEric** [comment]
I ran into the same issue, and it turns out it was because I did not register `'another_app.OtherModel'` in Django Admin. [From the documentation](https://django-grappelli.readthedocs.io/en/latest/customization.html#autocomplete-lookups):

> **Note**
> In order to use autocompletes, you need to register both ends (models) of the relationship with your `admin.site`.

**Comment by sehmaschine** [comment]
I'm closing this issue since it probably relates to what @EpicEric (thanks!) mentioned. Please reopen if the issue still exists with registering both ends of the relation.
