### ISSUE TITLE
Optimization of autocomplete_lookup_fields

### ISSUE THREAD

**Issue by emihir0** [sehmaschine/django-grappelli#824]
Is there any way to optimize `autocomplete_lookup_fields` so that there are no additional queries fired for every inline? My (simplified) models:

```
class Category(models.Model):
    name = models.CharField(max_length=6, unique=True, db_index=True)
    [...]

    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset() \
            .select_related('category')


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    [...]

    objects = ProductManager()

    def __str__(self):
        return "%s - %s" % (self.category, self.name)

    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "category__name__icontains", "name__icontains")
```

My inline:

```
class ProductInline(admin.TabularInline):
    def image_thumb(self, obj):
        return obj.product.image_thumbnail

    fields = ['id', 'product', '[...]']

    raw_id_fields = ['product']
    autocomplete_lookup_fields = {
        'fk': ['product']
    }
    readonly_fields = ['id', '[...]']

    model = Product
    extra = 0
```

When the inline is rendered, it has `product` and `category` instances cached; yet when it comes to rendering the autocomplete of the inline, it fires lookup request for every row (even though it already has that info). The auto complete is extremely useful when we want to change/add new inlines, but it could use optimization when loading the already existing ones. Maybe I'm missing something obvious and such optimization already exists?

P.S.: As I said, this is a very simplified version of my models and it makes sense for my use case to be able to lookup by both `category` and `product`. Think of it like 'Apple - Gala`, users don't always remember the product specific name, but the category name helps them find it quickly.

**Comment by sehmaschine** [comment]
I don´t think there is a way to achieve this with pure javascript (since we rely on what we get from django and that´s just the ID). However, if you come up with a good idea, please submit a PR.
