### ISSUE TITLE
Support Django 2.0

### ISSUE THREAD

**Issue by asfaltboy** [sehmaschine/django-grappelli#825]
Slated to be released in December, adding support for Django 2.0 would be amazing. Last release RC1 happened 2 weeks ago, [here is the announcement][2].

First and foremost because of the [mobile-friendly `contrib.admin`][1]. I haven't had a chance to play around with it, but I bet they added responsive styles for inlines as well. This may be a lot of work, but I think the community would be happy to help out, I know I would myself!

Let's use this issue to discuss the roadmap (Target 3.X ?) and list the individual parts that need to be changed, to assist contributors with short concise PRs where possible.

[1]: https://docs.djangoproject.com/en/dev/releases/2.0/#mobile-friendly-contrib-admin
[2]: https://www.djangoproject.com/weblog/2017/nov/15/django-20-release-candidate-1-released/

**Comment by sehmaschine** [comment]
Thanks for the heads up. We'll do another release (2.10.2) before dealing with Django 2.0. Besides, I don´t think we´ll support mobile devices with Grappelli.

**Comment by tdruez** [comment]
Before talking UI refinements, the first step should be too make the current code compatible with Django 2.0.
The following imports need to be replaced: `from django.core.urlresolvers import reverse`

**Comment by dstrohl** [comment]
I have a fork that I changed the imports with here: https://github.com/dstrohl/django-grappelli do you want me to do a pull request?  (which branch?)

**Comment by mpasternak** [comment]
@dstrohl I'm not sure about @sehmaschine , but if you ask me, GO FOR IT. Does your fork pass tests under 2.0?

**Comment by sehmaschine** [comment]
@dstrohl Sounds good. But please note that we´ll do another release before actually dealing with django 2.0. IMO, the best option is to wait for our upcoming release (which should happen this or next week). Otherwise, there are probably conflicts with your PR.

**Comment by sehmaschine** [comment]
There´s now a branch stable/2.11.x – please refer to this branch for any PR.

**Comment by dstrohl** [comment]
it didn't, but the tests seemed to be mostly solved by fixing a couple of
imports. However, I dropped Django 2.0 for now due to some pretty serious
problems with migrations and many to many fields so I didnt' finish it.
but it looks like it should not be very hard to get it working with 2.0.

**Comment by tdruez** [comment]
@sehmaschine `stable/2.11.x` is running along Django 2.0.1 in my codebase. Everything works fine.
Any plans for an official Grappelli 2.11 release?

**Comment by sehmaschine** [comment]
@tdruez I just waited for some styling issues to be resolved with 2.10.2 and we´ll release 2.10.2 and 2.11.1 later this week.

**Comment by tdruez** [comment]
Sounds great, thanks!

**Comment by sehmaschine** [comment]
done
