### ISSUE TITLE
RTL version

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-grappelli#827]
Hi
The RTL version of the grappelli is old and has many issues, can you please check it?

**Comment by parsch** [comment]
@sharifzadesina Can you provide some screenshots/examples? At a first glance it looks quite okay with my setup...

**Comment by parsch** [comment]
@sehmaschine There's an RTL issue with the brackets of FK/M2M `grp-related-labels`

![grp-rtl-related-labels](https://user-images.githubusercontent.com/206830/34111882-45a9c0c2-e40b-11e7-8c32-07d80d073607.png)

**Comment by sehmaschine** [comment]
@parsch that´s strange. the contents inside the span seems to be right. but as soon as there´s a space within the label, the additional bracket is there (although it is still not part of the contents). could this be an issue with the styles?

**Comment by sehmaschine** [comment]
maybe this one: https://stackoverflow.com/a/16611425

**Comment by parsch** [comment]
@sehmaschine This seems to be a webkit behaviour/bug (I thought that the bug's origin is some javascript text replacement but it's not). We can fix this by adding `&lrm;` to the `grp-related-labels` (https://stackoverflow.com/a/7931678) but the problem will exist for all other text parts containing brackets (e.g. labels, helptexts etc.).

**Comment by sharifzadesina** [comment]
There isn't only one or two bug, I've checked the source for RTL line-by-line, it is old and is not compatible with last style.

**Comment by sehmaschine** [comment]
@sharifzadesina which source?

**Comment by sharifzadesina** [comment]
@sehmaschine [this](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/compass/sass/rtl.scss)

I will send some images of visual bugs now.

**Comment by sharifzadesina** [comment]
![screenshot from 2017-12-20 16-58-36](https://user-images.githubusercontent.com/15300551/34209388-2bdf628a-e5a7-11e7-8db8-47f9ed0bcbb2.png)
float of login button should be "left" not "right".
body.grp-login should be added to the rtl file, to fix this bug. [here](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/compass/sass/screen.scss#L207) in source.

**Comment by sharifzadesina** [comment]
![screenshot from 2017-12-20 17-04-02](https://user-images.githubusercontent.com/15300551/34209542-cdad1f9e-e5a7-11e7-931d-e1acf297d19a.png)
The borders have wrong colors and direction.

**Comment by sharifzadesina** [comment]
Calendar has many bugs:
LTR Calendar:
![screenshot from 2017-12-20 17-04-48](https://user-images.githubusercontent.com/15300551/34209602-118139da-e5a8-11e7-8734-9a8ce1fea876.png)
RTL Calendar:
![screenshot from 2017-12-20 17-04-48](https://user-images.githubusercontent.com/15300551/34209596-076f0990-e5a8-11e7-8ccd-bcd97f54dade.png)

**Comment by sharifzadesina** [comment]
I tried to review the rtl.sass file completely and fix all the bugs, but when I started, I faced to many mixins and function which I wasn't aware about, so I had to go and check them one by one, so I just posted this issue to ask you for help.

**Comment by sharifzadesina** [comment]
![screenshot from 2017-12-20 17-10-52](https://user-images.githubusercontent.com/15300551/34209772-c9b72af0-e5a8-11e7-90d4-d9cee81029ea.png)

Arrow is in wrong direction.

**Comment by sharifzadesina** [comment]
![screenshot from 2017-12-20 17-11-28](https://user-images.githubusercontent.com/15300551/34209815-f235462e-e5a8-11e7-9c27-bce04f90ccdd.png)

The plus icon has wrong padding.

**Comment by sharifzadesina** [comment]
Footer in models archive:
![screenshot from 2017-12-20 17-14-02](https://user-images.githubusercontent.com/15300551/34209911-3b5c8d8a-e5a9-11e7-99b7-0204e199fca7.png)

**Comment by sharifzadesina** [comment]
LTR:
![screenshot from 2017-12-20 17-19-39](https://user-images.githubusercontent.com/15300551/34210215-4f664888-e5aa-11e7-90e1-a8f03ae498c4.png)
RTL:
![screenshot from 2017-12-20 17-19-55](https://user-images.githubusercontent.com/15300551/34210216-4fa1e514-e5aa-11e7-8b61-563cdce4fc19.png)

**Comment by sharifzadesina** [comment]
I think you can fix all of the bugs if you spend about 2-3 hour on this cause you are aware about all sass functions and mixins you use in styling. thanks.

**Comment by parsch** [comment]
@sharifzadesina thanks for reporting all the details

**Comment by parsch** [comment]
@sharifzadesina I fixed the RTL issues you mentioned (and some others I came across). Don't hesitate to report further bugs if you find any – unfortunately we're not used to RTL at all so it's a bit hard sometimes to have an eye for the small details.

**Comment by sharifzadesina** [comment]
@parsch Thank you for bug fix. but now when I am changing the language code to any RTL language (like ar (Arabic) or fa (Farsi)) the theme is still LTR and the direction doesn't change.
It seems this is cause you changed `if LANGUAGE_BIDI` to `if not LANGUAGE_BIDI` [here](https://github.com/sehmaschine/django-grappelli/commit/52e091ac555e5041e016313c48af66a24ef1381d#diff-b845866fbdab004e9709a6353b3fdc51R13).

**Comment by parsch** [comment]
Thanks, fixed it (forgot to remove the modifications for testing purposes).

**Comment by sharifzadesina** [comment]
@parsch Thank you for fix.
There is an other small bug with RTL version.
in rtl.scss you add some styles to all tables in the theme, [here](https://github.com/sehmaschine/django-grappelli/blob/stable/2.10.x/grappelli/compass/sass/rtl.scss#L418-L476).
this can break all custom components that include tables for example in CKEditor the gray borders circled by red squares are cause of RTL version, these gray borders doesn't exists in LTR version.
![screenshot from 2017-12-26 23-24-08](https://user-images.githubusercontent.com/15300551/34363748-10790112-ea94-11e7-9b47-e5fec3e73319.png)

**Comment by sharifzadesina** [comment]
@parsch It seems this bug is cause we don't have any special class for grappelli tables, so we add custom style to all tables and this breaks other third-party components, this is not specified to RTL mode only.
