### ISSUE TITLE
Pull down lists need whitespace between choices (or something)

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#828]
In a django 1.10.4 project with Grappelli 2.9.1 users are selecting wrong items in the tabular in-line pull-down choice lists.

They tend to get the item BELOW the one they want.  The choice names are similar so they frequently don't catch on.  Pandemonium ensues later.

Has anybody else seen this?

**Comment by sehmaschine** [comment]
do you have a screenshot?

**Comment by rcooke** [comment]
Sure.  Here is the inline with the dropbox open on the first row.  Users want to select "Sourced" but get "Ordered" instead.  Which fools the system into thinking the part has been ordered.
![image](https://user-images.githubusercontent.com/4250225/34116670-4607c880-e3e7-11e7-8525-f5eadc5acba3.png)

**Comment by sehmaschine** [comment]
Looks like an ordinary select to me. What exactly do you think we should improve here? Because this is related to your Browser/OS, not grappelli.

**Comment by rcooke** [comment]
I did not mean to imply this is a "problem" with Grappelli.  Only that I have see it cause problems.  Asking if others have too.

And, if so, what have others done to reduce errors?

And maybe its something Grappelli could fix by applying better CSS layout to it - or allowing dynamic re-arrangement or disabling of the choices.  

I have 6 users using different OS (Windows, Linux, Android) and different browser (Firefox, Chrome) experiencing it.  So I don't see it as a "specific OS or Browser" issue.

**Comment by sehmaschine** [comment]
If I'm not mistaken, there´s not much we can do since the options are browser/OS specific – unless we completely replace the select-field (which we don´t intend to do).

@parsch please correct me if I'm wrong and/or if you have another idea.

**Comment by parsch** [comment]
We do not apply any styles to `options` of native `selects` because it's not possible to create a unique look and feel across browsers/devices. I'm closing this since I don't see what we could improve here.
