### ISSUE TITLE
Conflict between style of tables

### ISSUE THREAD

**Issue by sharifzadesina** [sehmaschine/django-grappelli#832]
As we don't have any specific table class for grappelli tables and we add styles to add tables, sometimes we face conflict between styles in third-party components that include tables. for example in CKEditor the gray borders are cause of grappelli and they don't exists in CKEditor:

![screenshot from 2017-12-26 23-24-08](https://user-images.githubusercontent.com/15300551/34363748-10790112-ea94-11e7-9b47-e5fec3e73319.png)

This mostly happens in RTL mode but it can happen anywhere and can break style of third-party components.
The solution is adding a specific class to all grappelli tables, for example `grp-table`.

**Comment by parsch** [comment]
There's a class `grp-table` for Grappelli controlled tables now.
