### ISSUE TITLE
Under ChangeList you can not change the title

### ISSUE THREAD

**Issue by efimerdlerkravitz** [sehmaschine/django-grappelli#833]
Hello,

I'm overriding a change list class:
```
class BookChangeList(ChangeList):
    def __init__(self, request, model, list_display, list_display_links,
                 list_filter, date_hierarchy, search_fields, list_select_related,
                 list_per_page, list_max_show_all, list_editable, model_admin):
        super().__init__()

        self.title = 'Cool'

        # these need to be defined here, and not in BookAdmin
        self.list_display = ('name', 'categories')
        self.list_display_links = ['name']
        self.list_editable = ['categories'] 
```

Changing the title does not affect the view, see attached screenshot how it should look like:
![image](https://user-images.githubusercontent.com/33550454/35622670-577bf204-0691-11e8-8c48-5013af277bbd.png)

This is how it looks:
![image](https://user-images.githubusercontent.com/33550454/35622726-87545066-0691-11e8-91d3-7f152ad3729a.png)

VERSIONS: django-grappelli==2.10.1, Django==1.11.8
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: Changing title

**Comment by sehmaschine** [comment]
That's by purpose. You can change the title with `verbose_name_plural`. We decided to go with the simpler version instead of "Select <XXX> to change".
