### ISSUE TITLE
HTTP 414 for lengthy M2M autocomplete fields

### ISSUE THREAD

**Issue by 1337** [sehmaschine/django-grappelli#834]
Any M2M field in the admin that is configured to be autocomplete-enabled will fail if there are too many relationships. This makes the admin unusable for such fields, even though the user can select and deselect items from an autocomplete field that appears blank.

Environment:
* Django version: 1.10.8
* django-grappelli version: 2.9.1

Steps to reproduce:
1. Make an M2M field, say a Group model with a M2M field to Users.
2. Specify in the `GroupAdmin` the following:
```
raw_id_fields = ['users']
autocomplete_lookup_fields = {
    'm2m': ['users']
}
```
3. Do appropriate setup in your `settings.py`:
```
GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS = {
    'user': {
        'user': ('id', 'email', 'first_name', 'last_name')  # whatever
    }
}
```
3. Associate many (say, 10k) Users with a particular Group.
4. Open the browser's network inspector and load this Group in the admin. Observe that the admin makes the following request and fails with HTTP 414.

```
http://localhost:8000/grappelli/lookup/m2m/?object_id=2%2C3%2C4%2C5%2C6%2C7%2C8%2C9%2C10%2C11%2C12...
```

The HTTP 414 response body is:

```
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 414.
<p>Message: Request-URI Too Long.
<p>Error code explanation: 414 = URI is too long..
</body>
```

**Comment by sehmaschine** [comment]
I agree that an M2M autocomplete field should not be used in this case.
Not much we can do about it though, right?

**Comment by 1337** [comment]
I think autocomplete on a M2M on a large field is perfectly valid use case; it is just that this particular implementation (I think [here](https://github.com/sehmaschine/django-grappelli/blob/2.9.1/grappelli/views/related.py#L84)?) is made in such a way that the client is expected to provide the entirety of the field's existing relationships, which is something the server already knows.

So if the lookup were done from the current object's side, something like

    http://localhost:8000/grappelli/lookup/m2m/
        ?from_app_label=base    # the admin app I am looking at
        &from_model_name=group  # the admin model I am looking at
        &from_field=users  # the M2M field this request is supposed to populate
        &object_id=1  # the object ID I am looking at, N/A if I am creating a new object

then there is no need to send all the M2Ms back to grappelli.

**Comment by sehmaschine** [comment]
When loading the M2M field (initially), we need to send all IDs to the server – because we need the representations in order to display the selected values. Searching on the other hand works like you just mentioned (unless there's a bug I'm not aware of).

**Comment by 1337** [comment]
Good point, sorry about that. Hmm, do you happen to know if django can tell us the order of an M2M's relations from the server side?

**Comment by sehmaschine** [comment]
Django just tells us the IDs. The order should be like you defined with the related model.
I'm closing this for now since I don't think we can solve this unless Django gives us both the ID and a display value for related fields.
