### ISSUE TITLE
Style bug with django-filebrowser after update Grappelli 2.10.1 > 2.10.2

### ISSUE THREAD

**Issue by raagin** [sehmaschine/django-grappelli#836]
I found that something wrong with table styles in django-filebrowser file list. See screenshot
![screen shot 2018-02-20 at 17 53 07](https://user-images.githubusercontent.com/5389817/36430753-fa0bb72c-1666-11e8-9a87-bf5ffb08d4aa.png)

Grappelli 2.10.2 
FileBrowser 3.9.1
Django 1.11.9

**Comment by parsch** [comment]
will be fixed with https://github.com/sehmaschine/django-filebrowser/issues/348
