### ISSUE TITLE
the collapsible option doesn't work on InlineModelAdmins

### ISSUE THREAD

**Issue by mahmoodi** [sehmaschine/django-grappelli#838]
```python
class MyModelInline(admin.TabularInline):
        model = MyModel
        classes = ['collapse']
```
The `classes = ['collapse']` option should make the MyModelInline collapsible in admin site but it doesn't work.

**Comment by sehmaschine** [comment]
The classes are prefixed with `grp`, so it is `grp-collapse`. Did you find a reference to `collapse` (without the prefix) in the docs?

**Comment by mahmoodi** [comment]
No the docs says use `grp-collapse`. I just thought that it should work with the default classes from Django.
Sorry, my mistake.
