### ISSUE TITLE
Make it easier to override action select box

### ISSUE THREAD

**Issue by atodorov** [sehmaschine/django-grappelli#839]
We're using django-grappelli for Kiwi TCMS and one of our users reports an issue where they want us to remove the action select box and in this case replace it with a DELETE button on the top:
https://github.com/kiwitcms/Kiwi/issues/221

![screenshot](https://user-images.githubusercontent.com/918446/36311597-148bc472-132c-11e8-9b33-5d6254d8cc24.png)

Looking at the templates it looks like:

1) Using `object-tools` block we can add more buttons at the top of the screen so easy to add a Delete button. Question is how does this button handle multiple selections ?

2) Not so easy to disable/remove the action select box.

Can you give some hints/comments on this ?

**Comment by sehmaschine** [comment]
Removing the actions is part of the `ModelAdmin` (see Django docs). With `object-tools` you are (probably) not able to retrieve multiple values. Both issues are related to Django, not to Grappelli.
