### ISSUE TITLE
Feature Request: autocomplete with list_editable

### ISSUE THREAD

**Issue by dhaavi** [sehmaschine/django-grappelli#845]
It would be great to also have autocomplete on m2m fields in the change list.

I know, m2m fields normally don't work with `list_editable`, but this little gist helps you around that problem: https://gist.github.com/efimerdlerkravitz/6177b656563e86f57f1fb81c1a18bf85
And with awesome grapelli, m2m fields are as sleek as fk fields. :)

**Comment by sehmaschine** [comment]
Sorry, but we decided to not support this.
