### ISSUE TITLE
Related widget misses the edit and delete link

### ISSUE THREAD

**Issue by atleta** [sehmaschine/django-grappelli#848]
Hi,

The edit and delete icons are missing from all related widgets so one can only add a new related object (or select an existing one) but not edit (or delete) it. I've looked into the issue and it seems that those parts of the widget HTML (`admin/widgets/related_widget_wrapper.html`) are commented out. The reason being probably that the JavaScript (`admin/js/admin/RelatedObjectLookups.js`) that should update the links is out of sync.

I managed to fix it locally, if you're open, I can attach a patch or make a pull request. (Couple of lines, really.)

VERSIONS: django-grappelli==2.11.1, Django==2.0.6
STATICFILES: OK
JAVASCRIPTS: OK
CUSTOMIZATIONS: None (except overriding the above mentioned two files to fix the issue)

**Comment by sehmaschine** [comment]
PR is welcome, if you're able to resolve the inconsistencies (see #618).

**Comment by sehmaschine** [comment]
Solved with 2.12.2.
