### ISSUE TITLE
При открытии страницы ошибка установил django-grappelli по инструкции

### ISSUE THREAD

**Issue by Monster-Venum** [sehmaschine/django-grappelli#854]
После установки по инструкции когда сохраняю либо открываю страницу ошибка
вот код ошибки 
Error during template rendering
In template C:\Users\vasil\Desktop\qwert\qwert\lib\site-packages\grappelli\templates\admin\base.html, error at line 0
'str' object has no attribute 'app_label'

<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE\|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<meta charset="utf-8" />
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}

{% block stylesheets %}

**Comment by Monster-Venum** [comment]
After installation instructions when I save or open the error page
here is the error code
Error during template rendering
In template C:\Users\vasil\Desktop\qwert\qwert\lib\site-packages\grappelli\templates\admin\base.html, error at line 0
'str' object has no attribute 'app_label'

{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}

<title>{% block title %}{% endblock %}</title> {% block blockbots %}{% endblock %} {% block stylesheets %}

**Comment by sehmaschine** [comment]
does it work without grappelli?

**Comment by sehmaschine** [comment]
closing this since no further details are given. please reopen with additional details and clarify if it works without grappelli.
