### ISSUE TITLE
TextArea Field Widget is redused after adding help_text to the field

### ISSUE THREAD

**Issue by satels** [sehmaschine/django-grappelli#856]
![2018-08-08_21-14-11](https://user-images.githubusercontent.com/220572/43856360-f59343c6-9b50-11e8-80a7-5a932c80cb75.png)

**Comment by parsch** [comment]
@satels I cannot reproduce this, also not sure what kind of field you're talking about but it's definitely no `textarea`. From the screenshot it looks like this could be a `OneToOneField`, which has the same width with and without help_texts:

<img width="368" alt="grp_o2o_without_helptext" src="https://user-images.githubusercontent.com/206830/43861374-e9467bf0-9b56-11e8-97af-2b1d04eb350a.png">
<img width="362" alt="grp_o2o_with_helptext" src="https://user-images.githubusercontent.com/206830/43861389-ef1b69a0-9b56-11e8-8ceb-a3c281314f84.png">

Can you (a) please specify what kind of field you're concerned about and (b) send some screenshots how it looks _before_ and _after_ you added a help_text?

Please add some information on the Grappelli version you're using, as well.

**Comment by parsch** [comment]
@satels You might also provide your `models.py`definition...

**Comment by satels** [comment]
Sorry, I meant a MutliSelectField

**Comment by satels** [comment]
```python
providers = models.ManyToManyField(
    'providers.Provider',
    blank=True,
    related_name='users_set',
    verbose_name='Провайдеры в новых кампаниях',
    help_text='Провайдеры в новых кампаниях пользователя по-умолчанию',
)
```

**Comment by satels** [comment]
May be you add this css to screen.css?

```css
select[multiple]:focus {
    height: auto;
}
```

or

```css
select[multiple] {
    height: auto;
}
```
