### ISSUE TITLE
Grappelli breaks on Django 2.1; has problem with render() function fieldsets template

### ISSUE THREAD

**Issue by hypercodex** [sehmaschine/django-grappelli#858]
Issue pops up when rendering this template file in the admin: /grappelli/templates/admin/includes/fieldset.html

Here is the top part of the django error page:

```
TypeError
render() got an unexpected keyword argument 'renderer'
/usr/local/lib/python3.6/site-packages/django/forms/boundfield.py in as_widget, line 93
/usr/local/bin/python3
3.6.5
['/code',  '/usr/local/lib/python36.zip',  '/usr/local/lib/python3.6',  '/usr/local/lib/python3.6/lib-dynload',  '/usr/local/lib/python3.6/site-packages']
```

**Comment by Madi7** [comment]
I have the same problem, grappelli is unusable on Django 2.1

**Comment by sehmaschine** [comment]
Yes. The current version of grappelli is not compatible with Django 2.1 (see README).

**Comment by hypercodex** [comment]
@sehmaschine Yep, understood. Reporting just for future versions; whenever support is planned. Is there a roadmap document anywhere? 

ps. thanks for the excellent jazzy admin

**Comment by sehmaschine** [comment]
I don't think this is related to grappelli since we don't define any fields. Please reopen with more details if you think this is a grappelli issue.
