### ISSUE TITLE
#grp-content cut off because of top padding

### ISSUE THREAD

**Issue by douglance** [sehmaschine/django-grappelli#871]
```
django==1.11.16
django-grappelli==2.10.4
```

Here is the default look: 
![screen shot 2018-11-27 at 2 31 42 pm](https://user-images.githubusercontent.com/4741454/49106443-2f9ea900-f251-11e8-808d-bda638d062d9.png)

Here it is when I changed from `#grp-content {top: 80px}` to `#grp-content {top: 120px}`
![screen shot 2018-11-27 at 2 31 32 pm](https://user-images.githubusercontent.com/4741454/49106437-2ca3b880-f251-11e8-9ff1-ccdf9a7e19f7.png)

**Comment by douglance** [comment]
I had a custom admin template.

**Comment by jqsjqs** [comment]
https://github.com/sehmaschine/django-grappelli/issues/758
