### ISSUE TITLE
Number of selected items duplicates

### ISSUE THREAD

**Issue by stiko** [sehmaschine/django-grappelli#876]
It looks like the selected count isn't working, instead it displays it next to it

<img width="470" alt="screen shot 2019-01-12 at 6 52 32 am" src="https://user-images.githubusercontent.com/8698522/51072941-97f5ee00-1637-11e9-83df-ded408b431dc.png">

**Comment by sehmaschine** [comment]
which version (django & grappelli)?

**Comment by stiko** [comment]
Django (2, 1, 4, 'final', 0)
Grappelli 2.12.1

**Comment by sehmaschine** [comment]
you don't have any custom templates, right?

**Comment by stiko** [comment]
No, I just added grappeli and using only Available Settings so far

**Comment by stiko** [comment]
I think clearing the cache and removing `static/` folder in development solved my issue
