### ISSUE TITLE
[Question] How sort a model?

### ISSUE THREAD

**Issue by jfajardo** [sehmaschine/django-grappelli#880]
How sort items from a model without foreign key?

```
class Service(models.Model):
    name = models.CharField(max_length=120)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)
```

**Comment by jfajardo** [comment]
Have you a example with Inline Sortables for a model without foreign key, this example if for relations
https://django-grappelli.readthedocs.io/en/latest/customization.html#rearrange-inlines

thanks

**Comment by sehmaschine** [comment]
I don't think that inlines are possible without a foreign key. But again – that's more a general question with regards to Django, not Grappelli.

**Comment by jfajardo** [comment]
Thanks
