### ISSUE TITLE
Stylesheet overrides django_select2 widgets

### ISSUE THREAD

**Issue by florianm** [sehmaschine/django-grappelli#884]
Using django_select2 autocompletes in django_grappelli works pretty well, except for some styling issues which are probably caused by the "!important" grapelli styles.

This rule from [screen.css](https://github.com/sehmaschine/django-grappelli/blob/master/grappelli/static/grappelli/stylesheets/screen.css) causes some unsightly overlap, e.g. in the [select2_modelform](https://django-easy-select2.readthedocs.io/en/latest/reference.html#easy_select2.utils.select2_modelform) dropdown widget:

```
.grp-tools.grp-related-widget-tools {
    position: absolute;
    right: -30px;
    top: 2px;
    z-index: 1;
```

![grap_bad](https://user-images.githubusercontent.com/762815/53068612-0f128200-3514-11e9-8471-c1e56b1da09c.png)

Disabling `position` and `right` rules in the browser rectifies the layout temporarily:
![image](https://user-images.githubusercontent.com/762815/53068656-2f424100-3514-11e9-8239-89e5e8582d97.png)

A temporary fix is to override the style in a custom `admin/change_form.html`:
```
{% extends "admin/change_form.html" %}
{% load staticfiles %}

{% block stylesheets %}
{{ block.super }}
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"><! -- favicon -->
<style>
.grp-tools.grp-related-widget-tools {position: relative; right: 0px;}
</style>
{% endblock %}
```

**Comment by parsch** [comment]
@florianm Thanks, good catch, that's related to using the `django_select2` widget. Basically, there are 2 possible solutions I want to discuss internally, I'll get back with a fix.

**Comment by florianm** [comment]
@parsch thanks for the quick turnaround! I just installed master 
```
pip install -e git+https://github.com/sehmaschine/django-grappelli#egg=django-grappelli
```
and disabled my CSS overrides in my custom `admin/change_form.html`

```
/* Fix https://github.com/sehmaschine/django-grappelli/issues/884 */
// .grp-tools.grp-related-widget-tools {position: relative; right: 0px;}
```
but the overlap is still there. What could I be doing wrong? Should I wait for the next release?
No urgency, as my CSS patch works well enough!

**Comment by parsch** [comment]
@florianm changes are now available with the master (have been applied to stable/2.12.x only before).

**Comment by florianm** [comment]
@parsch Thanks for the fix, confirmed working now on my end.

I'm installing django-grappelli master with
```
pip install -e git+https://github.com/sehmaschine/django-grappelli@master#egg=django-grappelli
```

Not related to django-grappelli, but part of the CSS problem screenshotted above:
I had to fix django-select2 as @nuarhu showed at https://github.com/applegrew/django-select2/issues/252 with `'data-width': '50em'`:

```
# in admin.py
from easy_select2 import select2_modelform

class MyModelAdmin(admin.ModelAdmin):
    """Admin for MyModel with django-select2 widgets with min width of 50 em."""
    form = select2_modelform(MyModel, attrs={'data-width': '50em'})
```
