### ISSUE TITLE
grappelli urls don't match

### ISSUE THREAD

**Issue by bukosabino** [sehmaschine/django-grappelli#886]
Hi all,

I follow the steps here: https://django-grappelli.readthedocs.io/en/latest/quickstart.html

But, I get:

```
grappelli/ ^lookup/related/$ [name='grp_related_lookup']
grappelli/ ^lookup/m2m/$ [name='grp_m2m_lookup']
grappelli/ ^lookup/autocomplete/$ [name='grp_autocomplete_lookup']
grappelli/ ^switch/user/(?P<object_id>\d+)/$ [name='grp_switch_user']
The current path, grappelli/, didn't match any of these.
```

I use Django==2.1.3 and django-grappelli==2.12.2

**Comment by sehmaschine** [comment]
Why did you try to serve the path /grappelli/ in the first place?

**Comment by bukosabino** [comment]
Hi @sehmaschine 

I would like to change the admin panel interface using the grappelli interface.

Can I do it directly? Or I need setup my grappelli dashboard? https://django-grappelli.readthedocs.io/en/latest/dashboard_setup.html

**Comment by sehmaschine** [comment]
the dashboard is optional.
you know that /grappelli/ is not your admin URL, right? it's just a path for views used with lookups. you still define your admin URL (Isee quickstart).

**Comment by bukosabino** [comment]
Ok, I only needed to point to usual admin url.

Thank you.
