### ISSUE TITLE
M2M filter_horisontal/filter_vertical incorrect field display

### ISSUE THREAD

**Issue by Yuego** [sehmaschine/django-grappelli#889]
![m2m](https://user-images.githubusercontent.com/951586/55881889-8da2ac00-5bb4-11e9-9ea7-d1256e1f4042.png)

Everything can be seen in the screenshot.
Empty project. App with two models.
Django 2.1.7
Grappelli 2.12.2

models.py:

    from django.db import models
    class Tst1(models.Model):
        name = models.CharField('Name', max_length=50)
    class Tst2(models.Model):    
        tst = models.ManyToManyField(Tst1, verbose_name='tst1')

admin.py
    from django.contrib import admin

    from tst.models import *

    @admin.register(Tst1)
    class Tst1Admin(admin.ModelAdmin):
        pass

    @admin.register(Tst2)
    class Tst2Admin(admin.ModelAdmin):
        filter_horizontal = (
            'tst',
        )

**Comment by parsch** [comment]
@Yuego Which browser are you using? First guess is that this is similar to #857

**Comment by Yuego** [comment]
Firefox 66.0.2.
Yes that's it (#857). I searched, but did not find.

**Comment by parsch** [comment]
I also tested with Firefox 66.0.2 but I'm having a correct display here:

<img width="1673" alt="Bildschirmfoto 2019-04-10 um 16 46 01" src="https://user-images.githubusercontent.com/206830/55888790-503c1f80-5bb0-11e9-84ac-2a1a427b0bc8.png">

I'm not sure if this is related to styles, do you have any other customisations in place?

**Comment by Yuego** [comment]
My mistake.
Grappelli was incorrectly installed. Reinstallation solved the problem.
