### ISSUE TITLE
Add more info about Grappelli to FAQ

### ISSUE THREAD

**Issue by KevinVerre** [sehmaschine/django-grappelli#892]
Currently, the FAQ in the docs is missing a lot of good info. For example, it says "If you like Django admin, don't use Grappelli." and "We hope to become obsolete someday". But I think you should also talk about the advantages of Grappelli, like it makes things look prettier and easier to add new rows and such. Also, a brief introduction to how it was made and how the user will eventually install and use it.

**Comment by sehmaschine** [comment]
Good point. The phrase "We hope to become obsolete someday" is about 10 years old and (unfortunately) we still need to do Grappelli, so I guess we can remove this. I don't agree with notes about the installation, because that's covered with the quickstart.

**Comment by mikedew** [comment]
Further to the specific statement to not use Grappelli if you like the Admin interface how do you avoid using Grappelli when django-tinymce makes it a dependency? I don't need Grappelli but when I omit it from INSTALLED_APPS the Django Admin collapsible inlines all open up and lose their (Show/Hide) links. Maybe the FAQs could explain an absolute minimal Grappelli installation when the primary need is for TinyMCE.

**Comment by sehmaschine** [comment]
I don't think that grappelli is a requirement for django-tinymce. If it is, you should discuss that with the developers of django-tinymce. IMO these packages should not rely on each other. We will probably remove TinyMCE from grappelli in the future.
