### ISSUE TITLE
Responsive Admin / Mobile Friendly

### ISSUE THREAD

**Issue by JacoBezuidenhout** [sehmaschine/django-grappelli#893]
Good day,

Are there any plans to make Grappelli mobile-friendly / Responsive in the future?

**Comment by sehmaschine** [comment]
Unfortunately, there are no plans. We (and our customers) don't need a mobile-friendly version ourselves and since we do this in our spare time, there are not enough resources to tackle this issue. That said, there's still a slight chance we might work on this in the future.

**Comment by tylerecouture** [comment]
A bootstrap version of grapelli would be so awesome...
