### ISSUE TITLE
Django 2.2 compatibility

### ISSUE THREAD

**Issue by sehmaschine** [sehmaschine/django-grappelli#894]

**Comment by sehmaschine** [comment]
See Branch stable/2.13.x for compatibility with Django 2.2. It seems to work fine with my local setup, but (unfortunately) I'm not able to run the tests anymore due to SQLite contraints (most probably). If anyone has an idea on how to fix that, please let me know – I just spent about a day figuring it out but had to give up for now.

**Comment by rcooke** [comment]
I'm seeing this in my DEV setup as well.  Most of the posts I have read are along the lines "its time to mature and switch to a real DB even for testing" kind of thing.

**Comment by sehmaschine** [comment]
@rcooke thanks, but that doesn't help. similar error with postgres.
