### ISSUE TITLE
Related widgets don't show add-another icon

### ISSUE THREAD

**Issue by sonarun** [sehmaschine/django-grappelli#895]
The latest Grappelli no longer shows the add-another plus icon when there is more than one field on the related fields inline. 

The grp-related-widget-tools is using "display-inline" which doesn't seem to allow the relative positioning of the elements to expand. What we are stuck with is the add-another tool is wrapped below and hidden. Changing "display-inline" to "flex" solves the issue.

![Screen Shot 2019-05-15 at 4 49 23 PM](https://user-images.githubusercontent.com/593557/57785437-07890080-7732-11e9-9eae-f8806b9afa14.jpg)

**Comment by sonarun** [comment]
Fix will look like this with related widgets. 
![Screen Shot 2019-05-15 at 4 58 48 PM](https://user-images.githubusercontent.com/593557/57786095-2c31a800-7733-11e9-92b6-d039592b2325.jpg)

**Comment by sehmaschine** [comment]
which version of grappelli/django are you using?

**Comment by sonarun** [comment]
I am using the latest 

django-grappelli      2.12.3

**Comment by sehmaschine** [comment]
ok. thanks. we'll take a look.

**Comment by sehmaschine** [comment]
@parsch looks good to me. any objections?

**Comment by parsch** [comment]
looks good, thanks for the patch, merged it.
