### ISSUE TITLE
Anyway to make the admin filter "atomic"?

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#897]
A client with 6 or so items in his inventory admin filter notes its annoying if he wishes to do filtering on multiple fields.  That is, as he selects one filter choice, the filter list closes and he has to wait until the page reloads with that filter applied.  

He would rather there was a "mode" flag and when in "Manual" mode, he could select as many items as he wants, then click "GO" to apply them all at once.

I don't see anything in the current docs or issues list, is this something you have considered already?

My config:
    python 3.6
    Package              Version   Location                            
    -------------------- --------- ------------------------------------
    certifi              2018.8.24 
    daiquiri             1.5.0     
    Django               2.0.13    
    django-admin-locking 1.6       /home/rcooke/source/dj_admin_locking
    django-appconf       1.0.2     
    django-extensions    2.1.2     
    django-filebrowser   3.10.1    
    django-grappelli     2.11.1    
    django-staticfiles   1.2.1     
    factory-boy          2.11.1    
    Faker                1.0.2     
    feedparser           5.2.1     
    idna                 2.7       
    Pillow               5.2.0     
    pip                  19.0.3    
    python-dateutil      2.8.0     
    pytz                 2018.5    
    selenium             3.141.0   
    setuptools           39.0.1    
    simplejson           3.16.0    
    six                  1.11.0    
    text-unidecode       1.2       
    unicodecsv           0.14.1    
    urllib3              1.23      
    Werkzeug             0.14.1    
    wheel                0.31.1  

Thanks in advance!
Rich.

**Comment by sehmaschine** [comment]
I see your point and I mostly agree. Would be nice to have a custom setting for either choosing between the current version and a submit button. @parsch What do you think?

**Comment by rcooke** [comment]
Anybody seen or hear of anything other package or library that adds this option?  Before I start digging, it would be nice to have some starting points?

**Comment by parsch** [comment]
@rcooke I implemented the mentioned functionality, it can be used by defining `change_list_template` in the ModelAdmin, there are 2 options:

**1) Filters as drop-down, manually applied:**

`change_list_template = "admin/change_list_filter_confirm.html"`

**2) Filters in a sidebar, manually applied:**

`change_list_template = "admin/change_list_filter_confirm_sidebar.html"`

**Comment by rcooke** [comment]
Thanks Parch et al!  I'm going to test this out asap!

**Comment by rcooke** [comment]
I merged this repo's MASTER to my FORK repo's MASTER for testing on my DEV server.  What version will this change be incorporated into next (and when)?  I'll squeal like a pigglet if I find any problems....

**Comment by rcooke** [comment]
Works great, but users did find what appears to be a bug:
#903
