### ISSUE TITLE
add button in home page is so small 

### ISSUE THREAD

**Issue by chaouiy** [sehmaschine/django-grappelli#898]
It would be more user friendly if you can make add button bigger in home page, the small `+` icon need an effort to make cursor exactly on the icon.

**Comment by rcooke** [comment]
You can customize any of the HTML, CSS or JS.  For small tweaks like that, I add my own Javascript module and handle it in there.

Also is it small in proportion to the rest of the page?  Many pages look much better if you press CTRL-+ a few times.

**Comment by parsch** [comment]
@chaouiy While I agree this can't be improved in an isolated way as it depends on many aspects of its surrounding general layout. Unfortunately we currently can't find the time to overhaul the complete look & feel of Grappelli.
