### ISSUE TITLE
Inline items counter

### ISSUE THREAD

**Issue by TomaszBernat96** [sehmaschine/django-grappelli#902]
Hi,

I use your project for a couple of moths so far and now i have stucked with adding counter of presented items in linline. I searched thorugh docs but i haven't found any solution to my problem. I want to show number of visible items next to inlines' title.

I need something like this :
![grappeli-example](https://user-images.githubusercontent.com/26420483/62713700-78704980-b9fd-11e9-8da1-285daa05b158.png)

**Comment by rcooke** [comment]
I think that HTML comes from the modified ADMIN templates.  How comfortable are you with programming?

**Comment by sehmaschine** [comment]
@TomaszBernat96 you could add a custom js function in order to update the title.

**Comment by TomaszBernat96** [comment]
@rcooke Nope, it is generated based on grappeli's insides. It doesnt matter any more i did exactly as @sehmaschine has advised me. It works perfectly fine. I was just curious if it is possible to do just from grappeli's config files or sth. Thx anyway :D
