### ISSUE TITLE
Choices do not update on apply with Filters as drop-down, manually applied feature.

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#903]
I am using the new feature for "atomic" change list filters in 2.13.1 as documented [here](https://django-grappelli.readthedocs.io/en/2.13.1/customization.html#filters-as-drop-down-manually-applied).

Which was from #897 

I have 5 fields for filters. Starting from default, where no filters are set, a user can set two or more filters, press **APPLY** and it works as expected.

However, if the user then changes their choices and presses **APPLY**, _ONE_ of the changes will be lost - it will use the _previous_ value.

For example, when the user first opens the filter, the first two fields are set as:
 - Status: All
 - Customer: All

The user changes them to:
 - Status: Ordered
 - Customer: ACME

After pressing **APPLY** the properly filtered results are displayed.

Now the user changes to:
 - Status: Paid
 - Customer: TAI

After pressing **APPLY**, the results are _incorrect_, the filters are set to:
 - Status: Ordered
 - Customer: TAI

The _STATUS_ choice has stuck/reverted to the previously selected value.  Freaky.

My software versions:
```
(py37dj22) rcooke@Developer1:~/source/GNVO/django-DEV$ pip list
Package              Version     Location                            
-------------------- ----------- ------------------------------------
certifi              2019.6.16   
daiquiri             1.5.0       
Django               2.2.3       
django-admin-locking 1.6         /home/rcooke/source/dj_admin_locking
django-appconf       1.0.3       
django-debug-toolbar 2.0         
django-extensions    2.2.1       
django-filebrowser   3.11.1      
django-grappelli     2.13.1      
django-staticfiles   1.2.1       
factory-boy          2.12.0      
Faker                1.0.7       
feedparser           5.2.1       
idna                 2.8         
mysqlclient          1.4.2.post1 
Pillow               6.1.0       
pip                  19.2        
python-dateutil      2.8.0       
pytz                 2019.1      
selenium             3.141.0     
setuptools           41.0.1      
simplejson           3.16.0      
six                  1.12.0      
sqlparse             0.3.0       
text-unidecode       1.2         
tinycss2             1.0.2       
unicodecsv           0.14.1      
urllib3              1.25.3      
webencodings         0.5.1       
Werkzeug             0.15.4      
wheel                0.33.4      
xlrd                 1.2.0       
xlwt                 1.3.0

```

Python Version:
`Python 3.7.3 (default, Jun 19 2019, 13:36:51)`

Regards,
Richard Cooke

**Comment by parsch** [comment]
@rcooke Good catch, this might be a bit tricky because we have to deal with conflicting query parameters to solve that bug.

A brief introspection: each filter option holds the entire query parameters (including its own but also the other ones being present in the query string). If multiple filters are changed at once, there might be conflicts between parts of the query string which results in what you described.

**Comment by rcooke** [comment]
Heh.  No thanks to my testing, it was an end-user that found it!

I tried to debug the JS logic, but my diagnostic console logs rendered the code inoperable. So I shall wait until you can apply your big brain!

**Comment by parsch** [comment]
@rcooke I added a fix for that bug, testing would be appreciated.

**Comment by rcooke** [comment]
I merged branch 2.13.x into my master, checked that out onto my test machine.  Then I pip uninstalled the released version and pip installed -e my checkout.

When I try the filter, if I set two elements before clicking reply, it CLEARS them back to "all".

If I select one element, click apply, it works.  If I add a second element, click apply, it clears my second choice back to "all"!

Double checking the merge worked.  then I'll checkout branch 2.13.x and re-test.

**Comment by parsch** [comment]
I can't reproduce that, please make sure the latest `grappelli.js` or `grappelli.min.js` is loaded (you might have to run `collectstatic`).

**Comment by rcooke** [comment]
I use the Dev Server for testing, the static folder is empty since its suppose to pull right from the source and libraries.  I'll have to dig into that.  And I will try checking out that branch directly too.

**Comment by rcooke** [comment]
Finally got back to this.  I GIT cloned the latest master branch of your repo. Still getting strange behavior. Now its reducing the vertical size of the id="grp-content" article, cutting off the filter drop-down. I cant test it if I cant see the filter items! At first glance the JS files look like the right ones, and the static file history seems to be pulling from the checked out master. Really bizarre, even for a Monday.
