### ISSUE TITLE
related field proxy models

### ISSUE THREAD

**Issue by sandeepharlalka** [sehmaschine/django-grappelli#904]
The Widget for Related Field does not show up on Proxy Models. The snapshot of models below.

```
class Cct(Cd):
    class Meta:
        proxy = True

    objects = CctManager()
class T(models.Model):
    cd = models.OneToOneField(Cct, on_delete=models.PROTECT)

admin.py
    raw_id_fields = ('cd',)
    related_lookup_fields = {
        'fk': ['cd', ]
    }

```

**Comment by sehmaschine** [comment]
what's the behaviour with the vanilla admin? is this an issue with grappelli?

**Comment by sandeepharlalka** [comment]
Yes...

Sent from my iPhone

On 14-Aug-2019, at 4:00 PM, Patrick Kranzlmueller <notifications@github.com<mailto:notifications@github.com>> wrote:


what's the behaviour with the vanilla admin? is this an issue with grappelli?

**Comment by sehmaschine** [comment]
no issues here. did you register the proxy model?
