### ISSUE TITLE
Field Widths for read only fields in inlinetabular too small

### ISSUE THREAD

**Issue by dstrohl** [sehmaschine/django-grappelli#905]
When I create an InlineTabular model, and add some fields that are marked as read-only.  the css currently drives those to what looks like g-d-1.  This seems to be due to the grp-tools-container being set to "width:100%"  I changed the css file to set it to 50% and it seems to work fine.

I don't, however, know if that change will cause other problems, so I hesitate to say that's the "fix". 

At least to me, the preferred behavior would be for read-only fields to look the same as normal ones just without editing.

**Comment by parsch** [comment]
The width of form fields is based on a "widget-specific" CSS class which is derived from Django (e.g. `vIntegerField`).

Unfortunately, this CSS class is not provided in case of read-only fields so there's no possibility to make them "look the same as normal ones (just without editing)".

**Comment by dstrohl** [comment]
OK... but it did seem to work correctly when I changed the CSS width of the "grp-tools-container", which is provided... is there a problem with changing that?

**Comment by parsch** [comment]
Could you share screenshots (also showing the developer console logging CSS for the relevant DOM nodes)?
