### ISSUE TITLE
Improvement Request:  setup the grappelli_docs so that including them does not require changing the library code.

### ISSUE THREAD

**Issue by dstrohl** [sehmaschine/django-grappelli#907]
right now, to include the grappelli docs, I need to un-comment the docs lines in the grappelli/urls.py file.  this is pretty easy, but if/when I update grappelli, it's likely to be overwritten.

What feels like a better approach woudl be to have a second file, like docs_urls.py with the docs urls defined.  then the instructions would say somethign like, if you want to include the documentation, add another line to your urls file, like:

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('grappelli/grp_doc/', include('grappelli.docs_urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    ...
]

(here is what I did)
[docs_urls.txt](https://github.com/sehmaschine/django-grappelli/files/3513322/docs_urls.txt)

(without knowing enough about the overall grappelli design

**Comment by sehmaschine** [comment]
Sounds good.

**Comment by sehmaschine** [comment]
this does not solve the issue with the file being overwritten, right?

**Comment by dstrohl** [comment]
Actually it should, since the Grappelli.docs_urls file would be part of the library, if the user upgraded Grappelli, it would upgrade that file as well.  so as long as that docs_urls (or whatever) didnt change it woudl not matter.

**Comment by sehmaschine** [comment]
if we include the docs_urls with the main_urls and comment out the docs_urls (by default), and you change that line ... the issue still exists. ???

**Comment by dstrohl** [comment]
so, my suggestion was to split the docs urls from the main urls file.  (so nothing is commented in either file).  

Then in the instructions for installation, it would read something like:

> 
> 1.  in your urls.py file, add:
>     path('grappelli/', include('grappelli.urls')), # grappelli URLS
> 2.  if you would like to also include the Grappelli documentation, you can also add:
>     path('grappelli/grp_doc/', include('grappelli.docs_urls')), # grappelli docs URLS
> 

No uncommenting needed in any file.... make more sense?

**Comment by sehmaschine** [comment]
forget my last comment! I got it now ...
