### ISSUE TITLE
Autocomplete doesn't work in 2.13.1

### ISSUE THREAD

**Issue by atleta** [sehmaschine/django-grappelli#908]
After upgrading to 2.13.1 admin autocomplete fields don't work anymore in my project. The select fields, after loading the admin page, remain the plain old html version (with only a single value in them) instead of changing into the select2 widget. Seems to be a JS error. I checked the JS console but didn't see any exception or related log message there.

Downgrading grappelli to 2.12.3 eliminates the problem.

**Comment by sehmaschine** [comment]
we don't use select2. are you referring to the django autocompletes instead of grappelli?

**Comment by atleta** [comment]
Yep, sorry, I wasn't aware that you were using a different mechanism. I'm using django's standard `autocomplete_fields` setting on the model admin. With pre-2.13.1 these rendered properly, with 2.13.1 I get the plain html select field (with a single value) as explained above.

And the problem seems to be caused by you overriding django's `static/admin/js/autocomplete.js` file with a dummy one.

**Comment by sehmaschine** [comment]
this sounds really strange since pre-2.13.1, the functionality should be exactly the same. I don't see how this could be an issue with 2.13.1 only.

**Comment by sehmaschine** [comment]
solved with 12.3.x
