### ISSUE TITLE
Footer covering form content on chrome

### ISSUE THREAD

**Issue by CharlesStrickland** [sehmaschine/django-grappelli#910]
I've noticed that this happens on chrome (77.0.3865.90)
![Screenshot 2019-10-03 at 11 05 29](https://user-images.githubusercontent.com/26063597/66119409-7fb46d80-e5d0-11e9-9adb-8247d2e1d9ad.jpg)

while it renders with the expected spacing on firefox and safari

![Screenshot 2019-10-03 at 11 05 50](https://user-images.githubusercontent.com/26063597/66119457-9d81d280-e5d0-11e9-8806-4b4c97a1d3ef.jpg)

I've upgraded to 2.13.1 and this problem persists.

**Comment by parsch** [comment]
@CharlesStrickland Thanks for reporting
