### ISSUE TITLE
Autocomplete get method should also return "safe" label

### ISSUE THREAD

**Issue by ridwan-kazi** [sehmaschine/django-grappelli#917]
https://github.com/sehmaschine/django-grappelli/blob/89bc792a1291888204744193f32ba04707ac3c16/grappelli/views/related.py#L259

We are experiencing a xss vulnerability in our autocomplete fields because the return from this method is not escaping script tags. I am assuming your get_label_safe method would solve this issue.

**Comment by sehmaschine** [comment]
this line just returns a counter. do you mean ilne 244 instead?

**Comment by ridwan-kazi** [comment]
Yes, I meant the the return of the`get_data` method.

**Comment by ridwan-kazi** [comment]
`return [{"value": self.get_return_value(f, f.pk), "label": get_label(f)} for f in self.get_queryset()[:AUTOCOMPLETE_LIMIT]]` 
should be changed to 
`return [{"value": self.get_return_value(f, f.pk), "label": get_label(f), "safe": get_label_safe(f)} for f in self.get_queryset()[:AUTOCOMPLETE_LIMIT]]`

if Im reading your code properly ofcourse 😅

**Comment by ridwan-kazi** [comment]
@sehmaschine So I went ahead and made a fork to try the solution I stated above and it did not seem to work >.<, as in returning the `safe` field did not stop the autocomplete box from rendering the script tag I had inserted. I had to escape the return values for the method `get_label`, for the fix. Let me know what else you might suggest.

**Comment by sehmaschine** [comment]
@ridwan-kazi I'm not able to reproduce this. all tags are currently escaped with autocomplete fields.

can you give a more detailed example?
![Screenshot_2019-11-05 Change Entry Grappelli](https://user-images.githubusercontent.com/185432/68220860-c7238480-ffe8-11e9-87c7-ce887f591fff.png)

**Comment by ridwan-kazi** [comment]
You are correct. Strangely when we tried this before the field was not being escaped. Thanks!
