### ISSUE TITLE
Testing problems with patch 450ae71b9155b4a1d4ce68231cdc42cef922f975

### ISSUE THREAD

**Issue by rcooke** [sehmaschine/django-grappelli#921]
This is a fix for #903 and #897.

While testing this here and at the head of master branch, I observe odd behavior. 

My model has 9 filters, some are for fields in related dbs.  Lets say Filter1 (F1) and Filter2 F2) are fields on the db.  And Filter3 (F3) is a field on a related db.

If I set any ONE of F1, F2, or F3 it works as expected.

After setting F1 to a value, such as:
**http://127.0.0.1:8000/admin/repair/job/?F1__exact=20**

If I _change_ F1 to another value, such as "45", after pressing APPLY I get:
**http://127.0.0.1:8000/admin/repair/job/?F1__exact=20&F1__exact=45**
This appears to be displaying the correct query set. But I'm sure having the query string in the URL twice will cause problems at some point.

Some combinations of the filters, if set at the same time are ignored.  Trying to change one or more values after getting a compound filter to "stick" are still ignored.

I did a local checkout of the exact commit for your fix.  And I use Debug Toolbar to verify all files are loading from the GIT folder.  And, since I'm testing with the debug server all static files and templates are loaded from their source folders - collect static is not needed (actually has no effect I think).

What should I test or poke at next?

**Comment by tdruez** [comment]
See also https://github.com/sehmaschine/django-grappelli/issues/918

**Comment by sehmaschine** [comment]
should be solved
