### ISSUE TITLE
Is it possible to add `onclick` parameter for modules.LinkList?

### ISSUE THREAD

**Issue by max-block** [sehmaschine/django-grappelli#923]
I'd like to have some dangerous links in my dashboard like this:

`
<a href="#" onclick='return confirm("Are you sure?");'>Delete important data</a>`

**Comment by sehmaschine** [comment]
Why don't you just inherit LinkList and add the custom behaviour?

**Comment by sehmaschine** [comment]
I'm closing this since IMO it is pretty easy to achieve with the current behaviour.
