### ISSUE TITLE
Side-scrolling broken between 2.13.1 to 2.13.2

### ISSUE THREAD

**Issue by demerzel21** [sehmaschine/django-grappelli#925]
On upgrading to 2.13.2, scrolling left to right is no longer possible on a narrow interface.

**Comment by 007gzs** [comment]
https://github.com/sehmaschine/django-grappelli/blob/e7fa56d1c541f85e71fd635689060b298647e3c4/grappelli/compass/sass/screen.scss#L331
clearfix has overflow:hidden
so change_list view will hidden scroll-x

it is added in https://github.com/sehmaschine/django-grappelli/commit/9ba7825cca1b3f7ab41d38bb7641e28b818bfbf0
