### ISSUE TITLE
Rearrange inlines

### ISSUE THREAD

**Issue by Jean-Zombie** [sehmaschine/django-grappelli#928]
**I am not able to rearrange my inlines in the admin interface.**
I read the [documentation](https://django-grappelli.readthedocs.io/en/latest/customization.html#rearrange-inlines) and this open [issue](https://github.com/sehmaschine/django-grappelli/issues/355).

As far as I understand is the key to have a `placeholder` class and 

>  a 2nd class which matches the class of the inline-group (which depends on your fieldsets). If you have an inline images the class would probably be images-group.

So give my inline model:
```
class MyInlineModel(admin.TabularInline):
    model = MyModel
    extra = 1
```
I'd expect the 2nd classes name to be `MyInlineModel-group`. Although I am unsure what 
> which depends on your fieldsets

from above exactly means 😄 .

This is my adapted code:
```
("Some Fieldset", {
    "classes": ("grp-collapse grp-open",),
    "fields": ("whatever",)
}),
("Rearranged Inline", {"classes": ("placeholder MyInlineModel-group",), "fields" : ()}),
("Another Fieldset", {
    "classes": ("grp-collapse grp-open",),
    "fields": ("whatever",)
}),

inlines = [MyInlineModel]
```
But I still have my inline at the end. I am afraid I might miss something obvious here 😄 .

**Comment by sehmaschine** [comment]
check the 2nd class by removing the whole placeholder-stuff. I guess it is something like `myinlinemodel-group` (lowercase), but you can easily check with a DOM inspector.

**Comment by Jean-Zombie** [comment]
🤦‍♂ I was under the impression the `-group`-suffix was a Grappeli thing. The DOM inspection did the trick. My inline models class name is rendered as `myinlinemodel_set-group`.

Thx for the quick help!
