### ISSUE TITLE
Using grappelli verbose_name_plural

### ISSUE THREAD

**Issue by ruslankrivoshein** [sehmaschine/django-grappelli#938]
I have a model, i.e. Key, with verbose_name 'Key'. I'd like to have an opportunity to set a name for this model in `ModelList.models`. So I wanna see the subsection not with "Key" name, but with "Key management". Am I able to do this?

**Comment by sehmaschine** [comment]
how is this related to grappelli?

**Comment by ruslankrivoshein** [comment]
Directly. I pass models to ModelList from grapelli.

**Comment by sehmaschine** [comment]
`verbose_name` is a Django setting. We don't override this ... see https://docs.djangoproject.com/en/3.0/ref/models/options/#verbose-name

**Comment by ruslankrivoshein** [comment]
I'm sorry. Obviously, I named this issue wrong...
I meant the following: grappelli does `model_dict['title'] = capfirst(model._meta.verbose_name_plural)`, when creates dashboard. So I'd like to name a subsection other way.

**Comment by sehmaschine** [comment]
sorry, I still don't get it. why don't you rename `verbose_name_plural` then?

**Comment by ruslankrivoshein** [comment]
Just to keep semantic...
Okay, I got. So I do this. Danke schon für schnelle Reaktion! :)
