### ISSUE TITLE
add django-constance collapsablefieldsets support

### ISSUE THREAD

**Issue by horpto** [sehmaschine/django-grappelli#945]
Hi, new version of django-constance has cool feature like collapsable fieldsets ([changelog](https://django-constance.readthedocs.io/en/latest/changes.html#v2-7-0-2020-06-22)). But unfortunately it's not work with grappelli as django-constance renewed `admin/constance/change_list.html` template.

**Comment by sehmaschine** [comment]
happy to look into that if somebody comes up with a PR

**Comment by sehmaschine** [comment]
closing this since no PR has been submitted. please note that we cannot maintain 3rd-party packages and need to rely on contributors to do so.
