### ISSUE TITLE
GRAPPELLI_AUTOCOMPLETE_LIMIT setting

### ISSUE THREAD

**Issue by belthaZornv** [sehmaschine/django-grappelli#946]
The `GRAPPELLI_AUTOCOMPLETE_LIMIT` or the default value of `10` is not working with `autocomplete_fields` in the `ModelAdmin` - I just get all the records, am I missing something?

**Comment by sehmaschine** [comment]
`autocomplete_fields` is a Django field. That's different from the grappelli autocomplete field. You can use both, but the grappelli setting only affects the grappelli field.

**Comment by belthaZornv** [comment]
Ah! ok thanks @sehmaschine, is there the equivalent from Grappelli? I can't seem to find the attribute.

**Comment by sehmaschine** [comment]
https://django-grappelli.readthedocs.io/en/latest/customization.html#autocomplete-lookups
