### ISSUE TITLE
Some questions about integrating DjangoUeditor

### ISSUE THREAD

**Issue by CavalierSpirit** [sehmaschine/django-grappelli#950]
When I use django-grappelli and DjangoUeditor at the same time，some trouble will happening. Such as,
1. DjangoUeditor toolbars can't adapt the edit box to wrap;
2. django-grappelli full screen button does not work in Firefox, but it is ok in Google Chrome.

**Comment by sehmaschine** [comment]
There is a google group for asking questions:
https://groups.google.com/g/django-grappelli

Since this mainly refers to DjangoUEditor (I personally don't know this package), you might consider asking there.
