### ISSUE TITLE
ManyToMany selector is hidden in some browsers

### ISSUE THREAD

**Issue by meloman-a** [sehmaschine/django-grappelli#960]
Hi, we use the last version "2.14.3" at this moment and experience some unexpected behavior: one field is hidden is some browsers.
![image](https://user-images.githubusercontent.com/47209077/112721581-6f135800-8f26-11eb-93ef-b712422abded.png)
It will show up, It the class "social_network" is renamed to something else:
![image](https://user-images.githubusercontent.com/47209077/112721586-73d80c00-8f26-11eb-8351-43d057a670cd.png)
Can you help, please?

**Comment by sehmaschine** [comment]
Did you custimize anything? Do you use any other 3rd-party packages which could interfere? Besides, can you please check the css styles ... you should be able to see what exactly effects the visiblity.

**Comment by meloman-a** [comment]
Thank you!!! It was because of some extensions on browser!!! I am sorry for taking your time, hope it'll help to someone else.
