### ISSUE TITLE
When using DateTimeField, Button "Today" and "Now" overlaps with icons

### ISSUE THREAD

**Issue by XZ-XuZhang** [sehmaschine/django-grappelli#968]
Hi,

The field in the model is setup as
`date_joined = models.DateTimeField(blank=True, null=True)`

![image](https://user-images.githubusercontent.com/39953316/124297136-a7908680-db52-11eb-8b43-596e48381006.png)

**Comment by sehmaschine** [comment]
Just tested and I'm unable to reproduce this. Please check if all js/css are loaded. If the issue still exists, please reopen with additional details.
