### ISSUE TITLE
Missing CSS styles for grp-danger resulting in error messages in blue color

### ISSUE THREAD

**Issue by atodorov** [sehmaschine/django-grappelli#970]
In my admin forms I use `messages.add_message()` with the `messages.ERROR` type which results in list items with the `grp-danger` class. 

For all I can tell this class is not defined inside grappelli's CSS files and the result is that I get error messages with a blue background as you can see in the image below. 

Version is 2.15.1 with Django==3.2.5.

![blue_error](https://user-images.githubusercontent.com/1002300/125165849-670fb900-e1a1-11eb-8f0f-25ece7ca1e28.png)

**Comment by parsch** [comment]
@atodorov If I'm not mistaken, there is no default message tag "danger", Grappelli only supports those default tags (see https://docs.djangoproject.com/en/3.2/ref/contrib/messages/#message-tags). Did you define a custom message tag?

**Comment by atodorov** [comment]
@parsch you are right, my bad. I had overriden the default class names like so:
```
MESSAGE_TAGS = {
    messages.ERROR: "danger",
}
```
