### ISSUE TITLE
update django-reversion template

### ISSUE THREAD

**Issue by dandicocco** [sehmaschine/django-grappelli#971]
Reversion 3.0.0 includes a [breaking change](https://django-reversion.readthedocs.io/en/stable/changelog.html#id11) in which `Revision.comment` now returns the raw JSON change message rather than a string, making for ugly object history comments. New method `Revision.get_comment` is now the recommended implementation. Grappelli's own version of Reversion's `object_history.html` still uses `Revision.comment`.

**Comment by sehmaschine** [comment]
Thanks for the heads up. We'll take a look at a PR if someone wants to submit one (we generally do not follow 3rd-party upddate and we do not use Revision ourselves).
