### ISSUE TITLE
`Select all` disappeared in v2.15.4

### ISSUE THREAD

**Issue by Kiougar** [sehmaschine/django-grappelli#985]
### The problem

Version `v2.15.4`:
![image](https://user-images.githubusercontent.com/8688777/149498623-0fafa5fd-dcc7-4479-b2a2-94268dcce5f2.png)

Version `v2.15.3`:
![image](https://user-images.githubusercontent.com/8688777/149498673-858bb223-c8a1-4b99-8002-ae4f81dd8a77.png)

### The cause?

I believe this was caused from #980 (specifically the ~removal of~ `actions.js`).
Grappelli's `actions.js` in `v2.15.3` adds an `.actions` method to the jquery object where Django's default [`actions.js`](https://github.com/django/django/blob/b0ed619/django/contrib/admin/static/admin/js/actions.js#L91) adds an `Actions` function to the `window` object.

---

edit: minor edits for clarity

**Comment by sehmaschine** [comment]
FYI, `actions.js` has not been removed. But yes – still possible that we've missed this. We'll check asap (if you want to fix it, please use stable/2.15.x for a PR).

**Comment by Kiougar** [comment]
> FYI, actions.js has not been removed.

Ah my bad, I misread the commits referenced in #980 👍 

> if you want to fix it, please use stable/2.15.x for a PR

I would like to fix it but I don't even know where to start looking.

**Comment by Kiougar** [comment]
I think I found something - I believe this is what causes the issue:

https://github.com/sehmaschine/django-grappelli/blob/8e0aa7402f916397278a77533b076b4055d2cc51/grappelli/compass/sass/partials/layout/_changelist.scss#L296-L300

Instead of using the above CSS rule, we need to simply add `hidden` to the `actions.html` template.

**Comment by sehmaschine** [comment]
I think your "fix" was not quite working. Please check mine (this works with my setup).

**Comment by Kiougar** [comment]
Yes you are right! Your change works 👍

**Comment by Kiougar** [comment]
Do we have an ETA for the release?

**Comment by sehmaschine** [comment]
ETA is the 21st of January.

**Comment by sehmaschine** [comment]
solved with 3.0.2 and 2.15.5
