### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [sehmaschine/django-grappelli#987]
Hey there!

I belong to an open source security research community, and a member (@ktg9) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by sehmaschine** [comment]
Thanks! I'll add a security note with the next update. In the meantime you can use `sehmaschine@gmail.com` to report security related issues.

**Comment by JamieSlome** [comment]
@sehmaschine - thanks for the update!

Just for reference, you can view the report directly here:

https://huntr.dev/bounties/6e2c7f10-a8d7-4ba4-b50f-387ced7ef455/

It is private and only accessible to maintainers with repository write permissions.

**Comment by sehmaschine** [comment]
@JamieSlome thanks. you can contact us via the mentioned email address.

**Comment by JamieSlome** [comment]
@sehmaschine - e-mail sent ❤️
