### ISSUE TITLE
Set field widths in inlinetabular

### ISSUE THREAD

**Issue by gamesbook** [sehmaschine/django-grappelli#993]
I have tried to look at the docs for this, but cannot find any simple way to set/override the width of fields - specifically text fields where the user will be filling in data - in the inline form.

Ideally, I would like to do something like this:
```
    class Meta:
        model = models.MyModel
        widgets = {
            'version': forms.TextInput(attrs={'size': 1}),
            'data_type': forms.TextInput(attrs={'size': 2}),
            'owner_key': forms.TextInput(attrs={'size': 3}),
        }
```

**Comment by sehmaschine** [comment]
you can use (custom) CSS for that

**Comment by gamesbook** [comment]
Thanks for the update.  As I said,  I was looking for a relatively simple way to do this within the Python code, but as you say, I will need to dig down into the CSS level to achieve this result.  

This might be worth considering as an additional "feature add" at some point,  as I think this is a fairly common use-case for tabular inline forms.
