### ISSUE TITLE
I cannot add a button using change_list.html

### ISSUE THREAD

**Issue by MaksFoxerProgrammer** [sehmaschine/django-grappelli#999]
I created the timetable\templates\admin\change_list.html, code in it:
`
{% extends "admin/change_list.html" %} {% load i18n %} 

{% block object-tools-items %}
    {{ block.super }}
    <li>
        {% comment %} <a class="historylink" href="test_data/">My custom admin page</a> {% endcomment %}
        <a href="#" class="grp-add-link grp-state-focus">Test</a>
    </li>
{% endblock %}
`

f you look at an ordinary admin (without grappelli), the button appeared If With it, then no button.

If you edit venv\Lib\site-packages\grappelli\templates\admin\change_list.html, The button appears, but it’s not the case...

How can I make grappelli see my button?

**Comment by MaksFoxerProgrammer** [comment]
`{% extends "admin/change_list.html" %} {% load i18n %} 

{% block object-tools-items %}
    {{ block.super }}
    <li>
        {% comment %} <a class="historylink" href="test_data/">My custom admin page</a> {% endcomment %}
        <a href="#" class="grp-add-link grp-state-focus">Test</a>
        прив))
    </li>
{% endblock %}`

**Comment by MaksFoxerProgrammer** [comment]
`{% extends "admin/change_list.html" %} {% load i18n %} `

`{% block object-tools-items %}`
    `{{ block.super }}`
    `<li>`
       ` {% comment %} <a class="historylink" href="test_data/">My custom admin page</a> {% endcomment %}`
        `<a href="#" class="grp-add-link grp-state-focus">Test</a>`
   ` </li>`
`{% endblock %}`

**Comment by sehmaschine** [comment]
just tried this and it works without any issues. did you make sure that templates are loaded with the filesystem first (and with apps afterwards)?
